# Generated by Django 4.2.15 on 2025-03-12 14:37

from django.db import migrations


def add_long_running_migration(apps, schema_editor):
    LongRunningMigration = apps.get_model(
        'long_running_migrations', 'LongRunningMigration'
    )  # noqa
    LongRunningMigration.objects.create(name='0009_backfill_attachment_model')


def noop(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            'long_running_migrations',
            '0008_backfill_organization_metadata',
        ),
    ]

    operations = [
        migrations.RunPython(add_long_running_migration, noop),
    ]
