# Generated by Django 4.2.28 on 2026-05-14 12:47

from django.db import migrations


def add_long_running_migration(apps, schema_editor):
    LongRunningMigration = apps.get_model(
        'long_running_migrations', 'LongRunningMigration'
    )
    try:
        lrm_0024 = LongRunningMigration.objects.get(
            name='0024_migrate_submission_supplement_qpaths'
        )
        if lrm_0024.status == 'failed':
            lrm_0024.status = 'created'
            lrm_0024.save()
    except LongRunningMigration.DoesNotExist:
        # this shouldn't happen, but if it does, there's nothing to do because
        # 0024 hasn't run yet
        pass


def noop(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('long_running_migrations', '0024_migrate_submission_supplement_qpaths'),
    ]

    operations = [
        migrations.RunPython(add_long_running_migration, noop),
    ]
