# Generated by Django 3.2.15 on 2024-02-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openrosa_form_disclaimer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formdisclaimer',
            table='openrosa_form_disclaimer_formdisclaimer',
        ),
    ]
