# Generated by Django 4.2.28 on 2026-04-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionservicelanguagem2m',
            name='location_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transcriptionservicelanguagem2m',
            name='model_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
