# Generated by Django 2.2.27 on 2022-07-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcriptionservice',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='translationservice',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='transcriptionservicelanguagem2m',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='translationservicelanguagem2m',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
