/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KoboToolbox API
 * Powerful and intuitive data collection tools to make an impact
 * OpenAPI spec version: 2.0.0 (api_v2)
 */
import type { AccessLogResponseMetadata } from './accessLogResponseMetadata'

export interface AccessLogResponse {
  user: string
  date_created: string
  username: string
  metadata: AccessLogResponseMetadata
  user_uid: string
  count: number
}
