/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KoboToolbox API
 * Powerful and intuitive data collection tools to make an impact
 * OpenAPI spec version: 2.0.0 (api_v2)
 */

/**
 * * `add-media` - Add Media
 * `add-submission` - Add Submission
 * `allow-anonymous-submissions` - Allow Anonymous Submissions
 * `archive` - Archive
 * `auth` - Auth
 * `clone-permissions` - Clone Permissions
 * `connect-project` - Connect Project
 * `create` - Create
 * `delete` - Delete
 * `delete-media` - Delete Media
 * `delete-service` - Delete Service
 * `delete-submission` - Delete Submission
 * `deploy` - Deploy
 * `disable-sharing` - Disable Sharing
 * `disallow-anonymous-submissions` - Disallow Anonymous Submissions
 * `disconnect-project` - Disconnect Project
 * `enable-sharing` - Enable Sharing
 * `export` - Export
 * `in-trash` - In Trash
 * `modify-imported-fields` - Modify Imported Fields
 * `modify-service` - Modify Service
 * `modify-sharing` - Modify Sharing
 * `modify-submission` - Modify Submission
 * `modify-qa-data` - Modify Qa Data
 * `modify-user-permissions` - Modify User Permissions
 * `put-back` - Put Back
 * `redeploy` - Redeploy
 * `register-service` - Register Service
 * `remove` - Remove
 * `replace-form` - Replace Form
 * `share-form-publicly` - Share Form Publicly
 * `share-data-publicly` - Share Data Publicly
 * `unarchive` - Unarchive
 * `unshare-form-publicly` - Unshare Form Publicly
 * `unshare-data-publicly` - Unshare Data Publicly
 * `update` - Update
 * `update-content` - Update Content
 * `update-name` - Update Name
 * `update-settings` - Update Settings
 * `update-qa` - Update Qa
 * `transfer` - Transfer
 */
export type ActionEnum = (typeof ActionEnum)[keyof typeof ActionEnum]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionEnum = {
  'add-media': 'add-media',
  'add-submission': 'add-submission',
  'allow-anonymous-submissions': 'allow-anonymous-submissions',
  archive: 'archive',
  auth: 'auth',
  'clone-permissions': 'clone-permissions',
  'connect-project': 'connect-project',
  create: 'create',
  delete: 'delete',
  'delete-media': 'delete-media',
  'delete-service': 'delete-service',
  'delete-submission': 'delete-submission',
  deploy: 'deploy',
  'disable-sharing': 'disable-sharing',
  'disallow-anonymous-submissions': 'disallow-anonymous-submissions',
  'disconnect-project': 'disconnect-project',
  'enable-sharing': 'enable-sharing',
  export: 'export',
  'in-trash': 'in-trash',
  'modify-imported-fields': 'modify-imported-fields',
  'modify-service': 'modify-service',
  'modify-sharing': 'modify-sharing',
  'modify-submission': 'modify-submission',
  'modify-qa-data': 'modify-qa-data',
  'modify-user-permissions': 'modify-user-permissions',
  'put-back': 'put-back',
  redeploy: 'redeploy',
  'register-service': 'register-service',
  remove: 'remove',
  'replace-form': 'replace-form',
  'share-form-publicly': 'share-form-publicly',
  'share-data-publicly': 'share-data-publicly',
  unarchive: 'unarchive',
  'unshare-form-publicly': 'unshare-form-publicly',
  'unshare-data-publicly': 'unshare-data-publicly',
  update: 'update',
  'update-content': 'update-content',
  'update-name': 'update-name',
  'update-settings': 'update-settings',
  'update-qa': 'update-qa',
  transfer: 'transfer',
} as const
