/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KoboToolbox API
 * Powerful and intuitive data collection tools to make an impact
 * OpenAPI spec version: 2.0.0 (api_v2)
 */
import type { AssetsDataAttachmentsListFormat } from './assetsDataAttachmentsListFormat'

export type AssetsDataAttachmentsListParams = {
  format?: AssetsDataAttachmentsListFormat
  xpath: string
}
