/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KoboToolbox API
 * Powerful and intuitive data collection tools to make an impact
 * OpenAPI spec version: 2.0.0 (api_v2)
 */

export type CreateFilePayloadOneOf = {
  user: string
  asset: string
  description: string
  file_type: string
  content: string
}
