/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KoboToolbox API
 * Powerful and intuitive data collection tools to make an impact
 * OpenAPI spec version: 2.0.0 (api_v2)
 */
import type { ExportSettingResponseExportSettings } from './exportSettingResponseExportSettings'

export interface ExportSettingResponse {
  uid: string
  url: string
  data_url_csv: string
  data_url_xlsx: string
  name: string
  date_modified: string
  export_settings: ExportSettingResponseExportSettings
}
