/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KoboToolbox API
 * Powerful and intuitive data collection tools to make an impact
 * OpenAPI spec version: 2.0.0 (api_v2)
 */
import type { HookLogStatusEnum } from './hookLogStatusEnum'

export interface HookLog {
  readonly url: string
  readonly uid: string
  readonly submission_id: number
  readonly tries: number
  readonly status: HookLogStatusEnum
  status_str: string
  /** @nullable */
  readonly status_code: number | null
  readonly message: string
  readonly date_modified: string
}
