import type { ImportResponseMessagesAuditLogsItem } from './importResponseMessagesAuditLogsItem'
/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KoboToolbox API
 * Powerful and intuitive data collection tools to make an impact
 * OpenAPI spec version: 2.0.0 (api_v2)
 */
import type { ImportResponseMessagesUpdatedItem } from './importResponseMessagesUpdatedItem'

export type ImportResponseMessages = {
  updated?: ImportResponseMessagesUpdatedItem[]
  'audit-logs'?: ImportResponseMessagesAuditLogsItem[]
  error?: string
  error_type?: string
}
