/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KoboToolbox API
 * Powerful and intuitive data collection tools to make an impact
 * OpenAPI spec version: 2.0.0 (api_v2)
 */

export type ProjectViewsExportRetrieveFormat =
  (typeof ProjectViewsExportRetrieveFormat)[keyof typeof ProjectViewsExportRetrieveFormat]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectViewsExportRetrieveFormat = {
  json: 'json',
  xml: 'xml',
} as const
