/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KoboToolbox API
 * Powerful and intuitive data collection tools to make an impact
 * OpenAPI spec version: 2.0.0 (api_v2)
 */

/**
 * serialize allauth SocialAccounts for use with a REST API
 */
export interface SocialAccount {
  /** @maxLength 200 */
  provider: string
  /** @maxLength 191 */
  uid: string
  readonly last_login: string
  readonly date_joined: string
  readonly email: string
  readonly username: string
}
