/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KoboToolbox API
 * Powerful and intuitive data collection tools to make an impact
 * OpenAPI spec version: 2.0.0 (api_v2)
 */

/**
 * * `metered` - Metered
 * `licensed` - Licensed
 */
export type StripeUsageType = (typeof StripeUsageType)[keyof typeof StripeUsageType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StripeUsageType = {
  metered: 'metered',
  licensed: 'licensed',
} as const
