/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KoboToolbox API
 * Powerful and intuitive data collection tools to make an impact
 * OpenAPI spec version: 2.0.0 (api_v2)
 */

export type TranslationServicesRetrieveFormat =
  (typeof TranslationServicesRetrieveFormat)[keyof typeof TranslationServicesRetrieveFormat]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TranslationServicesRetrieveFormat = {
  json: 'json',
  xml: 'xml',
} as const
