import { http, HttpResponse } from 'msw'
import { endpoints } from '#/api.endpoints'
import type { EnvironmentResponse } from '../envStore'

/**
 * Mock API for environment config. Use it in Storybook tests in `parameters.msw.handlers[]`.
 */
const environmentMock = http.get<never, never, EnvironmentResponse>(endpoints.ENVIRONMENT, () =>
  HttpResponse.json(environmentResponse),
)
export default environmentMock

const environmentResponse: EnvironmentResponse = {
  terms_of_service_url: '',
  privacy_policy_url: '',
  source_code_url: 'https://github.com/kobotoolbox/',
  support_email: 'support@kobo.local',
  support_url: 'https://support.kobotoolbox.org/',
  academy_url: 'https://academy.kobotoolbox.org/',
  community_url: 'https://community.kobotoolbox.org/',
  frontend_min_retry_time: 2,
  frontend_max_retry_time: 120,
  use_team_label: true,
  free_tier_display: {
    name: null,
    feature_list: [],
  },
  free_tier_thresholds: {
    storage: null,
    data: null,
    transcription_minutes: null,
    translation_chars: null,
  },
  sector_choices: [
    ['Public Administration', 'Public Administration'],
    ['Arts, Entertainment, and Recreation', 'Arts, Entertainment, and Recreation'],
    ['Educational Services / Higher Education', 'Educational Services / Higher Education'],
    ['Health Services / Public Health', 'Health Services / Public Health'],
    ['Finance and Insurance', 'Finance and Insurance'],
    ['Information / Media', 'Information / Media'],
    ['Economic/Social Development', 'Economic/Social Development'],
    ['Security / Police / Peacekeeping', 'Security / Police / Peacekeeping'],
    ['Disarmament & Demobilization', 'Disarmament & Demobilization'],
    ['Environment', 'Environment'],
    ['Private sector', 'Private sector'],
    ['Humanitarian - Coordination / Information Management', 'Humanitarian - Coordination / Information Management'],
    ['Humanitarian - Multiple Clusters', 'Humanitarian - Multiple Clusters'],
    ['Humanitarian - Camp Management & Coordination', 'Humanitarian - Camp Management & Coordination'],
    ['Humanitarian - Early Recovery', 'Humanitarian - Early Recovery'],
    ['Humanitarian - Education', 'Humanitarian - Education'],
    ['Humanitarian - Emergency Shelter', 'Humanitarian - Emergency Shelter'],
    ['Humanitarian - Emergency Telecoms', 'Humanitarian - Emergency Telecoms'],
    ['Humanitarian - Food Security', 'Humanitarian - Food Security'],
    ['Humanitarian - Health', 'Humanitarian - Health'],
    ['Humanitarian - Logistics', 'Humanitarian - Logistics'],
    ['Humanitarian - Nutrition', 'Humanitarian - Nutrition'],
    ['Humanitarian - Protection', 'Humanitarian - Protection'],
    ['Humanitarian - Sanitation, Water & Hygiene', 'Humanitarian - Sanitation, Water & Hygiene'],
    ['Other', 'Other'],
  ],
  operational_purpose_choices: [['', '']],
  country_choices: [
    ['AFG', 'Afghanistan'],
    ['ALA', 'Åland Islands'],
    ['ALB', 'Albania'],
    ['DZA', 'Algeria'],
    ['ASM', 'American Samoa'],
    ['AND', 'Andorra'],
    ['AGO', 'Angola'],
    ['AIA', 'Anguilla'],
    ['ATA', 'Antarctica'],
    ['ATG', 'Antigua and Barbuda'],
    ['ARG', 'Argentina'],
    ['ARM', 'Armenia'],
    ['ABW', 'Aruba'],
    ['AUS', 'Australia'],
    ['AUT', 'Austria'],
    ['AZE', 'Azerbaijan'],
    ['BHS', 'Bahamas'],
    ['BHR', 'Bahrain'],
    ['BGD', 'Bangladesh'],
    ['BRB', 'Barbados'],
    ['BLR', 'Belarus'],
    ['BEL', 'Belgium'],
    ['BLZ', 'Belize'],
    ['BEN', 'Benin'],
    ['BMU', 'Bermuda'],
    ['BTN', 'Bhutan'],
    ['BOL', 'Bolivia, Plurinational State of'],
    ['BIH', 'Bosnia and Herzegovina'],
    ['BES', 'Bonaire, Sint Eustatius and Saba'],
    ['BWA', 'Botswana'],
    ['BVT', 'Bouvet Island'],
    ['BRA', 'Brazil'],
    ['IOT', 'British Indian Ocean Territory'],
    ['BRN', 'Brunei Darussalam'],
    ['BGR', 'Bulgaria'],
    ['BFA', 'Burkina Faso'],
    ['BDI', 'Burundi'],
    ['KHM', 'Cambodia'],
    ['CMR', 'Cameroon'],
    ['CAN', 'Canada'],
    ['CPV', 'Cape Verde'],
    ['CYM', 'Cayman Islands'],
    ['CAF', 'Central African Republic'],
    ['TCD', 'Chad'],
    ['CHL', 'Chile'],
    ['CHN', 'China'],
    ['CXR', 'Christmas Island'],
    ['CCK', 'Cocos (Keeling) Islands'],
    ['COL', 'Colombia'],
    ['COM', 'Comoros'],
    ['COG', 'Congo'],
    ['COD', 'Congo, The Democratic Republic of the'],
    ['COK', 'Cook Islands'],
    ['CRI', 'Costa Rica'],
    ['CIV', "Côte d'Ivoire"],
    ['HRV', 'Croatia'],
    ['CUB', 'Cuba'],
    ['CUW', 'Curaçao'],
    ['CYP', 'Cyprus'],
    ['CZE', 'Czech Republic'],
    ['DNK', 'Denmark'],
    ['DJI', 'Djibouti'],
    ['DMA', 'Dominica'],
    ['DOM', 'Dominican Republic'],
    ['ECU', 'Ecuador'],
    ['EGY', 'Egypt'],
    ['SLV', 'El Salvador'],
    ['GNQ', 'Equatorial Guinea'],
    ['ERI', 'Eritrea'],
    ['EST', 'Estonia'],
    ['ETH', 'Ethiopia'],
    ['FLK', 'Falkland Islands (Malvinas)'],
    ['FRO', 'Faroe Islands'],
    ['FJI', 'Fiji'],
    ['FIN', 'Finland'],
    ['FRA', 'France'],
    ['GUF', 'French Guiana'],
    ['PYF', 'French Polynesia'],
    ['ATF', 'French Southern Territories'],
    ['GAB', 'Gabon'],
    ['GMB', 'Gambia'],
    ['GEO', 'Georgia'],
    ['DEU', 'Germany'],
    ['GHA', 'Ghana'],
    ['GIB', 'Gibraltar'],
    ['GRC', 'Greece'],
    ['GRL', 'Greenland'],
    ['GRD', 'Grenada'],
    ['GLP', 'Guadeloupe'],
    ['GUM', 'Guam'],
    ['GTM', 'Guatemala'],
    ['GGY', 'Guernsey'],
    ['GIN', 'Guinea'],
    ['GNB', 'Guinea-Bissau'],
    ['GUY', 'Guyana'],
    ['HTI', 'Haiti'],
    ['HMD', 'Heard Island and McDonald Islands'],
    ['VAT', 'Holy See (Vatican City State)'],
    ['HND', 'Honduras'],
    ['HKG', 'Hong Kong'],
    ['HUN', 'Hungary'],
    ['ISL', 'Iceland'],
    ['IND', 'India'],
    ['IDN', 'Indonesia'],
    ['IRN', 'Iran, Islamic Republic of'],
    ['IRQ', 'Iraq'],
    ['IRL', 'Ireland'],
    ['IMN', 'Isle of Man'],
    ['ISR', 'Israel'],
    ['ITA', 'Italy'],
    ['JAM', 'Jamaica'],
    ['JPN', 'Japan'],
    ['JEY', 'Jersey'],
    ['JOR', 'Jordan'],
    ['KAZ', 'Kazakhstan'],
    ['KEN', 'Kenya'],
    ['KIR', 'Kiribati'],
    ['PRK', "Korea, Democratic People's Republic of"],
    ['KOR', 'Korea, Republic of'],
    ['XKX', 'Kosovo'],
    ['KWT', 'Kuwait'],
    ['KGZ', 'Kyrgyzstan'],
    ['LAO', "Lao People's Democratic Republic"],
    ['LVA', 'Latvia'],
    ['LBN', 'Lebanon'],
    ['LSO', 'Lesotho'],
    ['LBR', 'Liberia'],
    ['LBY', 'Libya'],
    ['LIE', 'Liechtenstein'],
    ['LTU', 'Lithuania'],
    ['LUX', 'Luxembourg'],
    ['MAC', 'Macao'],
    ['MKD', 'Macedonia, The Former Yugoslav Republic of'],
    ['MDG', 'Madagascar'],
    ['MWI', 'Malawi'],
    ['MYS', 'Malaysia'],
    ['MDV', 'Maldives'],
    ['MLI', 'Mali'],
    ['MLT', 'Malta'],
    ['MHL', 'Marshall Islands'],
    ['MTQ', 'Martinique'],
    ['MRT', 'Mauritania'],
    ['MUS', 'Mauritius'],
    ['MYT', 'Mayotte'],
    ['MEX', 'Mexico'],
    ['FSM', 'Micronesia, Federated States of'],
    ['MDA', 'Moldova, Republic of'],
    ['MCO', 'Monaco'],
    ['MNG', 'Mongolia'],
    ['MNE', 'Montenegro'],
    ['MSR', 'Montserrat'],
    ['MAR', 'Morocco'],
    ['MOZ', 'Mozambique'],
    ['MMR', 'Myanmar'],
    ['NAM', 'Namibia'],
    ['NRU', 'Nauru'],
    ['NPL', 'Nepal'],
    ['NLD', 'Netherlands'],
    ['ANT', 'Netherlands Antilles'],
    ['NCL', 'New Caledonia'],
    ['NZL', 'New Zealand'],
    ['NIC', 'Nicaragua'],
    ['NER', 'Niger'],
    ['NGA', 'Nigeria'],
    ['NIU', 'Niue'],
    ['NFK', 'Norfolk Island'],
    ['MNP', 'Northern Mariana Islands'],
    ['NOR', 'Norway'],
    ['OMN', 'Oman'],
    ['PAK', 'Pakistan'],
    ['PLW', 'Palau'],
    ['PSE', 'occupied Palestinian territory'],
    ['PAN', 'Panama'],
    ['PNG', 'Papua New Guinea'],
    ['PRY', 'Paraguay'],
    ['PER', 'Peru'],
    ['PHL', 'Philippines'],
    ['PCN', 'Pitcairn'],
    ['POL', 'Poland'],
    ['PRT', 'Portugal'],
    ['PRI', 'Puerto Rico'],
    ['QAT', 'Qatar'],
    ['REU', 'Réunion'],
    ['ROU', 'Romania'],
    ['RUS', 'Russian Federation'],
    ['RWA', 'Rwanda'],
    ['BLM', 'Saint Barthélemy'],
    ['SHN', 'Saint Helena, Ascension and Tristan da Cunha'],
    ['KNA', 'Saint Kitts and Nevis'],
    ['LCA', 'Saint Lucia'],
    ['MAF', 'Saint Martin (French part)'],
    ['SPM', 'Saint Pierre and Miquelon'],
    ['VCT', 'Saint Vincent and the Grenadines'],
    ['WSM', 'Samoa'],
    ['SMR', 'San Marino'],
    ['STP', 'São Tomé and Príncipe'],
    ['SAU', 'Saudi Arabia'],
    ['SEN', 'Senegal'],
    ['SRB', 'Serbia'],
    ['SYC', 'Seychelles'],
    ['SLE', 'Sierra Leone'],
    ['SGP', 'Singapore'],
    ['SXM', 'Sint Maarten (Dutch part)'],
    ['SVK', 'Slovakia'],
    ['SVN', 'Slovenia'],
    ['SLB', 'Solomon Islands'],
    ['SOM', 'Somalia'],
    ['ZAF', 'South Africa'],
    ['SGS', 'South Georgia and the South Sandwich Islands'],
    ['ESP', 'Spain'],
    ['LKA', 'Sri Lanka'],
    ['SSD', 'South Sudan'],
    ['SDN', 'Sudan'],
    ['SUR', 'Suriname'],
    ['SJM', 'Svalbard and Jan Mayen'],
    ['SWZ', 'Swaziland'],
    ['SWE', 'Sweden'],
    ['CHE', 'Switzerland'],
    ['SYR', 'Syrian Arab Republic'],
    ['TWN', 'Taiwan, Province of China'],
    ['TJK', 'Tajikistan'],
    ['TZA', 'Tanzania, United Republic of'],
    ['THA', 'Thailand'],
    ['TLS', 'Timor-Leste'],
    ['TGO', 'Togo'],
    ['TKL', 'Tokelau'],
    ['TON', 'Tonga'],
    ['TTO', 'Trinidad and Tobago'],
    ['TUN', 'Tunisia'],
    ['TUR', 'Turkey'],
    ['TKM', 'Turkmenistan'],
    ['TCA', 'Turks and Caicos Islands'],
    ['TUV', 'Tuvalu'],
    ['UGA', 'Uganda'],
    ['UKR', 'Ukraine'],
    ['ARE', 'United Arab Emirates'],
    ['GBR', 'United Kingdom'],
    ['USA', 'United States'],
    ['UMI', 'United States Minor Outlying Islands'],
    ['URY', 'Uruguay'],
    ['UZB', 'Uzbekistan'],
    ['VUT', 'Vanuatu'],
    ['VEN', 'Venezuela, Bolivarian Republic of'],
    ['VNM', 'Viet Nam'],
    ['VGB', 'Virgin Islands, British'],
    ['VIR', 'Virgin Islands, U.S.'],
    ['WLF', 'Wallis and Futuna'],
    ['ESH', 'Western Sahara'],
    ['YEM', 'Yemen'],
    ['ZMB', 'Zambia'],
    ['ZWE', 'Zimbabwe'],
  ],
  interface_languages: [
    ['am', 'አማርኛ'],
    ['ar', 'العربيّة'],
    ['bn', 'বাংলা'],
    ['cs', 'česky'],
    ['de', 'Deutsch'],
    ['en', 'English'],
    ['es', 'español'],
    ['fa', 'فارسی'],
    ['fr', 'français'],
    ['hi', 'हिंदी'],
    ['hu', 'Magyar'],
    ['id', 'Bahasa Indonesia'],
    ['ja', '日本語'],
    ['km', 'Khmer'],
    ['ku', 'كوردی'],
    ['ln', 'Lingala'],
    ['my', 'မြန်မာဘာသာ'],
    ['ny', 'Nyanja'],
    ['ne', 'नेपाली'],
    ['pl', 'polski'],
    ['pt', 'Português'],
    ['ru', 'Русский'],
    ['sw', 'Kiswahili'],
    ['th', 'ภาษาไทย'],
    ['tr', 'Türkçe'],
    ['uk', 'Українська'],
    ['vi', 'Tiếng Việt'],
    ['yo', 'Yoruba'],
    ['zh-hans', '简体中文'],
  ],
  mfa_localized_help_text:
    '<p>If you cannot access your authenticator app, please enter one of your backup codes instead. If you cannot access those either, then you will need to request assistance by contacting <a href="mailto:support@kobo.local">support@kobo.local</a>.</p>',
  mfa_enabled: true,
  mfa_per_user_availability: false,
  mfa_has_availability_list: false,
  mfa_code_length: 6,
  enable_password_entropy_meter: true,
  enable_custom_password_guidance_text: false,
  custom_password_localized_help_text:
    '<p>The password must be at least 10 characters long and contain 3 or more of the following: uppercase letters, lowercase letters, numbers, and special characters. It cannot be similar to your name, username, or email address.</p>',
  project_metadata_fields: [
    {
      name: 'sector',
      required: false,
      label: 'Sector',
    },
    {
      name: 'country',
      required: false,
      label: 'Country',
    },
    {
      name: 'description',
      required: false,
      label: 'Description',
    },
  ],
  user_metadata_fields: [
    {
      name: 'name',
      required: true,
      label: 'Full name',
    },
    {
      name: 'organization',
      required: false,
      label: 'Organization name',
    },
    {
      name: 'organization_type',
      required: false,
      label: 'Organization type',
    },
    {
      name: 'organization_website',
      required: false,
      label: 'Organization website',
    },
    {
      name: 'sector',
      required: false,
      label: 'Sector',
    },
    {
      name: 'bio',
      required: false,
      label: 'Bio',
    },
    {
      name: 'city',
      required: false,
      label: 'City',
    },
    {
      name: 'country',
      required: false,
      label: 'Country',
    },
    {
      name: 'twitter',
      required: false,
      label: 'Twitter',
    },
    {
      name: 'linkedin',
      required: false,
      label: 'LinkedIn',
    },
    {
      name: 'instagram',
      required: false,
      label: 'Instagram',
    },
    {
      name: 'newsletter_subscription',
      required: false,
      label: 'I want to receive occasional updates about KoboToolbox',
    },
  ],
  social_apps: [],
  asr_mt_features_enabled: false,
  submission_placeholder: '%SUBMISSION%',
  project_history_log_lifespan: 60,
  stripe_public_key: 'pk_test_qliDXQRyVGPWmsYR69tB1NPx00ndTrJfVM',
  terms_of_service__sitewidemessage__exists: false,
  open_rosa_server: 'http://kc.kobo.local',
}
