import { http, HttpResponse, type PathParams } from 'msw'
import { endpoints } from '#/api.endpoints'
import type { PaginatedResponse } from '#/dataInterface'
import type { ListLanguage } from '../components/languages/languagesStore'

/**
 * Mock API for languages list. Use it in Storybook tests in `parameters.msw.handlers[]`.
 */
const languagesMock = http.get<PathParams<'limit' | 'offset' | 'q'>, never, PaginatedResponse<ListLanguage>>(
  endpoints.LANGUAGES_LIST_URL,
  (info) => {
    const searchParams = new URL(info.request.url).searchParams
    if (searchParams.get('limit') === '100' && searchParams.get('offset') === '100') {
      return HttpResponse.json(languagesResponsePage2)
    } else if (searchParams.get('q') === 'swed') {
      return HttpResponse.json(languagesResponseQuerySwed)
    } else {
      return HttpResponse.json(languagesResponsePage1)
    }
  },
)
export default languagesMock

/** This is being returned for `q=swed` */
const languagesResponseQuerySwed: PaginatedResponse<ListLanguage> = {
  count: 1,
  next: null,
  previous: null,
  results: [
    {
      name: 'Swedish',
      code: 'sv',
      featured: false,
      transcription_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      translation_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      url: '/api/v2/languages/sv/',
    },
  ],
}

// Note: We are only supporting 2 pages of results with this mock data. The first page is 100 languages, and the second
// page is 50 items.

// I got these languages from the production API with these changes:
// 1. first page - set `count` to `150` (original set of languages is around 6k)
// 2. second page - mimic last page of results = set `count` to `150`, kept only 50 results, changed `next` to `null`

const languagesResponsePage1: PaginatedResponse<ListLanguage> = {
  count: 150,
  next: '/api/v2/languages/?limit=100&offset=100',
  previous: null,
  results: [
    {
      name: 'Arabic',
      code: 'ar',
      featured: true,
      transcription_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      translation_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      url: '/api/v2/languages/ar/',
    },
    {
      name: 'Bangla',
      code: 'bn',
      featured: true,
      transcription_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      translation_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      url: '/api/v2/languages/bn/',
    },
    {
      name: 'Dari',
      code: 'prs',
      featured: true,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/prs/',
    },
    {
      name: 'English',
      code: 'en',
      featured: true,
      transcription_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      translation_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      url: '/api/v2/languages/en/',
    },
    {
      name: 'French',
      code: 'fr',
      featured: true,
      transcription_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      translation_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      url: '/api/v2/languages/fr/',
    },
    {
      name: 'Spanish',
      code: 'es',
      featured: true,
      transcription_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      translation_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      url: '/api/v2/languages/es/',
    },
    {
      name: 'Ukrainian',
      code: 'uk',
      featured: true,
      transcription_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      translation_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      url: '/api/v2/languages/uk/',
    },
    {
      name: 'Urdu',
      code: 'ur',
      featured: true,
      transcription_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      translation_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      url: '/api/v2/languages/ur/',
    },
    {
      name: 'Aari',
      code: 'aiw',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aiw/',
    },
    {
      name: 'Aasáx',
      code: 'aas',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aas/',
    },
    {
      name: 'Abadi',
      code: 'kbt',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/kbt/',
    },
    {
      name: 'Abaga',
      code: 'abg',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/abg/',
    },
    {
      name: 'Abai Sungai',
      code: 'abf',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/abf/',
    },
    {
      name: 'Abanyom',
      code: 'abm',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/abm/',
    },
    {
      name: 'Abar',
      code: 'mij',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/mij/',
    },
    {
      name: 'Abau',
      code: 'aau',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aau/',
    },
    {
      name: 'Abaza',
      code: 'abq',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/abq/',
    },
    {
      name: 'Abé',
      code: 'aba',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aba/',
    },
    {
      name: 'Abellen Ayta',
      code: 'abp',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/abp/',
    },
    {
      name: 'Abidji',
      code: 'abi',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/abi/',
    },
    {
      name: 'Abinomn',
      code: 'bsa',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/bsa/',
    },
    {
      name: 'Abkhazian',
      code: 'ab',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ab/',
    },
    {
      name: 'Abom',
      code: 'aob',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aob/',
    },
    {
      name: 'Abon',
      code: 'abo',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/abo/',
    },
    {
      name: 'Abron',
      code: 'abr',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/abr/',
    },
    {
      name: 'Abu',
      code: 'ado',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ado/',
    },
    {
      name: 'Abua',
      code: 'abn',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/abn/',
    },
    {
      name: "Abu' Arapesh",
      code: 'aah',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aah/',
    },
    {
      name: 'Abui',
      code: 'abz',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/abz/',
    },
    {
      name: 'Abun',
      code: 'kgr',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/kgr/',
    },
    {
      name: 'Abure',
      code: 'abu',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/abu/',
    },
    {
      name: 'Abureni',
      code: 'mgj',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/mgj/',
    },
    {
      name: "Acatepec Me'phaa",
      code: 'tpx',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/tpx/',
    },
    {
      name: 'Achagua',
      code: 'aca',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aca/',
    },
    {
      name: 'Achang',
      code: 'acn',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/acn/',
    },
    {
      name: 'Ache',
      code: 'yif',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/yif/',
    },
    {
      name: 'Aché',
      code: 'guq',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/guq/',
    },
    {
      name: 'Acheron',
      code: 'acz',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/acz/',
    },
    {
      name: 'Achi',
      code: 'acr',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/acr/',
    },
    {
      name: 'Achinese',
      code: 'ace',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ace/',
    },
    {
      name: 'Achterhoeks',
      code: 'act',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/act/',
    },
    {
      name: 'Achuar-Shiwiar',
      code: 'acu',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/acu/',
    },
    {
      name: 'Achumawi',
      code: 'acv',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/acv/',
    },
    {
      name: 'Acoli',
      code: 'ach',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ach/',
    },
    {
      name: 'Adamawa Fulfulde',
      code: 'fub',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/fub/',
    },
    {
      name: 'Adang',
      code: 'adn',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/adn/',
    },
    {
      name: 'Adangbe',
      code: 'adq',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/adq/',
    },
    {
      name: 'Adangme',
      code: 'ada',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ada/',
    },
    {
      name: 'Adara',
      code: 'kad',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/kad/',
    },
    {
      name: 'Adasen',
      code: 'tiu',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/tiu/',
    },
    {
      name: 'Adele',
      code: 'ade',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ade/',
    },
    {
      name: 'Adhola',
      code: 'adh',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/adh/',
    },
    {
      name: 'Adi',
      code: 'adi',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/adi/',
    },
    {
      name: 'Adilabad Gondi',
      code: 'wsg',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/wsg/',
    },
    {
      name: 'Adioukrou',
      code: 'adj',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/adj/',
    },
    {
      name: 'Adivasi Oriya',
      code: 'ort',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ort/',
    },
    {
      name: 'Adiwasi Garasia',
      code: 'gas',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/gas/',
    },
    {
      name: 'Adnyamathanha',
      code: 'adt',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/adt/',
    },
    {
      name: 'Adonara',
      code: 'adr',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/adr/',
    },
    {
      name: 'Aduge',
      code: 'adu',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/adu/',
    },
    {
      name: 'Adyghe',
      code: 'ady',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ady/',
    },
    {
      name: 'Adzera',
      code: 'adz',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/adz/',
    },
    {
      name: 'Aeka',
      code: 'aez',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aez/',
    },
    {
      name: 'Aekyom',
      code: 'awi',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/awi/',
    },
    {
      name: 'Aer',
      code: 'aeq',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aeq/',
    },
    {
      name: 'Afade',
      code: 'aal',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aal/',
    },
    {
      name: 'Afar',
      code: 'aa',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aa/',
    },
    {
      name: 'Afitti',
      code: 'aft',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aft/',
    },
    {
      name: 'Afrikaans',
      code: 'af',
      featured: false,
      transcription_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      translation_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      url: '/api/v2/languages/af/',
    },
    {
      name: 'Afro-Seminole Creole',
      code: 'afs',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/afs/',
    },
    {
      name: 'Agarabi',
      code: 'agd',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/agd/',
    },
    {
      name: 'Agariya',
      code: 'agi',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/agi/',
    },
    {
      name: 'Agatu',
      code: 'agc',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/agc/',
    },
    {
      name: 'Aghem',
      code: 'agq',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/agq/',
    },
    {
      name: 'Aghu',
      code: 'ahh',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ahh/',
    },
    {
      name: 'Aghul',
      code: 'agx',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/agx/',
    },
    {
      name: 'Agi',
      code: 'aif',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aif/',
    },
    {
      name: 'Agob',
      code: 'kit',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/kit/',
    },
    {
      name: 'Agoi',
      code: 'ibm',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ibm/',
    },
    {
      name: 'Aguacateco',
      code: 'agu',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/agu/',
    },
    {
      name: 'Aguaruna',
      code: 'agr',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/agr/',
    },
    {
      name: 'Aguna',
      code: 'aug',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aug/',
    },
    {
      name: 'Agusan Manobo',
      code: 'msm',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/msm/',
    },
    {
      name: 'Agutaynen',
      code: 'agn',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/agn/',
    },
    {
      name: 'Agwagwune',
      code: 'yay',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/yay/',
    },
    {
      name: 'Àhàn',
      code: 'ahn',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ahn/',
    },
    {
      name: 'Ahanta',
      code: 'aha',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aha/',
    },
    {
      name: 'Aheri Gondi',
      code: 'esg',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/esg/',
    },
    {
      name: 'Aheu',
      code: 'thm',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/thm/',
    },
    {
      name: 'Ahirani',
      code: 'ahr',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ahr/',
    },
    {
      name: 'Ahtena',
      code: 'aht',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aht/',
    },
    {
      name: 'Ahwai',
      code: 'nfd',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/nfd/',
    },
    {
      name: 'Ai-Cham',
      code: 'aih',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aih/',
    },
    {
      name: 'Aighon',
      code: 'aix',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aix/',
    },
    {
      name: 'Aikanã',
      code: 'tba',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/tba/',
    },
    {
      name: 'Aiklep',
      code: 'mwg',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/mwg/',
    },
    {
      name: 'Aimaq',
      code: 'aiq',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aiq/',
    },
    {
      name: 'Aimele',
      code: 'ail',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ail/',
    },
    {
      name: 'Aimol',
      code: 'aim',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aim/',
    },
    {
      name: 'Ainbai',
      code: 'aic',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aic/',
    },
  ],
}

const languagesResponsePage2: PaginatedResponse<ListLanguage> = {
  count: 150,
  next: null,
  previous: '/api/v2/languages/?limit=100',
  results: [
    {
      name: 'Ainu',
      code: 'ain',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ain/',
    },
    {
      name: 'Ainu (China)',
      code: 'aib',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aib/',
    },
    {
      name: 'Aiome',
      code: 'aki',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aki/',
    },
    {
      name: 'Airoran',
      code: 'air',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/air/',
    },
    {
      name: 'Aiton',
      code: 'aio',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aio/',
    },
    {
      name: 'Aja (Benin)',
      code: 'ajg',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ajg/',
    },
    {
      name: 'Aja (South Sudan)',
      code: 'aja',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aja/',
    },
    {
      name: 'Ajië',
      code: 'aji',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aji/',
    },
    {
      name: 'Ajumbu',
      code: 'muc',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/muc/',
    },
    {
      name: 'Ajyíninka Apurucayali',
      code: 'cpc',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/cpc/',
    },
    {
      name: 'Ak',
      code: 'akq',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/akq/',
    },
    {
      name: 'Aka',
      code: 'soh',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/soh/',
    },
    {
      name: 'Akan',
      code: 'ak',
      featured: false,
      transcription_services: [],
      translation_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      url: '/api/v2/languages/ak/',
    },
    {
      name: 'Akaselem',
      code: 'aks',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aks/',
    },
    {
      name: 'Akawaio',
      code: 'ake',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ake/',
    },
    {
      name: 'Ake',
      code: 'aik',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aik/',
    },
    {
      name: 'Akebu',
      code: 'keu',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/keu/',
    },
    {
      name: 'Akei',
      code: 'tsr',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/tsr/',
    },
    {
      name: 'Akeu',
      code: 'aeu',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aeu/',
    },
    {
      name: 'Akha',
      code: 'ahk',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ahk/',
    },
    {
      name: 'Akhvakh',
      code: 'akv',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/akv/',
    },
    {
      name: 'Aklanon',
      code: 'akl',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/akl/',
    },
    {
      name: 'Akolet',
      code: 'akt',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/akt/',
    },
    {
      name: 'Akoose',
      code: 'bss',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/bss/',
    },
    {
      name: 'Akoye',
      code: 'miw',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/miw/',
    },
    {
      name: 'Akpa',
      code: 'akf',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/akf/',
    },
    {
      name: 'Akpes',
      code: 'ibe',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ibe/',
    },
    {
      name: 'Akrukay',
      code: 'afi',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/afi/',
    },
    {
      name: 'Akukem',
      code: 'spm',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/spm/',
    },
    {
      name: 'Akuku',
      code: 'ayk',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ayk/',
    },
    {
      name: 'Akum',
      code: 'aku',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aku/',
    },
    {
      name: 'Akuntsu',
      code: 'aqz',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/aqz/',
    },
    {
      name: 'Akurio',
      code: 'ako',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ako/',
    },
    {
      name: 'Akwa',
      code: 'akw',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/akw/',
    },
    {
      name: 'Akyaung Ari Naga',
      code: 'nqy',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/nqy/',
    },
    {
      name: 'Alaba-K’abeena',
      code: 'alw',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/alw/',
    },
    {
      name: 'Alabama',
      code: 'akz',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/akz/',
    },
    {
      name: 'Alabat Island Agta',
      code: 'dul',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/dul/',
    },
    {
      name: 'Alacatlatzala Mixtec',
      code: 'mim',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/mim/',
    },
    {
      name: 'Alago',
      code: 'ala',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ala/',
    },
    {
      name: 'Alagwa',
      code: 'wbj',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/wbj/',
    },
    {
      name: 'Alak',
      code: 'alk',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/alk/',
    },
    {
      name: 'Alamblak',
      code: 'amp',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/amp/',
    },
    {
      name: 'Alangan',
      code: 'alj',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/alj/',
    },
    {
      name: 'Alawa',
      code: 'alh',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/alh/',
    },
    {
      name: 'Albanian',
      code: 'sq',
      featured: false,
      transcription_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      translation_services: [
        {
          name: 'Goog',
          code: 'goog',
        },
      ],
      url: '/api/v2/languages/sq/',
    },
    {
      name: 'Alcozauca Mixtec',
      code: 'xta',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/xta/',
    },
    {
      name: 'Alege',
      code: 'alf',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/alf/',
    },
    {
      name: 'Alekano',
      code: 'gah',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/gah/',
    },
    {
      name: 'Aleut',
      code: 'ale',
      featured: false,
      transcription_services: [],
      translation_services: [],
      url: '/api/v2/languages/ale/',
    },
  ],
}
