# Generated by Django 4.2.24 on 2025-10-15 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import kpi.models.abstract_models


class Migration(migrations.Migration):

    replaces = [
        ('accounts_mfa', '0001_initial'),
        ('accounts_mfa', '0002_add_mfa_available_to_user_model'),
        ('accounts_mfa', '0003_rename_kobo_mfa_method_model'),
        ('accounts_mfa', '0004_alter_mfamethod_date_created_and_more'),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MfaAvailableToUser',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'per-user availability',
                'verbose_name_plural': 'per-user availabilities',
            },
        ),
        migrations.CreateModel(
            name='MfaMethod',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'date_created',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'date_modified',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                ('date_disabled', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'MFA Method',
                'verbose_name_plural': 'MFA Methods',
            },
        ),
    ]
