# Generated by Django 4.2.11 on 2024-07-24 07:16

from django.db import migrations, models
import kpi.models.abstract_models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa', '0003_rename_kobo_mfa_method_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfamethod',
            name='date_created',
            field=models.DateTimeField(default=kpi.models.abstract_models._get_default_datetime),
        ),
        migrations.AlterField(
            model_name='mfamethod',
            name='date_modified',
            field=models.DateTimeField(default=kpi.models.abstract_models._get_default_datetime),
        ),
    ]
