# Generated by Django 4.2.24 on 2026-01-09 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_mfa', '0006_add_mfa_methods_wrapper_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mfamethod',
            options={
                'verbose_name': 'Trench MFA Method',
                'verbose_name_plural': 'Trench MFA Methods',
            },
        ),
        migrations.AlterField(
            model_name='mfamethodswrapper',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mfa_methods_wrapper',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
