# Generated by Django 4.2.28 on 2026-04-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_mfa', '0007_alter_mfamethod_options_alter_mfamethodswrapper_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mfamethodswrapper',
            options={
                'verbose_name': 'MFA Registration',
                'verbose_name_plural': 'MFA Registrations',
            },
        ),
        migrations.AlterField(
            model_name='mfamethodswrapper',
            name='date_disabled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MfaAvailableToUser',
        ),
    ]
