# Generated by Django 4.2.28 on 2026-03-04 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kpi.fields.kpi_uid
import kpi.models.abstract_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kobo_scim', '0002_link_social_app_to_identityprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScimGroup',
            fields=[
                (
                    'date_created',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'date_modified',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'id',
                    kpi.fields.kpi_uid.KpiUidField(
                        _null=False, primary_key=True, uid_prefix='scg'
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Display name for the SCIM group',
                        max_length=255,
                        verbose_name='Name',
                    ),
                ),
                (
                    'scim_external_id',
                    models.CharField(
                        blank=True,
                        help_text='The external ID provided by the Identity Provider',
                        max_length=255,
                        verbose_name='SCIM External ID',
                    ),
                ),
                (
                    'idp',
                    models.ForeignKey(
                        help_text='The Identity Provider this group belongs to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='scim_groups',
                        to='kobo_scim.identityprovider',
                    ),
                ),
                (
                    'members',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Users belonging to this SCIM group',
                        related_name='scim_groups',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'SCIM Group',
                'verbose_name_plural': 'SCIM Groups',
                'unique_together': {('idp', 'name')},
            },
        ),
    ]
