/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KoboToolbox API
 * Powerful and intuitive data collection tools to make an impact
 * OpenAPI spec version: 2.0.0 (api_v2)
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { AssetsExportsListParams } from './models/assetsExportsListParams'

import type { ErrorDetail } from './models/errorDetail'

import type { ErrorObject } from './models/errorObject'

import type { ExportCreatePayload } from './models/exportCreatePayload'

import { faker } from '@faker-js/faker'

import { http, HttpResponse, delay } from 'msw'

import type { ExportResponse } from './models/exportResponse'

import type { PaginatedExportResponseList } from './models/paginatedExportResponseList'

import { koboCustomOrvalMutationOptions } from '../orval.mutationOptions'

/**
 * ## List of export tasks endpoints

Lists the export tasks accessible to requesting user, for anonymous access
nothing is returned.

<sup>*</sup> _Required permissions: `view_submissions` (View submissions)_

Otherwise, the search can be more specific:

**Exports matching `uid`s:**
```shell
curl -X GET https://kf.kobotoolbox.org/api/v2/assets/{asset_uid}/exports/?q=uid__in:ehZUwRctkhp9QfJgvEWGg OR uid__in:ehZUwRctkhp9QfJgvDnjud
```

 */
export type assetsExportsListResponse200 = {
  data: PaginatedExportResponseList
  status: 200
}

export type assetsExportsListResponse403 = {
  data: ErrorDetail
  status: 403
}

export type assetsExportsListResponse404 = {
  data: ErrorObject
  status: 404
}

export type assetsExportsListResponseComposite =
  | assetsExportsListResponse200
  | assetsExportsListResponse403
  | assetsExportsListResponse404

export type assetsExportsListResponse = assetsExportsListResponseComposite & {
  headers: Headers
}

export const getAssetsExportsListUrl = (parentLookupAsset: string, params?: AssetsExportsListParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v2/assets/${parentLookupAsset}/exports/?${stringifiedParams}`
    : `/api/v2/assets/${parentLookupAsset}/exports/`
}

export const assetsExportsList = async (
  parentLookupAsset: string,
  params?: AssetsExportsListParams,
  options?: RequestInit,
): Promise<assetsExportsListResponse> => {
  const res = await fetch(getAssetsExportsListUrl(parentLookupAsset, params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: assetsExportsListResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as assetsExportsListResponse
}

export const getAssetsExportsListQueryKey = (parentLookupAsset: string, params?: AssetsExportsListParams) => {
  return ['api', 'v2', 'assets', parentLookupAsset, 'exports', ...(params ? [params] : [])] as const
}

export const getAssetsExportsListQueryOptions = <
  TData = Awaited<ReturnType<typeof assetsExportsList>>,
  TError = ErrorDetail | ErrorObject,
>(
  parentLookupAsset: string,
  params?: AssetsExportsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsExportsList>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAssetsExportsListQueryKey(parentLookupAsset, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof assetsExportsList>>> = ({ signal }) =>
    assetsExportsList(parentLookupAsset, params, { signal, ...fetchOptions })

  return { queryKey, queryFn, enabled: !!parentLookupAsset, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof assetsExportsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssetsExportsListQueryResult = NonNullable<Awaited<ReturnType<typeof assetsExportsList>>>
export type AssetsExportsListQueryError = ErrorDetail | ErrorObject

export function useAssetsExportsList<
  TData = Awaited<ReturnType<typeof assetsExportsList>>,
  TError = ErrorDetail | ErrorObject,
>(
  parentLookupAsset: string,
  params: undefined | AssetsExportsListParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsExportsList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetsExportsList>>,
          TError,
          Awaited<ReturnType<typeof assetsExportsList>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetsExportsList<
  TData = Awaited<ReturnType<typeof assetsExportsList>>,
  TError = ErrorDetail | ErrorObject,
>(
  parentLookupAsset: string,
  params?: AssetsExportsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsExportsList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetsExportsList>>,
          TError,
          Awaited<ReturnType<typeof assetsExportsList>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetsExportsList<
  TData = Awaited<ReturnType<typeof assetsExportsList>>,
  TError = ErrorDetail | ErrorObject,
>(
  parentLookupAsset: string,
  params?: AssetsExportsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsExportsList>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAssetsExportsList<
  TData = Awaited<ReturnType<typeof assetsExportsList>>,
  TError = ErrorDetail | ErrorObject,
>(
  parentLookupAsset: string,
  params?: AssetsExportsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsExportsList>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAssetsExportsListQueryOptions(parentLookupAsset, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * ## Creates an export task

Where:
* `fields_from_all_versions` (required) is a boolean to specify whether fields from all form versions will be included in the export.
    * `group_sep` (required) is a value used to separate the names in a hierarchy of groups. Valid inputs include:
        * Non-empty value
    * `hierarchy_in_labels` (required) is a boolean to specify whether the group hierarchy will be displayed in labels
    * `lang` (required) is a string that can be set to:
        * `_xml` to have XML values and headers, or
        * Any translation specified in the form such as `English (en)`, etc.
    * `multiple_select` (required) is a value to specify the display of `multiple_select-type` responses. Valid inputs include:
        * `both`,
        * `summary`, or
        * `details`
    * "`type`" (required) specifies the export format. Valid export formats include:
        * `csv`,
        * `geojson`,
        * `spss_labels`, or
        * `xls`
    * `fields` (optional) is an array of column names to be included in the export (including their group hierarchy). Valid inputs include:
        * An array containing any string value that matches the XML column name
        * An empty array which will result in all columns being included
        * If `fields` is not included in the `export_settings`, all columns will be included in the export
    * `flatten` (optional) is a boolean value and only relevant when exporting to "geojson" format.
    * `xls_types_as_text` (optional) is a boolean value that defaults to `false` and only affects `xls` export types.
    * `include_media_url` (optional) is a boolean value that defaults to `false` and only affects `xls` and "csv" export types. This will include an additional column for media-type questions (`question_name_URL`) with the URL link to the hosted file.
    * `submission_ids` (optional) is an array of submission ids that will filter exported submissions to only the specified array of ids. Valid inputs include:
        * An array containing integer values
        * An empty array (no filtering)
    * `query` (optional) is a JSON object containing a Mongo filter query for filtering exported submissions. Valid inputs include:
        * A JSON object containing a valid Mongo query
        * An empty JSON object (no filtering)

 */
export type assetsExportsCreateResponse201 = {
  data: ExportResponse
  status: 201
}

export type assetsExportsCreateResponse400 = {
  data: ErrorObject
  status: 400
}

export type assetsExportsCreateResponse403 = {
  data: ErrorDetail
  status: 403
}

export type assetsExportsCreateResponseComposite =
  | assetsExportsCreateResponse201
  | assetsExportsCreateResponse400
  | assetsExportsCreateResponse403

export type assetsExportsCreateResponse = assetsExportsCreateResponseComposite & {
  headers: Headers
}

export const getAssetsExportsCreateUrl = (parentLookupAsset: string) => {
  return `/api/v2/assets/${parentLookupAsset}/exports/`
}

export const assetsExportsCreate = async (
  parentLookupAsset: string,
  exportCreatePayload: ExportCreatePayload,
  options?: RequestInit,
): Promise<assetsExportsCreateResponse> => {
  const res = await fetch(getAssetsExportsCreateUrl(parentLookupAsset), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(exportCreatePayload),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: assetsExportsCreateResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as assetsExportsCreateResponse
}

export const useAssetsExportsCreateMutationOptions = <
  TError = ErrorObject | ErrorDetail,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsExportsCreate>>,
    TError,
    { parentLookupAsset: string; data: ExportCreatePayload },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof assetsExportsCreate>>,
  TError,
  { parentLookupAsset: string; data: ExportCreatePayload },
  TContext
> => {
  const mutationKey = ['assetsExportsCreate']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assetsExportsCreate>>,
    { parentLookupAsset: string; data: ExportCreatePayload }
  > = (props) => {
    const { parentLookupAsset, data } = props ?? {}

    return assetsExportsCreate(parentLookupAsset, data, fetchOptions)
  }

  const customOptions = koboCustomOrvalMutationOptions({ ...mutationOptions, mutationFn })

  return customOptions
}

export type AssetsExportsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof assetsExportsCreate>>>
export type AssetsExportsCreateMutationBody = ExportCreatePayload
export type AssetsExportsCreateMutationError = ErrorObject | ErrorDetail

export const useAssetsExportsCreate = <TError = ErrorObject | ErrorDetail, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof assetsExportsCreate>>,
      TError,
      { parentLookupAsset: string; data: ExportCreatePayload },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof assetsExportsCreate>>,
  TError,
  { parentLookupAsset: string; data: ExportCreatePayload },
  TContext
> => {
  const mutationOptions = useAssetsExportsCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * ## Retrieves current export task

 */
export type assetsExportsRetrieveResponse200 = {
  data: ExportResponse
  status: 200
}

export type assetsExportsRetrieveResponse403 = {
  data: ErrorDetail
  status: 403
}

export type assetsExportsRetrieveResponse404 = {
  data: ErrorObject
  status: 404
}

export type assetsExportsRetrieveResponseComposite =
  | assetsExportsRetrieveResponse200
  | assetsExportsRetrieveResponse403
  | assetsExportsRetrieveResponse404

export type assetsExportsRetrieveResponse = assetsExportsRetrieveResponseComposite & {
  headers: Headers
}

export const getAssetsExportsRetrieveUrl = (parentLookupAsset: string, uid: string) => {
  return `/api/v2/assets/${parentLookupAsset}/exports/${uid}/`
}

export const assetsExportsRetrieve = async (
  parentLookupAsset: string,
  uid: string,
  options?: RequestInit,
): Promise<assetsExportsRetrieveResponse> => {
  const res = await fetch(getAssetsExportsRetrieveUrl(parentLookupAsset, uid), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: assetsExportsRetrieveResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as assetsExportsRetrieveResponse
}

export const getAssetsExportsRetrieveQueryKey = (parentLookupAsset: string, uid: string) => {
  return ['api', 'v2', 'assets', parentLookupAsset, 'exports', uid] as const
}

export const getAssetsExportsRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof assetsExportsRetrieve>>,
  TError = ErrorDetail | ErrorObject,
>(
  parentLookupAsset: string,
  uid: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsExportsRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAssetsExportsRetrieveQueryKey(parentLookupAsset, uid)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof assetsExportsRetrieve>>> = ({ signal }) =>
    assetsExportsRetrieve(parentLookupAsset, uid, { signal, ...fetchOptions })

  return { queryKey, queryFn, enabled: !!(parentLookupAsset && uid), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof assetsExportsRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssetsExportsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof assetsExportsRetrieve>>>
export type AssetsExportsRetrieveQueryError = ErrorDetail | ErrorObject

export function useAssetsExportsRetrieve<
  TData = Awaited<ReturnType<typeof assetsExportsRetrieve>>,
  TError = ErrorDetail | ErrorObject,
>(
  parentLookupAsset: string,
  uid: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsExportsRetrieve>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetsExportsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof assetsExportsRetrieve>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetsExportsRetrieve<
  TData = Awaited<ReturnType<typeof assetsExportsRetrieve>>,
  TError = ErrorDetail | ErrorObject,
>(
  parentLookupAsset: string,
  uid: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsExportsRetrieve>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetsExportsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof assetsExportsRetrieve>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetsExportsRetrieve<
  TData = Awaited<ReturnType<typeof assetsExportsRetrieve>>,
  TError = ErrorDetail | ErrorObject,
>(
  parentLookupAsset: string,
  uid: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsExportsRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAssetsExportsRetrieve<
  TData = Awaited<ReturnType<typeof assetsExportsRetrieve>>,
  TError = ErrorDetail | ErrorObject,
>(
  parentLookupAsset: string,
  uid: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsExportsRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAssetsExportsRetrieveQueryOptions(parentLookupAsset, uid, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * ## Deletes current export task

 */
export type assetsExportsDestroyResponse204 = {
  data: void
  status: 204
}

export type assetsExportsDestroyResponse403 = {
  data: ErrorDetail
  status: 403
}

export type assetsExportsDestroyResponse404 = {
  data: ErrorObject
  status: 404
}

export type assetsExportsDestroyResponseComposite =
  | assetsExportsDestroyResponse204
  | assetsExportsDestroyResponse403
  | assetsExportsDestroyResponse404

export type assetsExportsDestroyResponse = assetsExportsDestroyResponseComposite & {
  headers: Headers
}

export const getAssetsExportsDestroyUrl = (parentLookupAsset: string, uid: string) => {
  return `/api/v2/assets/${parentLookupAsset}/exports/${uid}/`
}

export const assetsExportsDestroy = async (
  parentLookupAsset: string,
  uid: string,
  options?: RequestInit,
): Promise<assetsExportsDestroyResponse> => {
  const res = await fetch(getAssetsExportsDestroyUrl(parentLookupAsset, uid), {
    ...options,
    method: 'DELETE',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: assetsExportsDestroyResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as assetsExportsDestroyResponse
}

export const useAssetsExportsDestroyMutationOptions = <
  TError = ErrorDetail | ErrorObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsExportsDestroy>>,
    TError,
    { parentLookupAsset: string; uid: string },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof assetsExportsDestroy>>,
  TError,
  { parentLookupAsset: string; uid: string },
  TContext
> => {
  const mutationKey = ['assetsExportsDestroy']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assetsExportsDestroy>>,
    { parentLookupAsset: string; uid: string }
  > = (props) => {
    const { parentLookupAsset, uid } = props ?? {}

    return assetsExportsDestroy(parentLookupAsset, uid, fetchOptions)
  }

  const customOptions = koboCustomOrvalMutationOptions({ ...mutationOptions, mutationFn })

  return customOptions
}

export type AssetsExportsDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof assetsExportsDestroy>>>

export type AssetsExportsDestroyMutationError = ErrorDetail | ErrorObject

export const useAssetsExportsDestroy = <TError = ErrorDetail | ErrorObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof assetsExportsDestroy>>,
      TError,
      { parentLookupAsset: string; uid: string },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof assetsExportsDestroy>>,
  TError,
  { parentLookupAsset: string; uid: string },
  TContext
> => {
  const mutationOptions = useAssetsExportsDestroyMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}

export const getApiV2AssetsExportsListResponseMock = (
  overrideResponse: Partial<PaginatedExportResponseList> = {},
): PaginatedExportResponseList => ({
  count: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  next: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
  previous: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
  results: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    url: faker.internet.url(),
    status: faker.string.alpha({ length: { min: 10, max: 20 } }),
    message: {},
    uid: faker.string.alpha({ length: { min: 10, max: 20 } }),
    date_created: `${faker.date.past().toISOString().split('.')[0]}Z`,
    last_submission_time: `${faker.date.past().toISOString().split('.')[0]}Z`,
    result: faker.internet.url(),
    data: {
      lang: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
      name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
      type: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
      fields: faker.helpers.arrayElement([
        Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
          faker.string.alpha({ length: { min: 10, max: 20 } }),
        ),
        undefined,
      ]),
      source: faker.helpers.arrayElement([faker.internet.url(), undefined]),
      group_sep: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
      multiple_select: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
      include_media_url: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
      hierarchy_in_labels: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
      processing_time_seconds: faker.helpers.arrayElement([
        faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
        undefined,
      ]),
      fields_from_all_versions: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    },
  })),
  ...overrideResponse,
})

export const getApiV2AssetsExportsCreateResponseMock = (
  overrideResponse: Partial<ExportResponse> = {},
): ExportResponse => ({
  url: faker.internet.url(),
  status: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: {},
  uid: faker.string.alpha({ length: { min: 10, max: 20 } }),
  date_created: `${faker.date.past().toISOString().split('.')[0]}Z`,
  last_submission_time: `${faker.date.past().toISOString().split('.')[0]}Z`,
  result: faker.internet.url(),
  data: {
    lang: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    type: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    fields: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
        faker.string.alpha({ length: { min: 10, max: 20 } }),
      ),
      undefined,
    ]),
    source: faker.helpers.arrayElement([faker.internet.url(), undefined]),
    group_sep: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    multiple_select: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    include_media_url: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    hierarchy_in_labels: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    processing_time_seconds: faker.helpers.arrayElement([
      faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
      undefined,
    ]),
    fields_from_all_versions: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  },
  ...overrideResponse,
})

export const getApiV2AssetsExportsRetrieveResponseMock = (
  overrideResponse: Partial<ExportResponse> = {},
): ExportResponse => ({
  url: faker.internet.url(),
  status: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: {},
  uid: faker.string.alpha({ length: { min: 10, max: 20 } }),
  date_created: `${faker.date.past().toISOString().split('.')[0]}Z`,
  last_submission_time: `${faker.date.past().toISOString().split('.')[0]}Z`,
  result: faker.internet.url(),
  data: {
    lang: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    type: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    fields: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
        faker.string.alpha({ length: { min: 10, max: 20 } }),
      ),
      undefined,
    ]),
    source: faker.helpers.arrayElement([faker.internet.url(), undefined]),
    group_sep: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    multiple_select: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    include_media_url: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    hierarchy_in_labels: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    processing_time_seconds: faker.helpers.arrayElement([
      faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
      undefined,
    ]),
    fields_from_all_versions: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  },
  ...overrideResponse,
})

export const getApiV2AssetsExportsListMockHandler = (
  overrideResponse?:
    | PaginatedExportResponseList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PaginatedExportResponseList> | PaginatedExportResponseList),
) => {
  return http.get('*/api/v2/assets/:parentLookupAsset/exports/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getApiV2AssetsExportsListResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getApiV2AssetsExportsCreateMockHandler = (
  overrideResponse?:
    | ExportResponse
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ExportResponse> | ExportResponse),
) => {
  return http.post('*/api/v2/assets/:parentLookupAsset/exports/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getApiV2AssetsExportsCreateResponseMock(),
      ),
      { status: 201, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getApiV2AssetsExportsRetrieveMockHandler = (
  overrideResponse?:
    | ExportResponse
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ExportResponse> | ExportResponse),
) => {
  return http.get('*/api/v2/assets/:parentLookupAsset/exports/:uid/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getApiV2AssetsExportsRetrieveResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getApiV2AssetsExportsDestroyMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
) => {
  return http.delete('*/api/v2/assets/:parentLookupAsset/exports/:uid/', async (info) => {
    await delay(1000)
    if (typeof overrideResponse === 'function') {
      await overrideResponse(info)
    }
    return new HttpResponse(null, { status: 204 })
  })
}
export const getExportsMock = () => [
  getApiV2AssetsExportsListMockHandler(),
  getApiV2AssetsExportsCreateMockHandler(),
  getApiV2AssetsExportsRetrieveMockHandler(),
  getApiV2AssetsExportsDestroyMockHandler(),
]
