/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KoboToolbox API
 * Powerful and intuitive data collection tools to make an impact
 * OpenAPI spec version: 2.0.0 (api_v2)
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { ErrorDetail } from './models/errorDetail'

import type { ErrorObject } from './models/errorObject'

import type { MeEmailsCreateParams } from './models/meEmailsCreateParams'

import type { MeEmailsListParams } from './models/meEmailsListParams'

import type { MeSocialAccountsDestroyParams } from './models/meSocialAccountsDestroyParams'

import type { MeSocialAccountsListParams } from './models/meSocialAccountsListParams'

import type { MeSocialAccountsRetrieveParams } from './models/meSocialAccountsRetrieveParams'

import type { PatchedCurrentUser } from './models/patchedCurrentUser'

import { faker } from '@faker-js/faker'

import { http, HttpResponse, delay } from 'msw'

import type { EmailAddress } from './models/emailAddress'

import type { MeListResponse } from './models/meListResponse'

import type { PaginatedEmailAddressList } from './models/paginatedEmailAddressList'

import type { PaginatedSocialAccountList } from './models/paginatedSocialAccountList'

import type { SocialAccount } from './models/socialAccount'

import { koboCustomOrvalMutationOptions } from '../orval.mutationOptions'

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<{ [Q in P]: T[P] }, { -readonly [Q in P]: T[P] }, P>
}[keyof T]

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void ? I : never
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never

type Writable<T> = Pick<T, WritableKeys<T>>
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object ? NonReadonly<NonNullable<T[P]>> : T[P]
    }
  : DistributeReadOnlyOverUnions<T>

/**
 * ## Retrieve current user profile

 */
export type meRetrieveResponse200 = {
  data: MeListResponse
  status: 200
}

export type meRetrieveResponse401 = {
  data: ErrorDetail
  status: 401
}

export type meRetrieveResponseComposite = meRetrieveResponse200 | meRetrieveResponse401

export type meRetrieveResponse = meRetrieveResponseComposite & {
  headers: Headers
}

export const getMeRetrieveUrl = () => {
  return `/me/`
}

export const meRetrieve = async (options?: RequestInit): Promise<meRetrieveResponse> => {
  const res = await fetch(getMeRetrieveUrl(), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: meRetrieveResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as meRetrieveResponse
}

export const getMeRetrieveQueryKey = () => {
  return ['me'] as const
}

export const getMeRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof meRetrieve>>,
  TError = ErrorDetail,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meRetrieve>>, TError, TData>>
  fetch?: RequestInit
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getMeRetrieveQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof meRetrieve>>> = ({ signal }) =>
    meRetrieve({ signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof meRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof meRetrieve>>>
export type MeRetrieveQueryError = ErrorDetail

export function useMeRetrieve<TData = Awaited<ReturnType<typeof meRetrieve>>, TError = ErrorDetail>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof meRetrieve>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof meRetrieve>>,
          TError,
          Awaited<ReturnType<typeof meRetrieve>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeRetrieve<TData = Awaited<ReturnType<typeof meRetrieve>>, TError = ErrorDetail>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meRetrieve>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof meRetrieve>>,
          TError,
          Awaited<ReturnType<typeof meRetrieve>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeRetrieve<TData = Awaited<ReturnType<typeof meRetrieve>>, TError = ErrorDetail>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMeRetrieve<TData = Awaited<ReturnType<typeof meRetrieve>>, TError = ErrorDetail>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMeRetrieveQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * ## Update current user infos

 */
export type mePartialUpdateResponse200 = {
  data: MeListResponse
  status: 200
}

export type mePartialUpdateResponse400 = {
  data: ErrorObject
  status: 400
}

export type mePartialUpdateResponse401 = {
  data: ErrorDetail
  status: 401
}

export type mePartialUpdateResponseComposite =
  | mePartialUpdateResponse200
  | mePartialUpdateResponse400
  | mePartialUpdateResponse401

export type mePartialUpdateResponse = mePartialUpdateResponseComposite & {
  headers: Headers
}

export const getMePartialUpdateUrl = () => {
  return `/me/`
}

export const mePartialUpdate = async (
  patchedCurrentUser: NonReadonly<PatchedCurrentUser>,
  options?: RequestInit,
): Promise<mePartialUpdateResponse> => {
  const res = await fetch(getMePartialUpdateUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchedCurrentUser),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: mePartialUpdateResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as mePartialUpdateResponse
}

export const useMePartialUpdateMutationOptions = <TError = ErrorObject | ErrorDetail, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof mePartialUpdate>>,
    TError,
    { data: NonReadonly<PatchedCurrentUser> },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof mePartialUpdate>>,
  TError,
  { data: NonReadonly<PatchedCurrentUser> },
  TContext
> => {
  const mutationKey = ['mePartialUpdate']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof mePartialUpdate>>,
    { data: NonReadonly<PatchedCurrentUser> }
  > = (props) => {
    const { data } = props ?? {}

    return mePartialUpdate(data, fetchOptions)
  }

  const customOptions = koboCustomOrvalMutationOptions({ ...mutationOptions, mutationFn })

  return customOptions
}

export type MePartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof mePartialUpdate>>>
export type MePartialUpdateMutationBody = NonReadonly<PatchedCurrentUser>
export type MePartialUpdateMutationError = ErrorObject | ErrorDetail

export const useMePartialUpdate = <TError = ErrorObject | ErrorDetail, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof mePartialUpdate>>,
      TError,
      { data: NonReadonly<PatchedCurrentUser> },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof mePartialUpdate>>,
  TError,
  { data: NonReadonly<PatchedCurrentUser> },
  TContext
> => {
  const mutationOptions = useMePartialUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * ## Delete current user

> Payload Example:
>
>       {
>           "confirm": "user__extra_details__uid",
>       }


### !! Due to current DRF-Spectacular limitations with AOS 3.1, DELETE operations do not display request or response bodies in this documentation (as payloads are not typically recommended for DELETE). This means direct testing is unavailable. However, example payloads and responses are provided for reference, and HTTP codes/error messages are accurate.  !!

 */
export type meDestroyResponse204 = {
  data: void
  status: 204
}

export type meDestroyResponse400 = {
  data: ErrorObject
  status: 400
}

export type meDestroyResponse401 = {
  data: ErrorDetail
  status: 401
}

export type meDestroyResponseComposite = meDestroyResponse204 | meDestroyResponse400 | meDestroyResponse401

export type meDestroyResponse = meDestroyResponseComposite & {
  headers: Headers
}

export const getMeDestroyUrl = () => {
  return `/me/`
}

export const meDestroy = async (options?: RequestInit): Promise<meDestroyResponse> => {
  const res = await fetch(getMeDestroyUrl(), {
    ...options,
    method: 'DELETE',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: meDestroyResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as meDestroyResponse
}

export const useMeDestroyMutationOptions = <TError = ErrorObject | ErrorDetail, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof meDestroy>>, TError, void, TContext>
  fetch?: RequestInit
}): UseMutationOptions<Awaited<ReturnType<typeof meDestroy>>, TError, void, TContext> => {
  const mutationKey = ['meDestroy']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof meDestroy>>, void> = () => {
    return meDestroy(fetchOptions)
  }

  const customOptions = koboCustomOrvalMutationOptions({ ...mutationOptions, mutationFn })

  return customOptions
}

export type MeDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof meDestroy>>>

export type MeDestroyMutationError = ErrorObject | ErrorDetail

export const useMeDestroy = <TError = ErrorObject | ErrorDetail, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof meDestroy>>, TError, void, TContext>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof meDestroy>>, TError, void, TContext> => {
  const mutationOptions = useMeDestroyMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * View and change email. Allow only 1 primary/confirmed email.

Set a new email: POST a new email address. The new email will be unverified
and replace existing unverfied, non-primary emails. New email is not usable
until verified.

Delete unconfirmed email: DELETE with no body will delete any existing
non-primary/non-verified emails.
 */
export type meEmailsListResponse200 = {
  data: PaginatedEmailAddressList
  status: 200
}

export type meEmailsListResponseComposite = meEmailsListResponse200

export type meEmailsListResponse = meEmailsListResponseComposite & {
  headers: Headers
}

export const getMeEmailsListUrl = (params?: MeEmailsListParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/me/emails/?${stringifiedParams}` : `/me/emails/`
}

export const meEmailsList = async (
  params?: MeEmailsListParams,
  options?: RequestInit,
): Promise<meEmailsListResponse> => {
  const res = await fetch(getMeEmailsListUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: meEmailsListResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as meEmailsListResponse
}

export const getMeEmailsListQueryKey = (params?: MeEmailsListParams) => {
  return ['me', 'emails', ...(params ? [params] : [])] as const
}

export const getMeEmailsListQueryOptions = <TData = Awaited<ReturnType<typeof meEmailsList>>, TError = unknown>(
  params?: MeEmailsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meEmailsList>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getMeEmailsListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof meEmailsList>>> = ({ signal }) =>
    meEmailsList(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof meEmailsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeEmailsListQueryResult = NonNullable<Awaited<ReturnType<typeof meEmailsList>>>
export type MeEmailsListQueryError = unknown

export function useMeEmailsList<TData = Awaited<ReturnType<typeof meEmailsList>>, TError = unknown>(
  params: undefined | MeEmailsListParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof meEmailsList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof meEmailsList>>,
          TError,
          Awaited<ReturnType<typeof meEmailsList>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeEmailsList<TData = Awaited<ReturnType<typeof meEmailsList>>, TError = unknown>(
  params?: MeEmailsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meEmailsList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof meEmailsList>>,
          TError,
          Awaited<ReturnType<typeof meEmailsList>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeEmailsList<TData = Awaited<ReturnType<typeof meEmailsList>>, TError = unknown>(
  params?: MeEmailsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meEmailsList>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMeEmailsList<TData = Awaited<ReturnType<typeof meEmailsList>>, TError = unknown>(
  params?: MeEmailsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meEmailsList>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMeEmailsListQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * View and change email. Allow only 1 primary/confirmed email.

Set a new email: POST a new email address. The new email will be unverified
and replace existing unverfied, non-primary emails. New email is not usable
until verified.

Delete unconfirmed email: DELETE with no body will delete any existing
non-primary/non-verified emails.
 */
export type meEmailsCreateResponse201 = {
  data: EmailAddress
  status: 201
}

export type meEmailsCreateResponseComposite = meEmailsCreateResponse201

export type meEmailsCreateResponse = meEmailsCreateResponseComposite & {
  headers: Headers
}

export const getMeEmailsCreateUrl = (params?: MeEmailsCreateParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/me/emails/?${stringifiedParams}` : `/me/emails/`
}

export const meEmailsCreate = async (
  emailAddress: NonReadonly<EmailAddress>,
  params?: MeEmailsCreateParams,
  options?: RequestInit,
): Promise<meEmailsCreateResponse> => {
  const res = await fetch(getMeEmailsCreateUrl(params), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(emailAddress),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: meEmailsCreateResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as meEmailsCreateResponse
}

export const useMeEmailsCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof meEmailsCreate>>,
    TError,
    { data: NonReadonly<EmailAddress>; params?: MeEmailsCreateParams },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof meEmailsCreate>>,
  TError,
  { data: NonReadonly<EmailAddress>; params?: MeEmailsCreateParams },
  TContext
> => {
  const mutationKey = ['meEmailsCreate']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof meEmailsCreate>>,
    { data: NonReadonly<EmailAddress>; params?: MeEmailsCreateParams }
  > = (props) => {
    const { data, params } = props ?? {}

    return meEmailsCreate(data, params, fetchOptions)
  }

  const customOptions = koboCustomOrvalMutationOptions({ ...mutationOptions, mutationFn })

  return customOptions
}

export type MeEmailsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof meEmailsCreate>>>
export type MeEmailsCreateMutationBody = NonReadonly<EmailAddress>
export type MeEmailsCreateMutationError = unknown

export const useMeEmailsCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof meEmailsCreate>>,
      TError,
      { data: NonReadonly<EmailAddress>; params?: MeEmailsCreateParams },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof meEmailsCreate>>,
  TError,
  { data: NonReadonly<EmailAddress>; params?: MeEmailsCreateParams },
  TContext
> => {
  const mutationOptions = useMeEmailsCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Apply this mixin to any view or viewset to enable multi-field lookups
based on a `lookup_fields` attribute, instead of the default single-field lookup
(`lookup_field`).

⚠️ Warning:
Make sure to declare the route using `.as_view()` so that `lookup_value_regex` is
properly applied. Avoid using DRF's automatic routers, which rely on the default
`lookup_field = 'pk'`.
 */
export type meSocialAccountsListResponse200 = {
  data: PaginatedSocialAccountList
  status: 200
}

export type meSocialAccountsListResponseComposite = meSocialAccountsListResponse200

export type meSocialAccountsListResponse = meSocialAccountsListResponseComposite & {
  headers: Headers
}

export const getMeSocialAccountsListUrl = (params?: MeSocialAccountsListParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/me/social-accounts/?${stringifiedParams}` : `/me/social-accounts/`
}

export const meSocialAccountsList = async (
  params?: MeSocialAccountsListParams,
  options?: RequestInit,
): Promise<meSocialAccountsListResponse> => {
  const res = await fetch(getMeSocialAccountsListUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: meSocialAccountsListResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as meSocialAccountsListResponse
}

export const getMeSocialAccountsListQueryKey = (params?: MeSocialAccountsListParams) => {
  return ['me', 'social-accounts', ...(params ? [params] : [])] as const
}

export const getMeSocialAccountsListQueryOptions = <
  TData = Awaited<ReturnType<typeof meSocialAccountsList>>,
  TError = unknown,
>(
  params?: MeSocialAccountsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meSocialAccountsList>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getMeSocialAccountsListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof meSocialAccountsList>>> = ({ signal }) =>
    meSocialAccountsList(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof meSocialAccountsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeSocialAccountsListQueryResult = NonNullable<Awaited<ReturnType<typeof meSocialAccountsList>>>
export type MeSocialAccountsListQueryError = unknown

export function useMeSocialAccountsList<TData = Awaited<ReturnType<typeof meSocialAccountsList>>, TError = unknown>(
  params: undefined | MeSocialAccountsListParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof meSocialAccountsList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof meSocialAccountsList>>,
          TError,
          Awaited<ReturnType<typeof meSocialAccountsList>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeSocialAccountsList<TData = Awaited<ReturnType<typeof meSocialAccountsList>>, TError = unknown>(
  params?: MeSocialAccountsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meSocialAccountsList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof meSocialAccountsList>>,
          TError,
          Awaited<ReturnType<typeof meSocialAccountsList>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeSocialAccountsList<TData = Awaited<ReturnType<typeof meSocialAccountsList>>, TError = unknown>(
  params?: MeSocialAccountsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meSocialAccountsList>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMeSocialAccountsList<TData = Awaited<ReturnType<typeof meSocialAccountsList>>, TError = unknown>(
  params?: MeSocialAccountsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meSocialAccountsList>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMeSocialAccountsListQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Apply this mixin to any view or viewset to enable multi-field lookups
based on a `lookup_fields` attribute, instead of the default single-field lookup
(`lookup_field`).

⚠️ Warning:
Make sure to declare the route using `.as_view()` so that `lookup_value_regex` is
properly applied. Avoid using DRF's automatic routers, which rely on the default
`lookup_field = 'pk'`.
 */
export type meSocialAccountsRetrieveResponse200 = {
  data: SocialAccount
  status: 200
}

export type meSocialAccountsRetrieveResponseComposite = meSocialAccountsRetrieveResponse200

export type meSocialAccountsRetrieveResponse = meSocialAccountsRetrieveResponseComposite & {
  headers: Headers
}

export const getMeSocialAccountsRetrieveUrl = (
  provider: string,
  uid: string,
  params?: MeSocialAccountsRetrieveParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/me/social-accounts/${provider}/${uid}/?${stringifiedParams}`
    : `/me/social-accounts/${provider}/${uid}/`
}

export const meSocialAccountsRetrieve = async (
  provider: string,
  uid: string,
  params?: MeSocialAccountsRetrieveParams,
  options?: RequestInit,
): Promise<meSocialAccountsRetrieveResponse> => {
  const res = await fetch(getMeSocialAccountsRetrieveUrl(provider, uid, params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: meSocialAccountsRetrieveResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as meSocialAccountsRetrieveResponse
}

export const getMeSocialAccountsRetrieveQueryKey = (
  provider: string,
  uid: string,
  params?: MeSocialAccountsRetrieveParams,
) => {
  return ['me', 'social-accounts', provider, uid, ...(params ? [params] : [])] as const
}

export const getMeSocialAccountsRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof meSocialAccountsRetrieve>>,
  TError = unknown,
>(
  provider: string,
  uid: string,
  params?: MeSocialAccountsRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meSocialAccountsRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getMeSocialAccountsRetrieveQueryKey(provider, uid, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof meSocialAccountsRetrieve>>> = ({ signal }) =>
    meSocialAccountsRetrieve(provider, uid, params, { signal, ...fetchOptions })

  return { queryKey, queryFn, enabled: !!(provider && uid), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof meSocialAccountsRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeSocialAccountsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof meSocialAccountsRetrieve>>>
export type MeSocialAccountsRetrieveQueryError = unknown

export function useMeSocialAccountsRetrieve<
  TData = Awaited<ReturnType<typeof meSocialAccountsRetrieve>>,
  TError = unknown,
>(
  provider: string,
  uid: string,
  params: undefined | MeSocialAccountsRetrieveParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof meSocialAccountsRetrieve>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof meSocialAccountsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof meSocialAccountsRetrieve>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeSocialAccountsRetrieve<
  TData = Awaited<ReturnType<typeof meSocialAccountsRetrieve>>,
  TError = unknown,
>(
  provider: string,
  uid: string,
  params?: MeSocialAccountsRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meSocialAccountsRetrieve>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof meSocialAccountsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof meSocialAccountsRetrieve>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeSocialAccountsRetrieve<
  TData = Awaited<ReturnType<typeof meSocialAccountsRetrieve>>,
  TError = unknown,
>(
  provider: string,
  uid: string,
  params?: MeSocialAccountsRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meSocialAccountsRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMeSocialAccountsRetrieve<
  TData = Awaited<ReturnType<typeof meSocialAccountsRetrieve>>,
  TError = unknown,
>(
  provider: string,
  uid: string,
  params?: MeSocialAccountsRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meSocialAccountsRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMeSocialAccountsRetrieveQueryOptions(provider, uid, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Apply this mixin to any view or viewset to enable multi-field lookups
based on a `lookup_fields` attribute, instead of the default single-field lookup
(`lookup_field`).

⚠️ Warning:
Make sure to declare the route using `.as_view()` so that `lookup_value_regex` is
properly applied. Avoid using DRF's automatic routers, which rely on the default
`lookup_field = 'pk'`.
 */
export type meSocialAccountsDestroyResponse204 = {
  data: void
  status: 204
}

export type meSocialAccountsDestroyResponseComposite = meSocialAccountsDestroyResponse204

export type meSocialAccountsDestroyResponse = meSocialAccountsDestroyResponseComposite & {
  headers: Headers
}

export const getMeSocialAccountsDestroyUrl = (
  provider: string,
  uid: string,
  params?: MeSocialAccountsDestroyParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/me/social-accounts/${provider}/${uid}/?${stringifiedParams}`
    : `/me/social-accounts/${provider}/${uid}/`
}

export const meSocialAccountsDestroy = async (
  provider: string,
  uid: string,
  params?: MeSocialAccountsDestroyParams,
  options?: RequestInit,
): Promise<meSocialAccountsDestroyResponse> => {
  const res = await fetch(getMeSocialAccountsDestroyUrl(provider, uid, params), {
    ...options,
    method: 'DELETE',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: meSocialAccountsDestroyResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as meSocialAccountsDestroyResponse
}

export const useMeSocialAccountsDestroyMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof meSocialAccountsDestroy>>,
    TError,
    { provider: string; uid: string; params?: MeSocialAccountsDestroyParams },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof meSocialAccountsDestroy>>,
  TError,
  { provider: string; uid: string; params?: MeSocialAccountsDestroyParams },
  TContext
> => {
  const mutationKey = ['meSocialAccountsDestroy']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof meSocialAccountsDestroy>>,
    { provider: string; uid: string; params?: MeSocialAccountsDestroyParams }
  > = (props) => {
    const { provider, uid, params } = props ?? {}

    return meSocialAccountsDestroy(provider, uid, params, fetchOptions)
  }

  const customOptions = koboCustomOrvalMutationOptions({ ...mutationOptions, mutationFn })

  return customOptions
}

export type MeSocialAccountsDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof meSocialAccountsDestroy>>>

export type MeSocialAccountsDestroyMutationError = unknown

export const useMeSocialAccountsDestroy = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof meSocialAccountsDestroy>>,
      TError,
      { provider: string; uid: string; params?: MeSocialAccountsDestroyParams },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof meSocialAccountsDestroy>>,
  TError,
  { provider: string; uid: string; params?: MeSocialAccountsDestroyParams },
  TContext
> => {
  const mutationOptions = useMeSocialAccountsDestroyMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}

export const getMeRetrieveResponseMock = (overrideResponse: Partial<MeListResponse> = {}): MeListResponse => ({
  username: faker.string.alpha({ length: { min: 10, max: 20 } }),
  first_name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  last_name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  email: faker.internet.email(),
  server_time: `${faker.date.past().toISOString().split('.')[0]}Z`,
  date_joined: `${faker.date.past().toISOString().split('.')[0]}Z`,
  projects_url: faker.internet.url(),
  gravatar: faker.internet.url(),
  last_login: `${faker.date.past().toISOString().split('.')[0]}Z`,
  extra_details: {
    bio: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    city: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    sector: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    country: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    twitter: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    linkedin: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    instagram: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    organization: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    last_ui_language: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    organization_type: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    organization_website: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    project_views_settings: faker.helpers.arrayElement([{}, undefined]),
    require_auth: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    newsletter_subscription: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
  },
  git_rev: faker.string.alpha({ length: { min: 10, max: 20 } }),
  social_accounts: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    provider: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    uid: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    last_joined: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]),
    date_joined: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]),
    email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
    username: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  })),
  validated_password: faker.datatype.boolean(),
  accepted_tos: faker.datatype.boolean(),
  organization: {
    url: faker.helpers.arrayElement([faker.internet.url(), undefined]),
    name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    uid: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  },
  extra_details__uid: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
})

export const getMePartialUpdateResponseMock = (overrideResponse: Partial<MeListResponse> = {}): MeListResponse => ({
  username: faker.string.alpha({ length: { min: 10, max: 20 } }),
  first_name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  last_name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  email: faker.internet.email(),
  server_time: `${faker.date.past().toISOString().split('.')[0]}Z`,
  date_joined: `${faker.date.past().toISOString().split('.')[0]}Z`,
  projects_url: faker.internet.url(),
  gravatar: faker.internet.url(),
  last_login: `${faker.date.past().toISOString().split('.')[0]}Z`,
  extra_details: {
    bio: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    city: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    sector: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    country: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    twitter: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    linkedin: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    instagram: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    organization: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    last_ui_language: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    organization_type: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    organization_website: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    project_views_settings: faker.helpers.arrayElement([{}, undefined]),
    require_auth: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    newsletter_subscription: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
  },
  git_rev: faker.string.alpha({ length: { min: 10, max: 20 } }),
  social_accounts: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    provider: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    uid: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    last_joined: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]),
    date_joined: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]),
    email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
    username: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  })),
  validated_password: faker.datatype.boolean(),
  accepted_tos: faker.datatype.boolean(),
  organization: {
    url: faker.helpers.arrayElement([faker.internet.url(), undefined]),
    name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    uid: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  },
  extra_details__uid: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
})

export const getMeEmailsListResponseMock = (
  overrideResponse: Partial<PaginatedEmailAddressList> = {},
): PaginatedEmailAddressList => ({
  count: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  next: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
  previous: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
  results: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    primary: faker.datatype.boolean(),
    email: faker.internet.email(),
    verified: faker.datatype.boolean(),
  })),
  ...overrideResponse,
})

export const getMeEmailsCreateResponseMock = (overrideResponse: Partial<EmailAddress> = {}): EmailAddress => ({
  primary: faker.datatype.boolean(),
  email: faker.internet.email(),
  verified: faker.datatype.boolean(),
  ...overrideResponse,
})

export const getMeSocialAccountsListResponseMock = (
  overrideResponse: Partial<PaginatedSocialAccountList> = {},
): PaginatedSocialAccountList => ({
  count: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  next: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
  previous: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
  results: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    provider: faker.string.alpha({ length: { min: 10, max: 200 } }),
    uid: faker.string.alpha({ length: { min: 10, max: 191 } }),
    last_login: `${faker.date.past().toISOString().split('.')[0]}Z`,
    date_joined: `${faker.date.past().toISOString().split('.')[0]}Z`,
    email: faker.internet.email(),
    username: faker.string.alpha({ length: { min: 10, max: 20 } }),
  })),
  ...overrideResponse,
})

export const getMeSocialAccountsRetrieveResponseMock = (
  overrideResponse: Partial<SocialAccount> = {},
): SocialAccount => ({
  provider: faker.string.alpha({ length: { min: 10, max: 200 } }),
  uid: faker.string.alpha({ length: { min: 10, max: 191 } }),
  last_login: `${faker.date.past().toISOString().split('.')[0]}Z`,
  date_joined: `${faker.date.past().toISOString().split('.')[0]}Z`,
  email: faker.internet.email(),
  username: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
})

export const getMeRetrieveMockHandler = (
  overrideResponse?:
    | MeListResponse
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MeListResponse> | MeListResponse),
) => {
  return http.get('*/me/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getMeRetrieveResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getMePartialUpdateMockHandler = (
  overrideResponse?:
    | MeListResponse
    | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<MeListResponse> | MeListResponse),
) => {
  return http.patch('*/me/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getMePartialUpdateResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getMeDestroyMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
) => {
  return http.delete('*/me/', async (info) => {
    await delay(1000)
    if (typeof overrideResponse === 'function') {
      await overrideResponse(info)
    }
    return new HttpResponse(null, { status: 204 })
  })
}

export const getMeEmailsListMockHandler = (
  overrideResponse?:
    | PaginatedEmailAddressList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PaginatedEmailAddressList> | PaginatedEmailAddressList),
) => {
  return http.get('*/me/emails/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getMeEmailsListResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getMeEmailsCreateMockHandler = (
  overrideResponse?:
    | EmailAddress
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<EmailAddress> | EmailAddress),
) => {
  return http.post('*/me/emails/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getMeEmailsCreateResponseMock(),
      ),
      { status: 201, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getMeSocialAccountsListMockHandler = (
  overrideResponse?:
    | PaginatedSocialAccountList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PaginatedSocialAccountList> | PaginatedSocialAccountList),
) => {
  return http.get('*/me/social-accounts/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getMeSocialAccountsListResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getMeSocialAccountsRetrieveMockHandler = (
  overrideResponse?:
    | SocialAccount
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SocialAccount> | SocialAccount),
) => {
  return http.get('*/me/social-accounts/:provider/:uid/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getMeSocialAccountsRetrieveResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getMeSocialAccountsDestroyMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
) => {
  return http.delete('*/me/social-accounts/:provider/:uid/', async (info) => {
    await delay(1000)
    if (typeof overrideResponse === 'function') {
      await overrideResponse(info)
    }
    return new HttpResponse(null, { status: 204 })
  })
}
export const getMeMock = () => [
  getMeRetrieveMockHandler(),
  getMePartialUpdateMockHandler(),
  getMeDestroyMockHandler(),
  getMeEmailsListMockHandler(),
  getMeEmailsCreateMockHandler(),
  getMeSocialAccountsListMockHandler(),
  getMeSocialAccountsRetrieveMockHandler(),
  getMeSocialAccountsDestroyMockHandler(),
]
