/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KoboToolbox API
 * Powerful and intuitive data collection tools to make an impact
 * OpenAPI spec version: 2.0.0 (api_v2)
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { ProjectViewsAssetsRetrieveParams } from './models/projectViewsAssetsRetrieveParams'

import type { ProjectViewsExportCreateParams } from './models/projectViewsExportCreateParams'

import type { ProjectViewsExportRetrieveParams } from './models/projectViewsExportRetrieveParams'

import type { ProjectViewsListParams } from './models/projectViewsListParams'

import type { ProjectViewsRetrieveParams } from './models/projectViewsRetrieveParams'

import type { ProjectViewsUsersRetrieveParams } from './models/projectViewsUsersRetrieveParams'

import { faker } from '@faker-js/faker'

import { http, HttpResponse, delay } from 'msw'

import type { PaginatedProjectViewList } from './models/paginatedProjectViewList'

import type { ProjectView } from './models/projectView'

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<{ [Q in P]: T[P] }, { -readonly [Q in P]: T[P] }, P>
}[keyof T]

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void ? I : never
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never

type Writable<T> = Pick<T, WritableKeys<T>>
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object ? NonReadonly<NonNullable<T[P]>> : T[P]
    }
  : DistributeReadOnlyOverUnions<T>

export type projectViewsListResponse200 = {
  data: PaginatedProjectViewList
  status: 200
}

export type projectViewsListResponseComposite = projectViewsListResponse200

export type projectViewsListResponse = projectViewsListResponseComposite & {
  headers: Headers
}

export const getProjectViewsListUrl = (params?: ProjectViewsListParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/api/v2/project-views/?${stringifiedParams}` : `/api/v2/project-views/`
}

export const projectViewsList = async (
  params?: ProjectViewsListParams,
  options?: RequestInit,
): Promise<projectViewsListResponse> => {
  const res = await fetch(getProjectViewsListUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: projectViewsListResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as projectViewsListResponse
}

export const getProjectViewsListQueryKey = (params?: ProjectViewsListParams) => {
  return [`/api/v2/project-views/`, ...(params ? [params] : [])] as const
}

export const getProjectViewsListQueryOptions = <TData = Awaited<ReturnType<typeof projectViewsList>>, TError = unknown>(
  params?: ProjectViewsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsList>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getProjectViewsListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof projectViewsList>>> = ({ signal }) =>
    projectViewsList(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof projectViewsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> }
}

export type ProjectViewsListQueryResult = NonNullable<Awaited<ReturnType<typeof projectViewsList>>>
export type ProjectViewsListQueryError = unknown

export function useProjectViewsList<TData = Awaited<ReturnType<typeof projectViewsList>>, TError = unknown>(
  params: undefined | ProjectViewsListParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectViewsList>>,
          TError,
          Awaited<ReturnType<typeof projectViewsList>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useProjectViewsList<TData = Awaited<ReturnType<typeof projectViewsList>>, TError = unknown>(
  params?: ProjectViewsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectViewsList>>,
          TError,
          Awaited<ReturnType<typeof projectViewsList>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useProjectViewsList<TData = Awaited<ReturnType<typeof projectViewsList>>, TError = unknown>(
  params?: ProjectViewsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsList>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useProjectViewsList<TData = Awaited<ReturnType<typeof projectViewsList>>, TError = unknown>(
  params?: ProjectViewsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsList>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getProjectViewsListQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

export type projectViewsRetrieveResponse200 = {
  data: ProjectView
  status: 200
}

export type projectViewsRetrieveResponseComposite = projectViewsRetrieveResponse200

export type projectViewsRetrieveResponse = projectViewsRetrieveResponseComposite & {
  headers: Headers
}

export const getProjectViewsRetrieveUrl = (uid: string, params?: ProjectViewsRetrieveParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v2/project-views/${uid}/?${stringifiedParams}`
    : `/api/v2/project-views/${uid}/`
}

export const projectViewsRetrieve = async (
  uid: string,
  params?: ProjectViewsRetrieveParams,
  options?: RequestInit,
): Promise<projectViewsRetrieveResponse> => {
  const res = await fetch(getProjectViewsRetrieveUrl(uid, params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: projectViewsRetrieveResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as projectViewsRetrieveResponse
}

export const getProjectViewsRetrieveQueryKey = (uid: string, params?: ProjectViewsRetrieveParams) => {
  return [`/api/v2/project-views/${uid}/`, ...(params ? [params] : [])] as const
}

export const getProjectViewsRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof projectViewsRetrieve>>,
  TError = unknown,
>(
  uid: string,
  params?: ProjectViewsRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getProjectViewsRetrieveQueryKey(uid, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof projectViewsRetrieve>>> = ({ signal }) =>
    projectViewsRetrieve(uid, params, { signal, ...fetchOptions })

  return { queryKey, queryFn, enabled: !!uid, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof projectViewsRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> }
}

export type ProjectViewsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof projectViewsRetrieve>>>
export type ProjectViewsRetrieveQueryError = unknown

export function useProjectViewsRetrieve<TData = Awaited<ReturnType<typeof projectViewsRetrieve>>, TError = unknown>(
  uid: string,
  params: undefined | ProjectViewsRetrieveParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsRetrieve>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectViewsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof projectViewsRetrieve>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useProjectViewsRetrieve<TData = Awaited<ReturnType<typeof projectViewsRetrieve>>, TError = unknown>(
  uid: string,
  params?: ProjectViewsRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsRetrieve>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectViewsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof projectViewsRetrieve>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useProjectViewsRetrieve<TData = Awaited<ReturnType<typeof projectViewsRetrieve>>, TError = unknown>(
  uid: string,
  params?: ProjectViewsRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useProjectViewsRetrieve<TData = Awaited<ReturnType<typeof projectViewsRetrieve>>, TError = unknown>(
  uid: string,
  params?: ProjectViewsRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getProjectViewsRetrieveQueryOptions(uid, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

export type projectViewsExportRetrieveResponse200 = {
  data: ProjectView
  status: 200
}

export type projectViewsExportRetrieveResponseComposite = projectViewsExportRetrieveResponse200

export type projectViewsExportRetrieveResponse = projectViewsExportRetrieveResponseComposite & {
  headers: Headers
}

export const getProjectViewsExportRetrieveUrl = (
  uid: string,
  objType: string,
  params?: ProjectViewsExportRetrieveParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v2/project-views/${uid}/${objType}/export/?${stringifiedParams}`
    : `/api/v2/project-views/${uid}/${objType}/export/`
}

export const projectViewsExportRetrieve = async (
  uid: string,
  objType: string,
  params?: ProjectViewsExportRetrieveParams,
  options?: RequestInit,
): Promise<projectViewsExportRetrieveResponse> => {
  const res = await fetch(getProjectViewsExportRetrieveUrl(uid, objType, params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: projectViewsExportRetrieveResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as projectViewsExportRetrieveResponse
}

export const getProjectViewsExportRetrieveQueryKey = (
  uid: string,
  objType: string,
  params?: ProjectViewsExportRetrieveParams,
) => {
  return [`/api/v2/project-views/${uid}/${objType}/export/`, ...(params ? [params] : [])] as const
}

export const getProjectViewsExportRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof projectViewsExportRetrieve>>,
  TError = unknown,
>(
  uid: string,
  objType: string,
  params?: ProjectViewsExportRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsExportRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getProjectViewsExportRetrieveQueryKey(uid, objType, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof projectViewsExportRetrieve>>> = ({ signal }) =>
    projectViewsExportRetrieve(uid, objType, params, { signal, ...fetchOptions })

  return { queryKey, queryFn, enabled: !!(uid && objType), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof projectViewsExportRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> }
}

export type ProjectViewsExportRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof projectViewsExportRetrieve>>>
export type ProjectViewsExportRetrieveQueryError = unknown

export function useProjectViewsExportRetrieve<
  TData = Awaited<ReturnType<typeof projectViewsExportRetrieve>>,
  TError = unknown,
>(
  uid: string,
  objType: string,
  params: undefined | ProjectViewsExportRetrieveParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsExportRetrieve>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectViewsExportRetrieve>>,
          TError,
          Awaited<ReturnType<typeof projectViewsExportRetrieve>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useProjectViewsExportRetrieve<
  TData = Awaited<ReturnType<typeof projectViewsExportRetrieve>>,
  TError = unknown,
>(
  uid: string,
  objType: string,
  params?: ProjectViewsExportRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsExportRetrieve>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectViewsExportRetrieve>>,
          TError,
          Awaited<ReturnType<typeof projectViewsExportRetrieve>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useProjectViewsExportRetrieve<
  TData = Awaited<ReturnType<typeof projectViewsExportRetrieve>>,
  TError = unknown,
>(
  uid: string,
  objType: string,
  params?: ProjectViewsExportRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsExportRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useProjectViewsExportRetrieve<
  TData = Awaited<ReturnType<typeof projectViewsExportRetrieve>>,
  TError = unknown,
>(
  uid: string,
  objType: string,
  params?: ProjectViewsExportRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsExportRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getProjectViewsExportRetrieveQueryOptions(uid, objType, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

export type projectViewsExportCreateResponse200 = {
  data: ProjectView
  status: 200
}

export type projectViewsExportCreateResponseComposite = projectViewsExportCreateResponse200

export type projectViewsExportCreateResponse = projectViewsExportCreateResponseComposite & {
  headers: Headers
}

export const getProjectViewsExportCreateUrl = (
  uid: string,
  objType: string,
  params?: ProjectViewsExportCreateParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v2/project-views/${uid}/${objType}/export/?${stringifiedParams}`
    : `/api/v2/project-views/${uid}/${objType}/export/`
}

export const projectViewsExportCreate = async (
  uid: string,
  objType: string,
  projectView: NonReadonly<ProjectView>,
  params?: ProjectViewsExportCreateParams,
  options?: RequestInit,
): Promise<projectViewsExportCreateResponse> => {
  const res = await fetch(getProjectViewsExportCreateUrl(uid, objType, params), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(projectView),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: projectViewsExportCreateResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as projectViewsExportCreateResponse
}

export const getProjectViewsExportCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof projectViewsExportCreate>>,
    TError,
    { uid: string; objType: string; data: NonReadonly<ProjectView>; params?: ProjectViewsExportCreateParams },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof projectViewsExportCreate>>,
  TError,
  { uid: string; objType: string; data: NonReadonly<ProjectView>; params?: ProjectViewsExportCreateParams },
  TContext
> => {
  const mutationKey = ['projectViewsExportCreate']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof projectViewsExportCreate>>,
    { uid: string; objType: string; data: NonReadonly<ProjectView>; params?: ProjectViewsExportCreateParams }
  > = (props) => {
    const { uid, objType, data, params } = props ?? {}

    return projectViewsExportCreate(uid, objType, data, params, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ProjectViewsExportCreateMutationResult = NonNullable<Awaited<ReturnType<typeof projectViewsExportCreate>>>
export type ProjectViewsExportCreateMutationBody = NonReadonly<ProjectView>
export type ProjectViewsExportCreateMutationError = unknown

export const useProjectViewsExportCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof projectViewsExportCreate>>,
      TError,
      { uid: string; objType: string; data: NonReadonly<ProjectView>; params?: ProjectViewsExportCreateParams },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof projectViewsExportCreate>>,
  TError,
  { uid: string; objType: string; data: NonReadonly<ProjectView>; params?: ProjectViewsExportCreateParams },
  TContext
> => {
  const mutationOptions = getProjectViewsExportCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
export type projectViewsAssetsRetrieveResponse200 = {
  data: ProjectView
  status: 200
}

export type projectViewsAssetsRetrieveResponseComposite = projectViewsAssetsRetrieveResponse200

export type projectViewsAssetsRetrieveResponse = projectViewsAssetsRetrieveResponseComposite & {
  headers: Headers
}

export const getProjectViewsAssetsRetrieveUrl = (uid: string, params?: ProjectViewsAssetsRetrieveParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v2/project-views/${uid}/assets/?${stringifiedParams}`
    : `/api/v2/project-views/${uid}/assets/`
}

export const projectViewsAssetsRetrieve = async (
  uid: string,
  params?: ProjectViewsAssetsRetrieveParams,
  options?: RequestInit,
): Promise<projectViewsAssetsRetrieveResponse> => {
  const res = await fetch(getProjectViewsAssetsRetrieveUrl(uid, params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: projectViewsAssetsRetrieveResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as projectViewsAssetsRetrieveResponse
}

export const getProjectViewsAssetsRetrieveQueryKey = (uid: string, params?: ProjectViewsAssetsRetrieveParams) => {
  return [`/api/v2/project-views/${uid}/assets/`, ...(params ? [params] : [])] as const
}

export const getProjectViewsAssetsRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>,
  TError = unknown,
>(
  uid: string,
  params?: ProjectViewsAssetsRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getProjectViewsAssetsRetrieveQueryKey(uid, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>> = ({ signal }) =>
    projectViewsAssetsRetrieve(uid, params, { signal, ...fetchOptions })

  return { queryKey, queryFn, enabled: !!uid, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> }
}

export type ProjectViewsAssetsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>>
export type ProjectViewsAssetsRetrieveQueryError = unknown

export function useProjectViewsAssetsRetrieve<
  TData = Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>,
  TError = unknown,
>(
  uid: string,
  params: undefined | ProjectViewsAssetsRetrieveParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useProjectViewsAssetsRetrieve<
  TData = Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>,
  TError = unknown,
>(
  uid: string,
  params?: ProjectViewsAssetsRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useProjectViewsAssetsRetrieve<
  TData = Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>,
  TError = unknown,
>(
  uid: string,
  params?: ProjectViewsAssetsRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useProjectViewsAssetsRetrieve<
  TData = Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>,
  TError = unknown,
>(
  uid: string,
  params?: ProjectViewsAssetsRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsAssetsRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getProjectViewsAssetsRetrieveQueryOptions(uid, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

export type projectViewsUsersRetrieveResponse200 = {
  data: ProjectView
  status: 200
}

export type projectViewsUsersRetrieveResponseComposite = projectViewsUsersRetrieveResponse200

export type projectViewsUsersRetrieveResponse = projectViewsUsersRetrieveResponseComposite & {
  headers: Headers
}

export const getProjectViewsUsersRetrieveUrl = (uid: string, params?: ProjectViewsUsersRetrieveParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v2/project-views/${uid}/users/?${stringifiedParams}`
    : `/api/v2/project-views/${uid}/users/`
}

export const projectViewsUsersRetrieve = async (
  uid: string,
  params?: ProjectViewsUsersRetrieveParams,
  options?: RequestInit,
): Promise<projectViewsUsersRetrieveResponse> => {
  const res = await fetch(getProjectViewsUsersRetrieveUrl(uid, params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: projectViewsUsersRetrieveResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as projectViewsUsersRetrieveResponse
}

export const getProjectViewsUsersRetrieveQueryKey = (uid: string, params?: ProjectViewsUsersRetrieveParams) => {
  return [`/api/v2/project-views/${uid}/users/`, ...(params ? [params] : [])] as const
}

export const getProjectViewsUsersRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof projectViewsUsersRetrieve>>,
  TError = unknown,
>(
  uid: string,
  params?: ProjectViewsUsersRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsUsersRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getProjectViewsUsersRetrieveQueryKey(uid, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof projectViewsUsersRetrieve>>> = ({ signal }) =>
    projectViewsUsersRetrieve(uid, params, { signal, ...fetchOptions })

  return { queryKey, queryFn, enabled: !!uid, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof projectViewsUsersRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> }
}

export type ProjectViewsUsersRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof projectViewsUsersRetrieve>>>
export type ProjectViewsUsersRetrieveQueryError = unknown

export function useProjectViewsUsersRetrieve<
  TData = Awaited<ReturnType<typeof projectViewsUsersRetrieve>>,
  TError = unknown,
>(
  uid: string,
  params: undefined | ProjectViewsUsersRetrieveParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsUsersRetrieve>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectViewsUsersRetrieve>>,
          TError,
          Awaited<ReturnType<typeof projectViewsUsersRetrieve>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useProjectViewsUsersRetrieve<
  TData = Awaited<ReturnType<typeof projectViewsUsersRetrieve>>,
  TError = unknown,
>(
  uid: string,
  params?: ProjectViewsUsersRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsUsersRetrieve>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectViewsUsersRetrieve>>,
          TError,
          Awaited<ReturnType<typeof projectViewsUsersRetrieve>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useProjectViewsUsersRetrieve<
  TData = Awaited<ReturnType<typeof projectViewsUsersRetrieve>>,
  TError = unknown,
>(
  uid: string,
  params?: ProjectViewsUsersRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsUsersRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useProjectViewsUsersRetrieve<
  TData = Awaited<ReturnType<typeof projectViewsUsersRetrieve>>,
  TError = unknown,
>(
  uid: string,
  params?: ProjectViewsUsersRetrieveParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof projectViewsUsersRetrieve>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getProjectViewsUsersRetrieveQueryOptions(uid, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

export const getApiV2ProjectViewsListResponseMock = (
  overrideResponse: Partial<PaginatedProjectViewList> = {},
): PaginatedProjectViewList => ({
  count: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  next: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
  previous: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
  results: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    uid: faker.string.alpha({ length: { min: 10, max: 23 } }),
    name: faker.string.alpha({ length: { min: 10, max: 200 } }),
    url: faker.string.alpha({ length: { min: 10, max: 20 } }),
    assets: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})),
    assets_export: faker.string.alpha({ length: { min: 10, max: 20 } }),
    users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
      faker.string.alpha({ length: { min: 10, max: 20 } }),
    ),
    users_export: faker.string.alpha({ length: { min: 10, max: 20 } }),
    countries: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
      faker.string.alpha({ length: { min: 10, max: 20 } }),
    ),
    permissions: faker.helpers.arrayElement([faker.helpers.arrayElements(Object.values(PermissionsEnum)), undefined]),
    assigned_users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
      faker.string.alpha({ length: { min: 10, max: 20 } }),
    ),
  })),
  ...overrideResponse,
})

export const getApiV2ProjectViewsRetrieveResponseMock = (overrideResponse: Partial<ProjectView> = {}): ProjectView => ({
  uid: faker.string.alpha({ length: { min: 10, max: 23 } }),
  name: faker.string.alpha({ length: { min: 10, max: 200 } }),
  url: faker.string.alpha({ length: { min: 10, max: 20 } }),
  assets: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})),
  assets_export: faker.string.alpha({ length: { min: 10, max: 20 } }),
  users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  users_export: faker.string.alpha({ length: { min: 10, max: 20 } }),
  countries: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  permissions: faker.helpers.arrayElement([faker.helpers.arrayElements(Object.values(PermissionsEnum)), undefined]),
  assigned_users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  ...overrideResponse,
})

export const getApiV2ProjectViewsExportRetrieveResponseMock = (
  overrideResponse: Partial<ProjectView> = {},
): ProjectView => ({
  uid: faker.string.alpha({ length: { min: 10, max: 23 } }),
  name: faker.string.alpha({ length: { min: 10, max: 200 } }),
  url: faker.string.alpha({ length: { min: 10, max: 20 } }),
  assets: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})),
  assets_export: faker.string.alpha({ length: { min: 10, max: 20 } }),
  users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  users_export: faker.string.alpha({ length: { min: 10, max: 20 } }),
  countries: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  permissions: faker.helpers.arrayElement([faker.helpers.arrayElements(Object.values(PermissionsEnum)), undefined]),
  assigned_users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  ...overrideResponse,
})

export const getApiV2ProjectViewsExportCreateResponseMock = (
  overrideResponse: Partial<ProjectView> = {},
): ProjectView => ({
  uid: faker.string.alpha({ length: { min: 10, max: 23 } }),
  name: faker.string.alpha({ length: { min: 10, max: 200 } }),
  url: faker.string.alpha({ length: { min: 10, max: 20 } }),
  assets: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})),
  assets_export: faker.string.alpha({ length: { min: 10, max: 20 } }),
  users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  users_export: faker.string.alpha({ length: { min: 10, max: 20 } }),
  countries: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  permissions: faker.helpers.arrayElement([faker.helpers.arrayElements(Object.values(PermissionsEnum)), undefined]),
  assigned_users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  ...overrideResponse,
})

export const getApiV2ProjectViewsAssetsRetrieveResponseMock = (
  overrideResponse: Partial<ProjectView> = {},
): ProjectView => ({
  uid: faker.string.alpha({ length: { min: 10, max: 23 } }),
  name: faker.string.alpha({ length: { min: 10, max: 200 } }),
  url: faker.string.alpha({ length: { min: 10, max: 20 } }),
  assets: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})),
  assets_export: faker.string.alpha({ length: { min: 10, max: 20 } }),
  users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  users_export: faker.string.alpha({ length: { min: 10, max: 20 } }),
  countries: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  permissions: faker.helpers.arrayElement([faker.helpers.arrayElements(Object.values(PermissionsEnum)), undefined]),
  assigned_users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  ...overrideResponse,
})

export const getApiV2ProjectViewsUsersRetrieveResponseMock = (
  overrideResponse: Partial<ProjectView> = {},
): ProjectView => ({
  uid: faker.string.alpha({ length: { min: 10, max: 23 } }),
  name: faker.string.alpha({ length: { min: 10, max: 200 } }),
  url: faker.string.alpha({ length: { min: 10, max: 20 } }),
  assets: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})),
  assets_export: faker.string.alpha({ length: { min: 10, max: 20 } }),
  users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  users_export: faker.string.alpha({ length: { min: 10, max: 20 } }),
  countries: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  permissions: faker.helpers.arrayElement([faker.helpers.arrayElements(Object.values(PermissionsEnum)), undefined]),
  assigned_users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
    faker.string.alpha({ length: { min: 10, max: 20 } }),
  ),
  ...overrideResponse,
})

export const getApiV2ProjectViewsListMockHandler = (
  overrideResponse?:
    | PaginatedProjectViewList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PaginatedProjectViewList> | PaginatedProjectViewList),
) => {
  return http.get('*/api/v2/project-views/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getApiV2ProjectViewsListResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getApiV2ProjectViewsRetrieveMockHandler = (
  overrideResponse?:
    | ProjectView
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ProjectView> | ProjectView),
) => {
  return http.get('*/api/v2/project-views/:uid/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getApiV2ProjectViewsRetrieveResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getApiV2ProjectViewsExportRetrieveMockHandler = (
  overrideResponse?:
    | ProjectView
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ProjectView> | ProjectView),
) => {
  return http.get('*/api/v2/project-views/:uid/:objType/export/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getApiV2ProjectViewsExportRetrieveResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getApiV2ProjectViewsExportCreateMockHandler = (
  overrideResponse?:
    | ProjectView
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ProjectView> | ProjectView),
) => {
  return http.post('*/api/v2/project-views/:uid/:objType/export/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getApiV2ProjectViewsExportCreateResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getApiV2ProjectViewsAssetsRetrieveMockHandler = (
  overrideResponse?:
    | ProjectView
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ProjectView> | ProjectView),
) => {
  return http.get('*/api/v2/project-views/:uid/assets/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getApiV2ProjectViewsAssetsRetrieveResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getApiV2ProjectViewsUsersRetrieveMockHandler = (
  overrideResponse?:
    | ProjectView
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ProjectView> | ProjectView),
) => {
  return http.get('*/api/v2/project-views/:uid/users/', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getApiV2ProjectViewsUsersRetrieveResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}
export const getProjectViewsMock = () => [
  getApiV2ProjectViewsListMockHandler(),
  getApiV2ProjectViewsRetrieveMockHandler(),
  getApiV2ProjectViewsExportRetrieveMockHandler(),
  getApiV2ProjectViewsExportCreateMockHandler(),
  getApiV2ProjectViewsAssetsRetrieveMockHandler(),
  getApiV2ProjectViewsUsersRetrieveMockHandler(),
]
