name: 'Checkout with Github App token'
description: 'Checkout repo with a Github App token and set bot config, so that push to the repo would trigger workflows.'

inputs:
  app-id:
    required: true
  private-key:
    required: true

runs:
  using: "composite"
  steps:

  - name: Generate a token to trigger a workflow from a workflow
    id: app-token
    uses: actions/create-github-app-token@v2
    with:
      app-id: ${{ inputs.app-id }}
      private-key: ${{ inputs.private-key }}

  - name: Get GitHub App user id
    id: get-user-id
    shell: bash
    run: |
      echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"

  - name: Set git name and email for the bot
    shell: bash
    run: |
      git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
      git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

  - uses: actions/checkout@v5
    with:
      token: ${{ steps.app-token.outputs.token }}
      fetch-depth: "0"
