import React, { useState } from 'react'

import { Group, Modal, Stack, Text } from '@mantine/core'
import { Box, ThemeIcon } from '@mantine/core'
import { useDisclosure } from '@mantine/hooks'
import ActionIcon from '#/components/common/ActionIcon'
import ButtonNew from '#/components/common/ButtonNew'
import Icon from '#/components/common/icon'

import type { ResponseManualQualActionParams } from '#/api/models/responseManualQualActionParams'
import { FeatureFlag, useFeatureFlag } from '#/featureFlags'
import { getQuestionTypeDefinition } from '../../../common/utils'

interface Props {
  children?: React.ReactNode
  qaQuestion: ResponseManualQualActionParams
  // This is optional because some types are not clearable
  onClear?: () => Promise<void>
  disabled: boolean
  onEdit: (qaQuestion: ResponseManualQualActionParams) => unknown
  onDelete: (qaQuestion: ResponseManualQualActionParams) => Promise<unknown>
  /**
   * Adds a Generate with AI button. API handling is being served by parent(s), as this component doesn't have all
   * the required data and it's easier to push this one function up than all the small pieces down.
   */
  onGenerateWithAI?: () => Promise<unknown>
  /**
   * Whether to show "AI generated" badge. Use it when response was generated by AI.
   */
  isGeneratedWithAI?: boolean
  hasResponse: boolean
}

/**
 * Displays question type icon, name, and an edit and delete buttons (if user
 * has sufficient permissions). Is being used in multiple other components.
 */
export default function ResponseForm({
  qaQuestion,
  children,
  onClear,
  disabled,
  onEdit,
  onDelete,
  onGenerateWithAI,
  isGeneratedWithAI,
  hasResponse,
}: Props) {
  const [opened, { open, close }] = useDisclosure(false)
  const [isGenerating, setIsGenerating] = useState(false)

  const ffAutoQAEnabled = useFeatureFlag(FeatureFlag.autoQAEnabled)

  // Get the question definition (with safety check)
  const qaQuestionDef = getQuestionTypeDefinition(qaQuestion.type)
  if (!qaQuestionDef) {
    return null
  }

  const handleEdit = () => {
    onEdit(qaQuestion)
  }

  const handleDelete = async () => {
    await onDelete(qaQuestion)
    close()
  }

  const handleGenerateWithAI = async () => {
    if (!onGenerateWithAI) return
    setIsGenerating(true)
    try {
      await onGenerateWithAI()
    } finally {
      setIsGenerating(false)
    }
  }

  const handleClear = async () => {
    if (!onClear) return
    await onClear()
  }

  return (
    <Stack gap='10px'>
      <Group align={'flex-start'} gap={'xs'}>
        {!disabled && (
          <Modal opened={opened} onClose={close} title={t('Delete this question?')} size={'md'}>
            <Stack gap='24px'>
              <Text>{t('Are you sure you want to delete this question? This action cannot be undone.')}</Text>
              <Group align='left'>
                <ButtonNew size='md' onClick={close} variant='light'>
                  {t('Cancel')}
                </ButtonNew>

                <ButtonNew size='md' onClick={handleDelete} variant='danger'>
                  {t('Delete')}
                </ButtonNew>
              </Group>
            </Stack>
          </Modal>
        )}

        <ThemeIcon ta={'center'} variant='light-teal'>
          <Icon name={qaQuestionDef.icon} size='xl' />
        </ThemeIcon>

        {/*TODO: font weight is not standardized DEV-1238*/}
        <Text
          style={{ wordBreak: 'break-all' }}
          span
          c={'gray.2'}
          fw={600}
          fz={'lg'}
          flex={1}
          mih={32}
          display={'flex'}
          ta={'left'}
        >
          {qaQuestion.labels._default}
        </Text>
        {!disabled && (
          <>
            <ActionIcon
              variant='light'
              size='sm'
              iconName='edit'
              onClick={handleEdit}
              // We only allow editing one question at a time, so adding new is not
              // possible until user stops editing
              disabled={disabled}
            />

            <ActionIcon variant='danger-secondary' size='sm' iconName='trash' onClick={open} disabled={disabled} />
          </>
        )}
      </Group>

      {/* Hard coded left padding to account for the 32px icon size + 8px gap */}
      {children && <Box pl='40px'>{children}</Box>}

      {/*
       * If there is an answer, we display "Clear" button and optionally AI info.
       * If no answer, we display "Generate with AI" button (for not all question types)
       */}
      {ffAutoQAEnabled && (
        <Group pl='40px'>
          {!hasResponse && !isGeneratedWithAI && onGenerateWithAI && (
            <Group>
              <ButtonNew
                variant='transparent'
                h='fit-content'
                size='md'
                p={0}
                disabled={disabled}
                c='var(--mantine-color-blue-5)'
                leftIcon='sparkles'
                onClick={handleGenerateWithAI}
                loading={isGenerating}
                loaderProps={{ type: 'dots' }}
              >
                {t('Generate with AI')}
              </ButtonNew>
            </Group>
          )}

          {hasResponse && (
            <Group style={{ justifyContent: 'space-between' }} w='100%'>
              <ButtonNew
                variant='transparent'
                h='fit-content'
                size='md'
                p={0}
                disabled={disabled}
                c='var(--mantine-color-red-5)'
                leftIcon='close'
                onClick={handleClear}
                loaderProps={{ type: 'dots' }}
              >
                {t('Clear')}
              </ButtonNew>

              {isGeneratedWithAI && (
                <Group pl='40px' c='var(--mantine-color-blue-5)' gap='xs'>
                  <Icon name='sparkles' size='m' />
                  <Text>{t('AI generated')}</Text>
                </Group>
              )}
            </Group>
          )}
        </Group>
      )}
    </Stack>
  )
}
