# Generated by Django 3.2.15 on 2023-09-05 21:22

from django.db import migrations, models
import django.db.models.deletion
import kobo.apps.stripe.models
import kpi.fields.kpi_uid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0011_2_7'),
        ('organizations', '0001_squashed_0004_remove_organization_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAddOn',
            fields=[
                ('usage_limits', models.JSONField(default=kobo.apps.stripe.models.get_default_add_on_limits, help_text='The historical usage limits, when the add-on was purchased.')),
                ('limits_used', models.JSONField(default=kobo.apps.stripe.models.get_default_add_on_limits, help_text="The amount of each of the add-on's individual limits that has been used.")),
                ('created', models.DateTimeField()),
                ('id', kpi.fields.kpi_uid.KpiUidField(_null=False, primary_key=True, uid_prefix='addon_')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djstripe.paymentintent', to_field='id')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.product', to_field='id')),
            ],
            options={
                'verbose_name': 'plan add-on',
                'verbose_name_plural': 'plan add-ons',
            },
        ),
    ]
