# Generated by Django 3.2.15 on 2023-11-10 14:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import kobo.apps.stripe.utils
import kpi.fields.kpi_uid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0011_2_7'),
        ('organizations', '0001_squashed_0004_remove_organization_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAddOn',
            fields=[
                (
                    'id',
                    kpi.fields.kpi_uid.KpiUidField(
                        _null=False, primary_key=True, uid_prefix='addon_'
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        help_text='The time when the add-on purchased.'
                    ),
                ),
                (
                    'quantity',
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    'usage_limits',
                    models.JSONField(
                        default=kobo.apps.stripe.utils.get_default_add_on_limits,
                        help_text='The historical usage limits when the add-on was '
                        'purchased.\n        Multiply this value by `quantity` to get '
                        'the total limits for this add-on. Possible keys:\n'
                        '"submission_limit", "asr_seconds_limit", and/or'
                        '"mt_characters_limit"',
                    ),
                ),
                (
                    'limits_remaining',
                    models.JSONField(
                        default=kobo.apps.stripe.utils.get_default_add_on_limits,
                        help_text="The amount of each of the add-on's individual "
                        'limits left to use."',
                    ),
                ),
                (
                    'charge',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='djstripe.charge',
                        to_field='id',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='organizations.organization',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='djstripe.product',
                        to_field='id',
                    ),
                ),
            ],
            options={
                'verbose_name': 'plan add-on',
                'verbose_name_plural': 'plan add-ons',
            },
        ),
        migrations.AddIndex(
            model_name='planaddon',
            index=models.Index(
                fields=['organization', 'limits_remaining', 'charge'],
                name='stripe_plan_organiz_b3d2e4_idx',
            ),
        ),
    ]
