# Generated by Django 4.2.15 on 2025-02-04 21:15

from django.db import migrations, models
from kobo.apps.stripe.utils.subscription_limits import get_default_add_on_limits


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planaddon',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='planaddon',
            name='limits_remaining',
            field=models.JSONField(
                default=get_default_add_on_limits,
                help_text=(
                    "The amount of each of the add-on's individual limits "
                    'left to use.'
                ),
            ),
        ),
        migrations.AlterField(
            model_name='planaddon',
            name='usage_limits',
            field=models.JSONField(
                default=get_default_add_on_limits,
                help_text=(
                    'The historical usage limits when the add-on was purchased.\n'
                    'Possible keys:\n'
                    '"submission_limit", "asr_seconds_limit", '
                    'and/or "mt_characters_limit"'
                ),
            ),
        ),
    ]
