# Generated by Django 4.2.24 on 2026-01-09 15:02

from django.db import migrations, models
import kobo.apps.stripe.utils.subscription_limits


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0003_add_exceededlimitcounter_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceededlimitcounter',
            name='limit_type',
            field=models.CharField(
                choices=[
                    ('submission', 'Submission'),
                    ('storage_bytes', 'Storage Bytes'),
                    ('mt_characters', 'Mt Characters'),
                    ('asr_seconds', 'Asr Seconds'),
                    ('llm_requests', 'Llm Requests'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='planaddon',
            name='usage_limits',
            field=models.JSONField(
                default=kobo.apps.stripe.utils.subscription_limits.get_default_add_on_limits,
                help_text='The historical usage limits when the add-on was purchased.\n        Possible keys:\n        "submission_limit", "asr_seconds_limit", and/or "mt_characters_limit"',
            ),
        ),
    ]
