# path filters used by the workflow/ci.yml to decide which tests should run

# if any file changed matches any of the filters in a list, the output for that
# list is set to the string 'true'.

npm-test:
  - '{jsapp,test,webpack,static,scripts}/**/*.!(md|py|sh|bash)'   # frontend
  - '{package*.json,patches/*.patch,scripts/copy_fonts.py}'       # npm + postinstall
  - '{tsconfig.json,.swcrc,.babelrc*,.browserslistrc}'            # compilers
  - '{.editorconfig,.prettier*,.stylelint*,.eslint*,coffeelint*}' # linters
  - '.gitignore'                                                  # (can affect tools)
  - '.github/workflows/npm-test.yml'                              # ci

pytest:
  - '{kpi,kobo,hub}/**/*.!(md)'    # backend
  - 'dependencies/**/*.!(md)'      # pip
  - 'pyproject.toml'               # (can affect build/tests)
  - '.github/workflows/pytest.yml' # ci

darker:
  - '{kpi,kobo,hub}/**/*.py'        # .py
  - 'pyproject.toml'                # rules
  - '.github/workflows/darker.yml'  # ci

unknown: # return 'true' if a file was added but not listed here yet
  - '!(((\.github|\.storybook|\.tx|cypress|dependencies|docker|hub|jsapp|kobo|kpi|patches|scripts|static|test|webpack)/**)|(\.babelrc\.json|\.browserslistrc|\.coveragerc|\.dockerignore|\.editorconfig|\.eslintignore|\.eslintrc\.js|\.git-blame-ignore-revs|\.gitattributes|\.gitignore|\.gitlab-ci\.yml|\.gitmodules|\.node-version|\.nvmrc|\.prettierrc\.js|\.stylelintrc\.js|\.swcrc|CONTRIBUTING\.md|Dockerfile|LICENSE|README\.md|coffeelint\.json|dependabot\.yml|format-python\.sh|kpi\.code-workspace|locale|manage\.py|package-lock\.json|package\.json|pip-compile\.sh|pyproject\.toml|tsconfig\.json))'
