# Used by workflows

npm-test:
  - '{jsapp,test,webpack,static,scripts}/**/*.!(md|py|sh|bash)'   # frontend
  - '{package*.json,patches/*.patch,scripts/copy_fonts.py}'       # npm + postinstall
  - '{tsconfig.json,.swcrc,.babelrc*,.browserslistrc}'            # compilers
  - '{.editorconfig,.prettier*,.stylelint*,.eslint*,coffeelint*}' # linters
  - '{.gitignore}'                                                # (can affect tools)

  # WIP - re-enable when done tweaking workflow logic.
  #   In the future we should re-run test whenever the ci logic is modified.
  #   but during this PR draft, I want to test if the logic would result
  #   in a skip if the rule was already established
  # - '.github/workflows/npm-test.yml'                              # ci

pytest:
  - '{kpi,kobo,hub}/**/*.!(md)'    # backend
  - 'dependencies/**/*.!(md)'      # pip
  - 'pyproject.toml'               # (can affect build/tests)

  # WIP
  # - '.github/workflows/pytest.yml' # ci

darker:
  - '{kpi,kobo,hub}/**/*.py'        # .py
  - 'pyproject.toml'                # rules

  # WIP
  # - '.github/workflows/darker.yml'  # ci

unknown:
  # New and unrecognized files can affect CI test results.
  #  - We usually want to err on the side of running tests
  #    instead of skipping them.
  #  - This filter is basically an inverted 'ignore' list of paths
  #    we know about already.
  #  - Add new entries into this list once they're accounted for
  #    in the other lists.
  #      (alphabetical order, folders-first)
  - '!(((\.github|\.storybook|\.tx|cypress|dependencies|docker|hub|jsapp|kobo|kpi|patches|scripts|static|test|webpack)/**)|(\.babelrc\.json|\.browserslistrc|\.coveragerc|\.dockerignore|\.editorconfig|\.eslintignore|\.eslintrc\.js|\.git-blame-ignore-revs|\.gitattributes|\.gitignore|\.gitlab-ci\.yml|\.gitmodules|\.node-version|\.nvmrc|\.prettierrc\.js|\.stylelintrc\.js|\.swcrc|CONTRIBUTING\.md|Dockerfile|LICENSE|README\.md|coffeelint\.json|dependabot\.yml|format-python\.sh|kpi\.code-workspace|locale|manage\.py|package-lock\.json|package\.json|pip-compile\.sh|pyproject\.toml|tsconfig\.json))'


# Notes:

# Filter syntax is picomatch v4 with {dot:true}. A few quirks:
# - '*' and '**' always act as glob matchers, even in groups
# - in groups (parens), you need to escape '.' with (\.)


# Clarifying question for making these:
#
# > "If a new PR is opened,
# >  and it only changes 1 file, which test(s) should be re-run?"
