# Generated by Django 5.2.14 on 2026-09-21 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import kpi.models.abstract_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentRestoreJob',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'date_created',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'date_modified',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                ('asset_uid', models.CharField(max_length=32, verbose_name='project')),
                (
                    'dry_run',
                    models.BooleanField(
                        default=True,
                        help_text=(
                            'Report what would be restored, without writing anything. '
                            'Turn this off to actually restore the files.'
                        ),
                    ),
                ),
                (
                    'resume',
                    models.BooleanField(
                        default=True,
                        help_text=(
                            'Pick up where an interrupted run stopped, rather than '
                            'walking the project from its most recent attachment again.'
                        ),
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('in_progress', 'In Progress'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('scanned', models.PositiveIntegerField(default=0)),
                ('restored', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True, default='')),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Attachment restore',
                'verbose_name_plural': 'Attachment restores',
            },
        ),
    ]
