AWS_ACCOUNT = 311934536039
PIPELINE_VERSION = "1.0.0"
GIT_COMMIT := $(shell git rev-parse HEAD 2>/dev/null | cut -c 1-7)
APP_VERSION= 0.0.1
IMAGE_TAG := $(shell echo "${APP_VERSION}-${GIT_COMMIT}")
HELM_DIR=helm-chart