# Dev scripts 
# Not intended to merge to main, delete before merging.
tasks:
  mk:
    desc: Build the task-Dockerfile image + Run bash in it
    cmds:
     - task: mk-dc
     - task: mk-bash

  mk-dc:
    desc: Build the test image
    cmd: '{{.COMPOSE}} build {{.SERVICE}}'
    dir:  .

  mk-bash: 
    desc: Run 'bash' in the container (to check on stuff)
    cmd: '{{.COMPOSE}} run --rm {{.BASH_ENV}} {{.SERVICE}} bash'
    ignore_error: true
    dir:  .


  # Previous versions

  mk-node-2:
    desc: Build and run the task-node-2-Dockerfile
    cmds:
     - { task: mk-dc,   vars: { SERVICE: mk-node-2 } }
     - { task: mk-bash, vars: { SERVICE: mk-node-2 } }


  mk-node:
    desc: Build and run the task-node-Dockerfile
    cmds:
     - { task: mk-dc,   vars: { SERVICE: mk-node } }
     - { task: mk-bash, vars: { SERVICE: mk-node } }


vars: {
  COMPOSE: 'docker compose --file task-compose.yml ',
  SERVICE: 'mk',

  BASH_ENV: ' -e TERM=xterm-256color ',
}

# Optionally include other taskfile commands from higher workspace
includes: { other: { taskfile: ../taskfile.yml, optional: true, flatten: true } }
version: '3'