# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-18 19:27
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0004_add_payload_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hook',
            name='subset_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True,
                                                            default=list, size=None),
        ),
    ]
