# Generated by Django 2.2.7 on 2021-12-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('hook', '0006_auto_20211202_2331'), ('hook', '0007_auto_20211202_2335'), ('hook', '0008_hook_veritree_type'), ('hook', '0009_auto_20211217_1816')]

    dependencies = [
        ('hook', '0005_allow_blank_subset_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hook',
            name='auth_level',
            field=models.CharField(choices=[('no_auth', 'no_auth'), ('basic_auth', 'basic_auth'), ('veritree_auth', 'veritree_auth')], default='no_auth', max_length=10),
        ),
        migrations.AlterField(
            model_name='hook',
            name='auth_level',
            field=models.CharField(choices=[('no_auth', 'no_auth'), ('basic_auth', 'basic_auth'), ('veritree_auth', 'veritree_auth')], default='no_auth', max_length=13),
        ),
        migrations.AddField(
            model_name='hook',
            name='veritree_type',
            field=models.CharField(choices=[('none', 'none'), ('form_metadata', 'form_metadata'), ('field_update', 'field_update')], default='none', max_length=20),
        ),
    ]
