# Generated by Django 2.2.7 on 2019-11-19 08:34

from django.db import migrations, models
import kpi.fields.kpi_uid


class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0005_allow_blank_subset_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hook',
            name='auth_level',
            field=models.CharField(choices=[('no_auth', 'no_auth'), ('basic_auth', 'basic_auth')], default='no_auth', max_length=10),
        ),
        migrations.AlterField(
            model_name='hook',
            name='export_type',
            field=models.CharField(choices=[('xml', 'xml'), ('json', 'json')], default='json', max_length=10),
        ),
        migrations.AlterField(
            model_name='hook',
            name='uid',
            field=kpi.fields.kpi_uid.KpiUidField(uid_prefix='h'),
        ),
        migrations.AlterField(
            model_name='hooklog',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hooklog',
            name='uid',
            field=kpi.fields.kpi_uid.KpiUidField(uid_prefix='hl'),
        ),
    ]
