# Generated by Django 3.2.15 on 2024-01-17 12:38

from django.db import migrations, models


ON_EVENT = {
    "onEdit": False,
    "onDelete": False,
    "onSubmit": True,
    "onValidation": False
}

class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0007_do_nothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='on_event',
            field=models.JSONField(default=ON_EVENT),
        ),
        migrations.AddField(
            model_name='hooklog',
            name='event',
            field=models.CharField(max_length=50, default='on_submit'),
        ),
    ]
