import type { Decorator } from '@storybook/react'
import type { Meta, StoryObj } from '@storybook/react-webpack5'
import RegisterAside from './RegisterAside'

/**
 * The registration screen's supporting column on its own
 */

/** Inline so the story stays offline */
const EXAMPLE_IMAGE_URL = `data:image/svg+xml,${encodeURIComponent(
  [
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 120">',
    '<rect width="240" height="120" rx="8" fill="#e3f2fd"/>',
    '<text x="120" y="80" text-anchor="middle" font-family="sans-serif" font-size="44" fill="#135991">',
    '૮ ˙Ⱉ˙ ა',
    '</text></svg>',
  ].join('\n'),
)}`

/**
 * A heading, a list and a link - as if generated by markdownify.
 */
const EXAMPLE_TEXT = [
  '<h2>Welcome to the Early Cretaceous server</h2>',
  '<p>Accounts here are for <strong>phds and doctors</strong>. Please use your scientific address.</p>',
  '<ul>\n<li>Ask your country focal point for access</li>\n<li>Data stays on our own infrastructure</li>\n</ul>',
  '<p>Questions? <a href="https://example.org/support">Contact support</a>.</p>',
].join('\n')

/** Roughly the width the column gets inside the card */
const columnDecorator: Decorator = (Story) => (
  <main style={{ maxWidth: 360, padding: 24 }}>
    <Story />
  </main>
)

const meta: Meta<typeof RegisterAside> = {
  title: 'Features/RegisterAside',
  component: RegisterAside,
  decorators: [columnDecorator],
  parameters: {
    // Only one rule is failing.
    // TODO fix our anchor styles
    a11y: { config: { rules: [{ id: 'color-contrast', enabled: false }] } },
  },
}

export default meta
type Story = StoryObj<typeof RegisterAside>

export const TextAndImage: Story = {
  args: { imageUrl: EXAMPLE_IMAGE_URL, text: EXAMPLE_TEXT },
}

export const TextOnly: Story = {
  args: { imageUrl: null, text: EXAMPLE_TEXT },
}

export const ImageOnly: Story = {
  args: { imageUrl: EXAMPLE_IMAGE_URL, text: '' },
}
