from kobo.apps.organizations.constants import (
    ORG_ADMIN_ROLE,
    ORG_MEMBER_ROLE,
    ORG_OWNER_ROLE,
)

ROLE_CHOICES_ENUM = [
    (ORG_ADMIN_ROLE, ORG_ADMIN_ROLE),
    (ORG_MEMBER_ROLE, ORG_MEMBER_ROLE),
    (ORG_OWNER_ROLE, ORG_OWNER_ROLE),
]

ROLE_CHOICES_PAYLOAD_ENUM = [
    (ORG_ADMIN_ROLE, ORG_ADMIN_ROLE),
    (ORG_MEMBER_ROLE, ORG_MEMBER_ROLE),
]
