import * as TablerIcons from '@tabler/icons-react'
import type { IconProps as SvgIconProps, TablerIcon } from '@tabler/icons-react'
import type { ComponentType } from 'react'
import type { IconName } from '#/k-icons'
import { resolveLegacySvgIconByName } from './IconLegacySvgMappings'

const tablerIconEntries = Object.entries(TablerIcons).filter(
  (entry): entry is [string, TablerIcon] =>
    entry[0].startsWith('Icon') &&
    (typeof entry[1] === 'function' || (typeof entry[1] === 'object' && entry[1] !== null)),
)

const tablerIconToNameMap = new Map<TablerIcon, string>(
  tablerIconEntries.map(([exportName, icon]) => [icon, exportName]),
)

export const LegacyIconToTablerIconMap: Record<IconName, TablerIcon | undefined> = {
  alert: TablerIcons.IconAlertCircleFilled,
  'angle-bar-left': TablerIcons.IconChevronLeftPipe,
  'angle-bar-right': TablerIcons.IconChevronRightPipe,
  'angle-down': TablerIcons.IconChevronDown,
  'angle-left': TablerIcons.IconChevronLeft,
  'angle-right': TablerIcons.IconChevronRight,
  'angle-up': TablerIcons.IconChevronUp,
  archived: TablerIcons.IconArchiveFilled,
  'arrow-down-left': TablerIcons.IconArrowDownLeft,
  'arrow-down-right': TablerIcons.IconArrowDownRight,
  'arrow-down': TablerIcons.IconArrowDown,
  'arrow-left': TablerIcons.IconArrowLeft,
  'arrow-right': TablerIcons.IconArrowRight,
  'arrow-up-left': TablerIcons.IconArrowUpLeft,
  'arrow-up-right': TablerIcons.IconArrowUpRight,
  'arrow-up': TablerIcons.IconArrowUp,
  attach: TablerIcons.IconPaperclip,
  block: undefined,
  'caret-down': TablerIcons.IconCaretDownFilled,
  'caret-left': TablerIcons.IconCaretLeftFilled,
  'caret-right': TablerIcons.IconCaretRightFilled,
  'caret-up': TablerIcons.IconCaretUpFilled,
  cascading: undefined,
  'check-circle': TablerIcons.IconCircleCheckFilled,
  check: TablerIcons.IconCheck,
  close: TablerIcons.IconX,
  'data-sync': undefined,
  deploy: undefined, // 'IconRocket' ??
  document: TablerIcons.IconFileDescriptionFilled,
  download: TablerIcons.IconDownload,
  drafts: undefined, // 'IconFilePencilFilled' ??
  'drag-handle': TablerIcons.IconGripVertical,
  duplicate: TablerIcons.IconFilesFilled,
  edit: TablerIcons.IconPencilFilled,
  editor: undefined,
  email: TablerIcons.IconMailFilled,
  'expand-arrow': undefined,
  'expand-list': undefined,
  expand: TablerIcons.IconArrowsMaximize,
  'file-audio': TablerIcons.IconFileMusic,
  'file-image': TablerIcons.IconPhoto,
  'file-video': TablerIcons.IconVideo,
  'file-xls': TablerIcons.IconFileTypeXls,
  'file-xml': TablerIcons.IconFileTypeXml,
  file: TablerIcons.IconFile,
  'filter-arrows': TablerIcons.IconCaretUpDownFilled,
  filter: TablerIcons.IconFilter2,
  flows: TablerIcons.IconSwitch3,
  folder: TablerIcons.IconFolder,
  'folder-in': undefined,
  'folder-out': undefined,
  'folder-plus': undefined,
  'folder-public': undefined,
  'folder-shared': undefined,
  'folder-subscribed': undefined,
  freeze: TablerIcons.IconTableColumn,
  gallery: TablerIcons.IconPhotoFilled,
  'globe-alt': undefined,
  'group-split': undefined,
  group: undefined,
  heatmap: undefined,
  help: TablerIcons.IconHelpFilled,
  'help-academy': TablerIcons.IconSchool,
  'help-articles': TablerIcons.IconHelpSquare,
  'help-forum': TablerIcons.IconMessages,
  hide: TablerIcons.IconEyeOff,
  information: TablerIcons.IconInfoCircleFilled,
  intercom: TablerIcons.IconBrandIntercom,
  kobo: undefined,
  'language-alt': TablerIcons.IconLanguage,
  'language-default': TablerIcons.IconWorldStar,
  'language-settings': TablerIcons.IconWorldCog,
  layer: TablerIcons.IconStack2,
  'library-public': undefined,
  library: undefined,
  link: TablerIcons.IconLink,
  lock: TablerIcons.IconLock,
  'lock-alt': TablerIcons.IconLockFilled,
  'logo-github': TablerIcons.IconBrandGithubFilled,
  'logo-instagram': TablerIcons.IconBrandInstagram,
  'logo-linkedin': TablerIcons.IconBrandLinkedinFilled,
  'logo-twitter': TablerIcons.IconBrandTwitterFilled,
  logout: TablerIcons.IconLogout,
  mail: TablerIcons.IconMailFilled,
  'map-view': TablerIcons.IconMapPinFilled,
  'media-files': undefined,
  menu: TablerIcons.IconMenu2,
  minus: TablerIcons.IconMinus,
  'more-vertical': TablerIcons.IconDotsVertical,
  more: TablerIcons.IconDots,
  notification: TablerIcons.IconBell,
  pause: TablerIcons.IconPlayerPauseFilled,
  pdf: TablerIcons.IconFileTypePdf,
  pins: TablerIcons.IconMapPins,
  play: TablerIcons.IconPlayerPlayFilled,
  plus: TablerIcons.IconPlus,
  print: TablerIcons.IconPrinter,
  'project-archived': undefined,
  'project-deployed': undefined,
  'project-draft': undefined,
  'project-locked': undefined,
  'project-overview': undefined,
  project: undefined,
  projects: undefined,
  'qt-acknowledge-lock': undefined,
  'qt-acknowledge': undefined,
  'qt-area-lock': undefined,
  'qt-area': undefined,
  'qt-audio-lock': undefined,
  'qt-audio': undefined,
  'qt-background-audio': undefined,
  'qt-barcode-lock': undefined,
  'qt-barcode': undefined,
  'qt-calculate-lock': undefined,
  'qt-calculate': undefined,
  'qt-date-lock': undefined,
  'qt-date-time-lock': undefined,
  'qt-date-time': undefined,
  'qt-date': undefined,
  'qt-decimal-lock': undefined,
  'qt-decimal': undefined,
  'qt-external-xml-lock': undefined,
  'qt-external-xml': undefined,
  'qt-file-lock': undefined,
  'qt-file': undefined,
  'qt-hidden-lock': undefined,
  'qt-hidden': undefined,
  'qt-line-lock': undefined,
  'qt-line': undefined,
  'qt-meta-default': undefined,
  'qt-note-lock': undefined,
  'qt-note': undefined,
  'qt-number-lock': undefined,
  'qt-number': undefined,
  'qt-photo-lock': undefined,
  'qt-photo': undefined,
  'qt-point-lock': undefined,
  'qt-point': undefined,
  'qt-question-matrix-lock': undefined,
  'qt-question-matrix': undefined,
  'qt-range-lock': undefined,
  'qt-range': undefined,
  'qt-ranking-lock': undefined,
  'qt-ranking': undefined,
  'qt-rating-lock': undefined,
  'qt-rating': undefined,
  'qt-select-many-from-file-lock': undefined,
  'qt-select-many-from-file': undefined,
  'qt-select-many-lock': undefined,
  'qt-select-many': undefined,
  'qt-select-one-from-file-lock': undefined,
  'qt-select-one-from-file': undefined,
  'qt-select-one-lock': undefined,
  'qt-select-one': undefined,
  'qt-text-lock': undefined,
  'qt-text': undefined,
  'qt-time-lock': undefined,
  'qt-time': undefined,
  'qt-video-lock': undefined,
  'qt-video': undefined,
  question: undefined,
  reload: TablerIcons.IconReload,
  replace: undefined,
  reports: undefined,
  search: TablerIcons.IconSearch,
  settings: TablerIcons.IconSettings,
  'skip-logic': undefined,
  'sort-ascending': undefined,
  'sort-default': undefined,
  'sort-descending': undefined,
  sparkles: TablerIcons.IconSparkles,
  spinner: TablerIcons.IconLoader2,
  spreadsheet: undefined,
  stop: TablerIcons.IconPlayerStopFilled,
  subscribe: undefined,
  table: TablerIcons.IconTable,
  tag: TablerIcons.IconTagFilled,
  'template-locked': undefined,
  template: undefined,
  trash: TablerIcons.IconTrash,
  unfreeze: TablerIcons.IconTableOff,
  unsubscribe: undefined,
  upload: TablerIcons.IconUpload,
  'user-share': TablerIcons.IconUserPlus,
  user: TablerIcons.IconUser,
  users: TablerIcons.IconUsers,
  'view-all': undefined,
  view: TablerIcons.IconEye,
  warning: TablerIcons.IconAlertTriangleFilled,
} satisfies Record<IconName, TablerIcon | undefined>

export function resolveIconByLegacyName(legacyIconName: IconName): TablerIcon | undefined {
  return LegacyIconToTablerIconMap[legacyIconName]
}

export function resolveIconComponentByLegacyName(legacyIconName: IconName): ComponentType<SvgIconProps> {
  const tablerIcon = resolveIconByLegacyName(legacyIconName)
  if (tablerIcon) {
    return tablerIcon
  }

  return resolveLegacySvgIconByName(legacyIconName)
}

export function getLegacyIconsCatalog() {
  return Object.entries(LegacyIconToTablerIconMap)
    .map(([legacyName, icon]) => ({
      legacyName: legacyName as IconName,
      tablerIconName: icon ? tablerIconToNameMap.get(icon) : undefined,
      icon,
    }))
    .sort((a, b) => a.legacyName.localeCompare(b.legacyName))
}
