# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_views', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectview',
            name='uid_organizations',
            field=models.TextField(default='*'),
        ),
    ]
