# Generated by Django 2.2.14 on 2021-03-03 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_optional_filename_to_metadata'),
    ]

    # This migration will rewrite all records in the DB.
    # It can take a while with lots of records
    operations = [
        migrations.AddField(
            model_name='metadata',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='metadata',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
