# Generated by Django 3.2.15 on 2023-07-10 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_drop_old_kpi_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='validated_password',
            field=models.BooleanField(default=True),
        ),
    ]
