# Generated by Django 4.2.15 on 2024-12-19 21:31

from django.core.files.storage import FileSystemStorage
from django.db import migrations

import kobo.apps.openrosa.apps.main.models.meta_data
import kpi.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_userprofile_submissions_suspended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='data_file',
            field=kpi.fields.file.ExtendedFileField(
                blank=True,
                max_length=380,
                null=True,
                storage=FileSystemStorage(),
                upload_to=kobo.apps.openrosa.apps.main.models.meta_data.upload_to,
            ),
        ),
    ]
