# Generated by Django 3.2.15 on 2023-02-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('project_trash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttrash',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AddField(
            model_name='projecttrash',
            name='periodic_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='projecttrash',
            name='asset',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trash', to='kpi.asset'),
        ),
        migrations.AlterField(
            model_name='projecttrash',
            name='status',
            field=models.CharField(choices=[('in_progress', 'IN_PROGRESS'), ('pending', 'PENDING'), ('failed', 'FAILED')], db_index=True, default='pending', max_length=11),
        ),
    ]
