# Generated by Django 3.2.15 on 2023-03-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_bin', '0002_drop_django_registration_old_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttrash',
            name='status',
            field=models.CharField(choices=[('in_progress', 'IN_PROGRESS'), ('pending', 'PENDING'), ('retry', 'RETRY'), ('failed', 'FAILED')], db_index=True, default='pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='projecttrash',
            name='status',
            field=models.CharField(choices=[('in_progress', 'IN_PROGRESS'), ('pending', 'PENDING'), ('retry', 'RETRY'), ('failed', 'FAILED')], db_index=True, default='pending', max_length=11),
        ),
    ]
