# Generated by Django 4.2.15 on 2025-03-28 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kpi.fields.kpi_uid
import kpi.models.abstract_models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trash_bin', '0003_alter_accounttrash_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentTrash',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'date_created',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'date_modified',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('in_progress', 'IN PROGRESS'),
                            ('pending', 'PENDING'),
                            ('retry', 'RETRY'),
                            ('failed', 'FAILED'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=11,
                    ),
                ),
                ('metadata', models.JSONField(default=dict)),
                ('empty_manually', models.BooleanField(default=False)),
                ('retain_placeholder', models.BooleanField(default=True)),
                ('uid', kpi.fields.kpi_uid.KpiUidField(_null=False, uid_prefix='attt')),
                (
                    'attachment_id',
                    models.IntegerField(db_index=True, default=0, unique=True),
                ),
                (
                    'periodic_task',
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='django_celery_beat.periodictask',
                    ),
                ),
                (
                    'request_author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'attachment',
                'abstract': False,
            },
        ),
    ]
