# Generated by Django 3.2.15 on 2023-04-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_integrations', '0001_add_allowed_cors_origin_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corsmodel',
            name='cors',
            field=models.CharField(
                help_text=(
                    'Must contain exactly the URI scheme and host, e.g.'
                    ' https://example.com. Include a port only if it is'
                    ' non-standard, e.g. https://example.com:1234. Do not'
                    ' include the default port for the scheme (80 for http, 443'
                    ' for https): browsers never send it in the `Origin`'
                    ' header, so it would never match.'
                ),
                max_length=255,
                verbose_name='allowed origin',
            ),
        ),
    ]
