# Generated by Django 4.2.11 on 2024-07-17 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subsequences', '0002_non_nullable_unique_together_asset_and_submission_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionextras',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submissionextras',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
