# Generated by Django 4.2.24 on 2025-11-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsequences', '0005_submissionsupplement_questionadvancedaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionadvancedaction',
            old_name='config',
            new_name='params',
        ),
    ]
