# Generated by Django 4.2.24 on 2026-01-05 20:08

from django.db import migrations, models

import kpi.fields.kpi_uid


class Migration(migrations.Migration):

    dependencies = [
        ('subsequences', '0006_rename_submissionextras_submissionsupplement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionadvancedfeature',
            name='action',
            field=models.CharField(
                choices=[
                    ('manual_transcription', 'Manual Transcription'),
                    ('manual_translation', 'Manual Translation'),
                    ('automatic_google_translation', 'Automatic Google Translation'),
                    (
                        'automatic_google_transcription',
                        'Automatic Google Transcription',
                    ),
                    ('manual_qual', 'Manual Qual'),
                    ('automatic_chained_qual', 'Automatic Chained Qual'),
                ],
                db_index=True,
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name='questionadvancedfeature',
            name='uid',
            field=kpi.fields.kpi_uid.KpiUidField(
                _null=False, primary_key=True, uid_prefix='qaf'
            ),
        ),
    ]
