# Generated by Django 5.2.13 on 2026-05-11 11:22

import django.db.models.deletion
import kpi.fields.kpi_uid
import kpi.fields.lazy_default_jsonb
import kpi.models.abstract_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsequences', '0009_update_automatic_qual'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsequenceBulkAction',
            fields=[
                (
                    'date_created',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'date_modified',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'uid',
                    kpi.fields.kpi_uid.KpiUidField(
                        _null=False, primary_key=True, uid_prefix='sba'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('in_progress', 'In Progress'),
                            ('complete', 'Complete'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                (
                    'action_id',
                    models.CharField(
                        choices=[
                            ('manual_transcription', 'Manual Transcription'),
                            ('manual_translation', 'Manual Translation'),
                            (
                                'automatic_google_translation',
                                'Automatic Google Translation',
                            ),
                            (
                                'automatic_google_transcription',
                                'Automatic Google Transcription',
                            ),
                            ('manual_qual', 'Manual Qual'),
                            ('automatic_bedrock_qual', 'Automatic Bedrock Qual'),
                        ],
                        db_index=True,
                        max_length=60,
                    ),
                ),
                ('question_xpath', models.CharField(max_length=2000)),
                (
                    'params',
                    kpi.fields.lazy_default_jsonb.LazyDefaultJSONBField(default=dict),
                ),
                ('created_by', models.CharField(db_index=True, max_length=150)),
                (
                    'asset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subsequence_bulk_actions',
                        to='kpi.asset',
                    ),
                ),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SubsequenceBulkActionItem',
            fields=[
                (
                    'date_created',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'date_modified',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'uid',
                    kpi.fields.kpi_uid.KpiUidField(
                        _null=False, primary_key=True, uid_prefix='sbai'
                    ),
                ),
                (
                    'submission_root_uuid',
                    models.CharField(db_index=True, max_length=249),
                ),
                (
                    'action_id',
                    models.CharField(
                        choices=[
                            ('manual_transcription', 'Manual Transcription'),
                            ('manual_translation', 'Manual Translation'),
                            (
                                'automatic_google_translation',
                                'Automatic Google Translation',
                            ),
                            (
                                'automatic_google_transcription',
                                'Automatic Google Transcription',
                            ),
                            ('manual_qual', 'Manual Qual'),
                            ('automatic_bedrock_qual', 'Automatic Bedrock Qual'),
                        ],
                        db_index=True,
                        max_length=60,
                    ),
                ),
                ('question_xpath', models.CharField(max_length=2000)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('in_progress', 'In Progress'),
                            ('complete', 'Complete'),
                            ('failed', 'Failed'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('hash', models.CharField(db_index=True, max_length=64)),
                (
                    'service_id',
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='subsequences.subsequencebulkaction',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('status__in', ['pending', 'in_progress'])),
                        fields=(
                            'action_id',
                            'submission_root_uuid',
                            'question_xpath',
                            'hash',
                        ),
                        name='uniq_active_bulk_job_item_per_submission_action',
                    )
                ],
            },
        ),
    ]
