# Generated by Django 5.2.13 on 2026-06-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsequences', '0013_add_failure_error_field_to_subsequencebulkactionitem'),
        ('subsequences', '0013_rename_google_region_us_to_global'),
    ]

    operations = [
    ]
