# Generated by Django 5.2.14 on 2026-10-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsequences', '0015_add_qa_tag_tracker_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsequencebulkaction',
            name='auto_accept',
            field=models.BooleanField(default=False),
        ),
    ]
