# Generated by Django 2.2.14 on 2022-02-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0021_fix_xform_unique_together_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AlterModelOptions(
            name='xform',
            options={'ordering': ('id_string',), 'permissions': (('report_xform', 'Can make submissions to the form'), ('transfer_xform', 'Can transfer form ownership.'), ('validate_xform', 'Can validate submissions'), ('delete_data_xform', 'Can delete submissions')), 'verbose_name': 'XForm', 'verbose_name_plural': 'XForms'},
        ),
    ]
