# Generated by Django 3.2.15 on 2023-03-02 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0026_add_pending_delete_to_xform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyxformsubmissioncounter',
            name='xform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_counters', to='logger.xform'),
        ),
        migrations.AlterField(
            model_name='monthlyxformsubmissioncounter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlyxformsubmissioncounter',
            name='xform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.xform'),
        ),
    ]
