# Generated by Django 4.2.15 on 2024-09-16 14:01

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import kobo.apps.openrosa.apps.logger.fields
import kobo.apps.openrosa.apps.logger.models.attachment
import kobo.apps.openrosa.apps.logger.models.xform
import kpi.deployment_backends.kc_access.storage
import kpi.fields.file
import kpi.models.abstract_models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0037_remove_xform_has_kpi_hooks_and_instance_posted_to_kpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInstance',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=kpi.models.abstract_models._get_default_datetime)),
                ('date_modified', models.DateTimeField(default=kpi.models.abstract_models._get_default_datetime)),
                ('json', jsonfield.fields.JSONField(default={})),
                ('xml', models.TextField()),
                ('xml_hash', models.CharField(db_index=True, default=None, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(default='submitted_via_web', max_length=20)),
                ('uuid', models.CharField(db_index=True, default='', max_length=249)),
                ('geom', django.contrib.gis.db.models.fields.GeometryCollectionField(null=True, srid=4326)),
                ('validation_status', jsonfield.fields.JSONField(default=None, null=True)),
                ('is_synced_with_mongo', kobo.apps.openrosa.apps.logger.fields.LazyDefaultBooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('survey_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logger.surveytype')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('xform', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logger.xform')),
            ],
            options={
                'verbose_name': 'historical instance',
                'verbose_name_plural': 'historical instances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
