# Generated by Django 4.2.15 on 2024-12-19 21:31

from django.conf import settings
from django.db import migrations
import kobo.apps.openrosa.apps.logger.models.attachment
import kobo.apps.openrosa.apps.logger.models.xform
import kpi.deployment_backends.kc_access.storage
import kpi.fields.file


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0039_populate_counters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='media_file',
            field=kpi.fields.file.ExtendedFileField(
                db_index=True,
                max_length=380,
                storage=kpi.deployment_backends.kc_access.storage.KobocatS3Boto3Storage(),
                upload_to=kobo.apps.openrosa.apps.logger.models.attachment.upload_to,
            ),
        ),
        migrations.AlterField(
            model_name='xform',
            name='xls',
            field=kpi.fields.file.ExtendedFileField(
                max_length=380,
                null=True,
                storage=kpi.deployment_backends.kc_access.storage.KobocatS3Boto3Storage(),
                upload_to=kobo.apps.openrosa.apps.logger.models.xform.upload_to,
            ),
        ),
    ]
