# Generated by Django 4.2.15 on 2025-03-06 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import kobo.apps.openrosa.apps.logger.models.attachment
import kobo.apps.openrosa.apps.logger.models.xform
import kpi.fields.file
from kpi.deployment_backends.kc_access.storage import KobocatFileSystemStorage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0041_add_root_uuid_field_to_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attachments',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='attachment',
            name='xform',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attachments',
                to='logger.xform',
            ),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='media_file',
            field=kpi.fields.file.ExtendedFileField(
                db_index=True,
                max_length=380,
                storage=KobocatFileSystemStorage(),
                upload_to=kobo.apps.openrosa.apps.logger.models.attachment.upload_to,
            ),
        ),
        migrations.AlterField(
            model_name='dailyxformsubmissioncounter',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='daily_counts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='xform',
            name='require_auth',
            field=models.BooleanField(
                default=True,
                verbose_name='Require authentication to see form and submit data',
            ),
        ),
        migrations.AlterField(
            model_name='xform',
            name='xls',
            field=kpi.fields.file.ExtendedFileField(
                max_length=380,
                null=True,
                storage=KobocatFileSystemStorage(),
                upload_to=kobo.apps.openrosa.apps.logger.models.xform.upload_to,
            ),
        ),
    ]
