# Generated by Django 4.2.15 on 2025-05-26 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0041_add_root_uuid_field_to_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
