# Generated by Django 4.2.15 on 2025-03-07 20:40

from django.db import migrations, models

import kpi.models.abstract_models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0042_attachment_user_attachment_xform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='date_created',
            field=models.DateTimeField(
                default=kpi.models.abstract_models._get_default_datetime
            ),
        ),
        migrations.AddField(
            model_name='attachment',
            name='date_modified',
            field=models.DateTimeField(
                default=kpi.models.abstract_models._get_default_datetime
            ),
        ),
    ]
