# flake8: noqa: E501
# Generated by Django 4.2.15 on 2025-07-02 18:46

from django.conf import settings
from django.db import migrations, models


def manually_create_indexes_instructions(apps, schema_editor):
    print(
        """
        ⚠️ ATTENTION ⚠️
        Run the SQL queries below in PostgreSQL directly:

            ```sql
            CREATE INDEX CONCURRENTLY "logger_instancehistory_uuid_f8441978" ON "logger_instancehistory" ("uuid");
            CREATE INDEX CONCURRENTLY "logger_instancehistory_uuid_f8441978_like" ON "logger_instancehistory" ("uuid" varchar_pattern_ops);
            ```

        """
    )


def manually_drop_indexes_instructions(apps, schema_editor):
    print(
        """
        ⚠️ ATTENTION ⚠️
        Run the SQL queries below in PostgreSQL directly:

            ```sql
            DROP INDEX CONCURRENTLY IF EXISTS "logger_instancehistory_uuid_f8441978";
            DROP INDEX CONCURRENTLY IF EXISTS "logger_instancehistory_uuid_f8441978_like";
            ```

        """
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0043_add_new_columns_to_attachment'),
    ]

    operations = [
        (
            migrations.RunPython(
                manually_create_indexes_instructions,
                manually_drop_indexes_instructions,
            )
            if settings.SKIP_HEAVY_MIGRATIONS
            else migrations.AlterField(
                model_name='instancehistory',
                name='uuid',
                field=models.CharField(db_index=True, default='', max_length=249),
            )
        )
    ]
