# Generated by Django 4.2.15 on 2025-03-13 14:37

from django.conf import settings
from django.db import migrations

import kpi.fields.kpi_uid


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0043_attachment_date_created_attachment_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='uid',
            field=kpi.fields.kpi_uid.KpiUidField(
                _null=True, null=True, uid_prefix='att'
            ),
        ),
    ]
