# Generated by Django 4.2.15 on 2025-03-13 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kobo.apps.openrosa.apps.logger.models.attachment
import kobo.apps.openrosa.apps.logger.models.xform
import kpi.deployment_backends.kc_access.storage
import kpi.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0044_attachment_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='delete_status',
            field=models.CharField(
                choices=[
                    ('deleted', 'Deleted'),
                    ('soft-deleted', 'Soft Deleted'),
                    ('pending-delete', 'Pending Delete'),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        )
    ]
