# Generated by Django 4.2.15 on 2025-07-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0044_add_index_to_instance_history_uuid'),
        ('logger', '0045_xform_add_pending_transfer'),
    ]

    operations = []
