# Generated by Django 4.2.15 on 2025-08-18 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0046_merge_20250703_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancehistory',
            name='root_uuid',
            field=models.CharField(max_length=249, null=True),
        ),
    ]
