# flake8: noqa: E501
# Generated by Django 4.2.15 on 2025-08-20 19:52

from django.conf import settings
from django.db import migrations, models


def manually_create_indexes_instructions(apps, schema_editor):
    print(
        """
        ⚠️ ATTENTION ⚠️
        Run the SQL query below in PostgreSQL directly:

            > CREATE INDEX CONCURRENTLY "logger_instance_history_root_uuid_idx" ON "logger_instancehistory" ("root_uuid");

        """
    )


def manually_drop_indexes_instructions(apps, schema_editor):
    print(
        """
        ⚠️ ATTENTION ⚠️
        Run the SQL query below in PostgreSQL directly:

            > DROP INDEX CONCURRENTLY IF EXISTS "logger_instance_history_root_uuid_idx";

        """
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0047_instancehistory_root_uuid'),
    ]

    if settings.SKIP_HEAVY_MIGRATIONS:
        operations = [
            migrations.RunPython(
                manually_create_indexes_instructions,
                manually_drop_indexes_instructions,
            )
        ]
    else:
        operations = [
            migrations.AlterField(
                model_name='instancehistory',
                name='root_uuid',
                field=models.CharField(db_index=True, max_length=249, null=True),
            ),
        ]
