# Generated by Django 4.2.24 on 2025-10-28 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0049_alter_instance_history_allow_null_instance'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "logger_instance" ALTER COLUMN "user_id" DROP NOT NULL;',
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
