# Generated by Django 5.2.13 on 2026-06-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0051_alter_logger_models_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='audio_length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
