# Generated by Django 5.2.14 on 2026-07-31 17:08
from django.conf import settings
from django.db import migrations, models

from kobo.apps.user_reports.utils.migrations import (
    CREATE_MV_SQL_VERSIONS,
    drop_mv,
    reschedule_lrm_recreate,
)

dependencies = [
    ('user_reports', '0008_drop_mv_before_djstripe'),
    ('long_running_migrations', '0019_recreate_user_reports_mv'),
    ('trackers', '0006_add_total_llm_requests'),
]
if 'djstripe' in settings.INSTALLED_APPS:
    # 0013_2_9 is the first djstripe migration that alters columns the MV
    # depends on (price.type, product.type). Make sure that's done before kicking
    # off another drop-and-rebuild
    dependencies.append(('djstripe', '0013_2_9'))

expected_sql_version = '20260807'

operations = [
    migrations.RunPython(drop_mv, migrations.RunPython.noop),
    migrations.AddField(
        model_name='billingandusagesnapshot',
        name='llm_requests_limit',
        field=models.BigIntegerField(blank=True, null=True),
    ),
]
if CREATE_MV_SQL_VERSIONS[-1] == expected_sql_version:
    operations.append(
        migrations.RunPython(reschedule_lrm_recreate, migrations.RunPython.noop)
    )


class Migration(migrations.Migration):

    atomic = False

    dependencies = dependencies

    operations = operations
