# Generated by Django 3.2.15 on 2022-10-07 16:43

from django.core.paginator import Paginator
from django.db import migrations, models
import django.db.models.deletion


def migrate_email(apps, schema_editor):
    # Effecient bulk data mover - 3 queries per 2k users
    User = apps.get_model('auth', 'User')
    ImportedVerification = apps.get_model('accounts', 'ImportedVerification')
    EmailAddress = apps.get_model('account', 'EmailAddress')

    paginator = Paginator(User.objects.exclude(email=''), 2000)
    for page in paginator.page_range:
        users = paginator.page(page).object_list
        emails = EmailAddress.objects.bulk_create(
            [
                EmailAddress(
                    user=user, email=user.email, verified=True, primary=True
                )
                for user in users
            ]
        )
        ImportedVerification.objects.bulk_create(
            [ImportedVerification(email=email) for email in emails]
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_email_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedVerification',
            fields=[
                (
                    'email',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='+',
                        serialize=False,
                        to='account.emailaddress',
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_email),
    ]
