# Generated by Django 4.2.24 on 2026-01-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_socialappcustomdata_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialappcustomdata',
            name='is_public',
            field=models.BooleanField(
                default=False, help_text='Display social login on login page'
            ),
        ),
    ]
