# Generated by Django 5.2.14 on 2026-08-14 17:06

import django.db.models.deletion
from django.db import migrations, models

import kobo.apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_socialappcustomdata_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialappcustomdata',
            name='managed',
            field=models.BooleanField(
                default=False,
                help_text='Allow clients to manage users exclusively through SSO',
            ),
        ),
        migrations.CreateModel(
            name='SocialAppManagedDomain',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'domain',
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[kobo.apps.accounts.models.validate_domain],
                    ),
                ),
                (
                    'social_app',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='domains',
                        to='accounts.socialappcustomdata',
                    ),
                ),
            ],
        ),
    ]
