# Generated by Django 5.2.14 on 2026-09-10 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_socialappcustomdata_managed_socialappmanageddomain'),
        ('help', '0005_inappmessage_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialappcustomdata',
            name='in_app_message',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='custom_data',
                to='help.inappmessage',
            ),
        ),
        migrations.AddField(
            model_name='socialappcustomdata',
            name='send_in_app_message',
            field=models.BooleanField(
                default=True,
                help_text='Notify unlinked users on managed SSO activation',
            ),
        ),
    ]
