# Generated by Django 5.2.14 on 2026-09-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_socialappcustomdata_managed_socialappmanageddomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialappcustomdata',
            name='in_app_message_body',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Body of that in-app message; empty means the default text',
            ),
        ),
        migrations.AddField(
            model_name='socialappcustomdata',
            name='send_in_app_message',
            field=models.BooleanField(
                default=False,
                help_text='Send unlinked accounts on managed domains an in-app message',
            ),
        ),
    ]
