# Generated by Django 5.2.14 on 2026-09-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_socialappcustomdata_in_app_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialappcustomdata',
            name='logout_behavior',
            field=models.CharField(
                choices=[
                    ('local_only', 'Local logout only'),
                    ('rp_initiated', 'RP-initiated logout (IdP end session)'),
                    ('prompt_login', 'Prompt login on next sign-in'),
                ],
                default='local_only',
                help_text='Logout behavior for this SSO provider',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='socialappcustomdata',
            name='end_session_endpoint',
            field=models.URLField(
                blank=True,
                help_text='Custom OIDC end session endpoint (optional; auto-discovered if left blank)',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='socialappcustomdata',
            name='post_logout_redirect_uri',
            field=models.URLField(
                blank=True,
                help_text='URL to redirect to after IdP logout (optional; defaults to Kobo login page)',
                null=True,
            ),
        ),
    ]
