# Generated by Django 3.2.15 on 2022-09-30 20:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.BigIntegerField()),
                (
                    'date_created',
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ('metadata', models.JSONField(default=dict)),
                (
                    'method',
                    models.CharField(
                        choices=[
                            ('create', 'CREATE'),
                            ('delete', 'DELETE'),
                            ('update', 'UPDATE'),
                        ],
                        db_index=True,
                        default='delete',
                        max_length=6,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'index_together': {
                    ('app_label', 'model_name'),
                    ('app_label', 'model_name', 'method'),
                },
            },
        ),
    ]
