# Generated by Django 3.2.15 on 2023-03-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='auditlog',
            index_together={('app_label', 'model_name')},
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='method',
            new_name='action',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('create', 'CREATE'),
                    ('delete', 'DELETE'),
                    ('in-trash', 'IN TRASH'),
                    ('put-back', 'PUT BACK'),
                    ('remove', 'REMOVE'),
                    ('update', 'UPDATE'),
                ],
                db_index=True,
                default='delete',
                max_length=10,
            ),
        ),
        migrations.AlterIndexTogether(
            name='auditlog',
            index_together={
                ('app_label', 'model_name', 'action'),
                ('app_label', 'model_name'),
            },
        ),
    ]
