# Generated by Django 3.2.15 on 2023-03-28 16:23
from django.db import migrations, models

from kpi.fields.kpi_uid import UUID_LENGTH


def noop(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_add_uid_to_extra_details'),
        ('audit_log', '0003_alter_auditlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_uid',
            field=models.CharField(
                default='',
                max_length=UUID_LENGTH + 1,
                db_index=True,
            ),
        ),
        migrations.RunSQL(
            sql="UPDATE audit_log_auditlog SET user_uid = hub_extrauserdetail.uid "
            "FROM hub_extrauserdetail "
            "WHERE audit_log_auditlog.user_id = hub_extrauserdetail.user_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
