# Generated by Django 3.2.15 on 2023-03-28 16:23

from django.core.paginator import Paginator
from django.db import migrations, models

from kpi.fields.kpi_uid import KpiUidField, UUID_LENGTH


def update_null_uids(apps, schema_editor):

    AuditLog = apps.get_model('audit_log', 'AuditLog')  # noqa
    page_size = 10000
    paginator = Paginator(
        AuditLog.objects.filter(user__isnull=True)
        .order_by('pk'),
        page_size,
    )
    for page in paginator.page_range:
        audit_logs = paginator.page(page).object_list
        for audit_log in audit_logs:
            audit_log.user_uid = KpiUidField.generate_unique_id(prefix='u')
        AuditLog.objects.bulk_update(audit_logs, ['user_uid'], batch_size=2000)


def noop(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_add_uid_to_extra_details'),
        ('audit_log', '0003_alter_auditlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_uid',
            field=models.CharField(
                default='',
                max_length=UUID_LENGTH + 1,
                db_index=True,
            ),
        ),
        migrations.RunSQL(
            sql="UPDATE audit_log_auditlog SET user_uid = hub_extrauserdetail.uid "
                "FROM hub_extrauserdetail "
                "WHERE audit_log_auditlog.user_id = hub_extrauserdetail.user_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(update_null_uids, noop),
    ]
