# Generated by Django 3.2.15 on 2023-04-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0004_populate_user_uids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_uid',
            field=models.CharField(db_index=True, max_length=22),
        ),
    ]
