# Generated by Django 4.2.15 on 2024-09-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0009_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('audit_log.auditlog',),
        ),
    ]
