# Generated by Django 4.2.15 on 2024-10-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0011_projecthistorylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('create', 'Create'),
                    ('delete', 'Delete'),
                    ('in-trash', 'In Trash'),
                    ('put-back', 'Put Back'),
                    ('remove', 'Remove'),
                    ('update', 'Update'),
                    ('auth', 'Auth'),
                    ('deploy', 'Deploy'),
                    ('archive', 'Archive'),
                    ('unarchive', 'Unarchive'),
                    ('redeploy', 'Redeploy'),
                ],
                db_index=True,
                default='delete',
                max_length=30,
            ),
        ),
    ]
