# Generated by Django 4.2.15 on 2024-12-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0012_alter_auditlog_action'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE audit_log_auditlog SET action = 'modify-sharing' "
                "WHERE action = 'modify_sharing';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('add-media', 'Add Media'),
                    ('allow-anonymous-submissions', 'Allow Anonymous Submissions'),
                    ('archive', 'Archive'),
                    ('auth', 'Auth'),
                    ('clone-permissions', 'Clone Permissions'),
                    ('connect-project', 'Connect Project'),
                    ('create', 'Create'),
                    ('delete', 'Delete'),
                    ('delete-media', 'Delete Media'),
                    ('delete-service', 'Delete Service'),
                    ('deploy', 'Deploy'),
                    ('disable-sharing', 'Disable Sharing'),
                    (
                        'disallow-anonymous-submissions',
                        'Disallow Anonymous Submissions',
                    ),
                    ('disconnect-project', 'Disconnect Project'),
                    ('enable-sharing', 'Enable Sharing'),
                    ('export', 'Export'),
                    ('in-trash', 'In Trash'),
                    ('modify-imported-fields', 'Modify Imported Fields'),
                    ('modify-service', 'Modify Service'),
                    ('modify-sharing', 'Modify Sharing'),
                    ('modify-user-permissions', 'Modify User Permissions'),
                    ('put-back', 'Put Back'),
                    ('redeploy', 'Redeploy'),
                    ('register-service', 'Register Service'),
                    ('remove', 'Remove'),
                    ('replace-form', 'Replace Form'),
                    ('share-form-publicly', 'Share Form Publicly'),
                    ('share-data-publicly', 'Share Data Publicly'),
                    ('unarchive', 'Unarchive'),
                    ('unshare-form-publicly', 'Unshare Form Publicly'),
                    ('unshare-data-publicly', 'Unshare Data Publicly'),
                    ('update', 'Update'),
                    ('update-content', 'Update Content'),
                    ('update-name', 'Update Name'),
                    ('update-settings', 'Update Settings'),
                    ('update-qa', 'Update Qa'),
                ],
                db_index=True,
                default='delete',
                max_length=30,
            ),
        ),
    ]
