# Generated by Django 4.2.15 on 2025-05-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0014_add_modify_qa_data_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='log_type',
            field=models.CharField(
                choices=[
                    ('access', 'Access'),
                    ('project-history', 'Project History'),
                    ('data-editing', 'Data Editing'),
                    ('user-management', 'User Management'),
                    ('asset-management', 'Asset Management'),
                    ('submission-management', 'Submission Management'),
                    ('attachment-management', 'Attachment Management'),
                ],
                db_index=True,
            ),
        ),
    ]
