# Generated by Django 4.2.15 on 2025-01-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0015_add_submission_audit_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_uid',
            field=models.CharField(db_index=True, max_length=22, null=True),
        ),
    ]
