# Generated by Django 4.2.24 on 2026-03-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0015_alter_auditlog_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='object_id_tmp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
