# Generated by Django 4.2.24 on 2026-02-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0016_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('add-media', 'Add Media'),
                    ('add-submission', 'Add Submission'),
                    ('allow-anonymous-submissions', 'Allow Anonymous Submissions'),
                    ('archive', 'Archive'),
                    ('auth', 'Auth'),
                    ('clone-permissions', 'Clone Permissions'),
                    ('connect-project', 'Connect Project'),
                    ('create', 'Create'),
                    ('delete', 'Delete'),
                    ('delete-media', 'Delete Media'),
                    ('delete-service', 'Delete Service'),
                    ('delete-submission', 'Delete Submission'),
                    ('deploy', 'Deploy'),
                    ('disable-sharing', 'Disable Sharing'),
                    (
                        'disallow-anonymous-submissions',
                        'Disallow Anonymous Submissions',
                    ),
                    ('disconnect-project', 'Disconnect Project'),
                    ('enable-sharing', 'Enable Sharing'),
                    ('export', 'Export'),
                    ('in-trash', 'In Trash'),
                    ('modify-imported-fields', 'Modify Imported Fields'),
                    ('modify-service', 'Modify Service'),
                    ('modify-sharing', 'Modify Sharing'),
                    ('modify-submission', 'Modify Submission'),
                    ('modify-qa-data', 'Modify Qa Data'),
                    ('modify-automatic-qa-data', 'Modify Automatic Qa Data'),
                    ('modify-user-permissions', 'Modify User Permissions'),
                    ('put-back', 'Put Back'),
                    ('redeploy', 'Redeploy'),
                    ('register-service', 'Register Service'),
                    ('remove', 'Remove'),
                    ('replace-form', 'Replace Form'),
                    ('share-form-publicly', 'Share Form Publicly'),
                    ('share-data-publicly', 'Share Data Publicly'),
                    ('unarchive', 'Unarchive'),
                    ('unshare-form-publicly', 'Unshare Form Publicly'),
                    ('unshare-data-publicly', 'Unshare Data Publicly'),
                    ('unverify-automatic-qa-data', 'Unverify Automatic Qa Data'),
                    ('unverify-manual-qa-data', 'Unverify Manual Qa Data'),
                    ('update', 'Update'),
                    ('update-content', 'Update Content'),
                    ('update-name', 'Update Name'),
                    ('update-settings', 'Update Settings'),
                    ('update-qa', 'Update Qa'),
                    ('transfer', 'Transfer'),
                    ('verify-automatic-qa-data', 'Verify Automatic Qa Data'),
                    ('verify-manual-qa-data', 'Verify Manual Qa Data'),
                ],
                db_index=True,
                default='delete',
                max_length=60,
            ),
        ),
    ]
