# Generated by Django 4.2.24 on 2026-03-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0018_alter_auditlog_action_alter_auditlog_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
