from django.db import models


class AuditAction(models.TextChoices):
    ADD_MEDIA = 'add-media'
    ARCHIVE = 'archive'
    AUTH = 'auth'
    CONNECT_PROJECT = 'connect-project'
    CREATE = 'create'
    DELETE = 'delete'
    DELETE_MEDIA = 'delete-media'
    DELETE_SERVICE = 'delete-service'
    DEPLOY = 'deploy'
    DISABLE_SHARING = 'disable-sharing'
    DISCONNECT_PROJECT = 'disconnect-project'
    ENABLE_SHARING = 'enable-sharing'
    EXPORT = 'export'
    IN_TRASH = 'in-trash'
    MODIFY_IMPORTED_FIELDS = 'modify-imported-fields'
    MODIFY_SERVICE = 'modify-service'
    MODIFY_SHARING = 'modify_sharing'
    PUT_BACK = 'put-back'
    REDEPLOY = 'redeploy'
    REGISTER_SERVICE = 'register-service'
    REMOVE = 'remove'
    REPLACE_FORM = 'replace-form'
    UNARCHIVE = 'unarchive'
    UPDATE = 'update'
    UPDATE_CONTENT = 'update-content'
    UPDATE_NAME = 'update-name'
    UPDATE_SETTINGS = 'update-settings'
    UPDATE_QA = 'update-qa'
