from django.db import models


class AuditAction(models.TextChoices):
    ADD_MEDIA = 'add-media'
    ADD_SUBMISSION = 'add-submission'
    ALLOW_ANONYMOUS_SUBMISSIONS = 'allow-anonymous-submissions'
    ARCHIVE = 'archive'
    AUTH = 'auth'
    CLONE_PERMISSIONS = 'clone-permissions'
    CONNECT_PROJECT = 'connect-project'
    CREATE = 'create'
    DELETE = 'delete'
    DELETE_MEDIA = 'delete-media'
    DELETE_SERVICE = 'delete-service'
    DELETE_SUBMISSION = 'delete-submission'
    DEPLOY = 'deploy'
    DISABLE_SHARING = 'disable-sharing'
    DISALLOW_ANONYMOUS_SUBMISSIONS = 'disallow-anonymous-submissions'
    DISCONNECT_PROJECT = 'disconnect-project'
    ENABLE_SHARING = 'enable-sharing'
    EXPORT = 'export'
    IN_TRASH = 'in-trash'
    MODIFY_IMPORTED_FIELDS = 'modify-imported-fields'
    MODIFY_SERVICE = 'modify-service'
    MODIFY_SHARING = 'modify-sharing'
    MODIFY_SUBMISSION = 'modify-submission'
    MODIFY_USER_PERMISSIONS = 'modify-user-permissions'
    PUT_BACK = 'put-back'
    REDEPLOY = 'redeploy'
    REGISTER_SERVICE = 'register-service'
    REMOVE = 'remove'
    REPLACE_FORM = 'replace-form'
    SHARE_FORM_PUBLICLY = 'share-form-publicly'
    SHARE_DATA_PUBLICLY = 'share-data-publicly'
    UNARCHIVE = 'unarchive'
    UNSHARE_FORM_PUBLICLY = 'unshare-form-publicly'
    UNSHARE_DATA_PUBLICLY = 'unshare-data-publicly'
    UPDATE = 'update'
    UPDATE_CONTENT = 'update-content'
    UPDATE_NAME = 'update-name'
    UPDATE_SETTINGS = 'update-settings'
    UPDATE_QA = 'update-qa'
    TRANSFER = 'transfer'
