# Generated by Django 4.2.15 on 2025-04-16 11:18
from django.conf import settings
from django.db.models.query import QuerySet

from kpi.models.asset import Asset

CHUNK_SIZE = settings.LONG_RUNNING_MIGRATION_BATCH_SIZE


def run():
    """
    Backfills is_excluded_from_projects_list (to False) for the Asset model
    """
    stop = False
    asset_pk = 0

    while not stop:
        if asset_ids := get_queryset(asset_pk):
            Asset.all_objects.filter(pk__in=asset_ids).update(
                is_excluded_from_projects_list=False
            )
            asset_pk = list(asset_ids)[-1]
        else:
            stop = True


def get_queryset(asset_pk: int) -> QuerySet[Asset]:
    return (
        Asset.all_objects.values_list('pk', flat=True)
        .filter(
            is_excluded_from_projects_list__isnull=True,
            pk__gt=asset_pk,
        )
        .order_by('pk')[:CHUNK_SIZE]
    )
