# flake8: noqa: F401
import kpi.schema_extensions.v2.asset_attachments.extensions
import kpi.schema_extensions.v2.asset_permission_assignments.extensions
import kpi.schema_extensions.v2.asset_snapshots.extensions
import kpi.schema_extensions.v2.asset_subscriptions.extensions
import kpi.schema_extensions.v2.asset_usage.extensions
import kpi.schema_extensions.v2.assets.extensions
import kpi.schema_extensions.v2.data.extensions
import kpi.schema_extensions.v2.export_settings.extensions
import kpi.schema_extensions.v2.export_tasks.extensions
import kpi.schema_extensions.v2.files.extensions
import kpi.schema_extensions.v2.invites.extensions
import kpi.schema_extensions.v2.members.extensions
import kpi.schema_extensions.v2.openrosa.extensions
import kpi.schema_extensions.v2.organizations.extensions
import kpi.schema_extensions.v2.paired_data.extensions
import kpi.schema_extensions.v2.service_usage.extensions
import kpi.schema_extensions.v2.permissions.extensions
import kpi.schema_extensions.v2.versions.extensions
