# Generated by Django 4.2.11 on 2024-07-17 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_update_meta_data_export_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancemodification',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='instancemodification',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
