# Generated by Django 4.2.24 on 2025-10-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_alter_instancemodification_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedinstance',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
