# flake8: noqa: F401
# Generated by Django 4.2.11 on 2024-07-03 19:37

from django.db import migrations


class Migration(migrations.Migration):
    """
    Dummy migration to be able to register SuperuserStatsModel with its admin
    model without raising an error.

    > django.db.migrations.exceptions.InvalidBasesError: Cannot resolve bases for [<ModelState: 'superuser_stats.SuperuserStatsModel'>]
    >   This can happen if you are inheriting models from an app with migrations (e.g.: contrib.auth)
    >   in an app with no migrations; see https://docs.djangoproject.com/en/4.2/topics/migrations/#dependencies for more details
    """

    dependencies = [
        ('logger', '0034_set_require_auth_at_project_level'),
    ]

    operations = []
