# Generated by Django 4.2.24 on 2026-01-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logger', '0051_alter_logger_models_options'),
        ('superuser_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperuserStatsModel',
            fields=[],
            options={
                'verbose_name_plural': 'Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('logger.monthlyxformsubmissioncounter',),
        ),
    ]
