# Generated by Django 3.2.15 on 2023-06-22 20:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.migrations.operations.special
from django.db.models import DateField, F, Value
from django.db.models.functions import Cast, Concat, ExtractMonth, ExtractYear


class Migration(migrations.Migration):
    replaces = [
        ('trackers', '0003_add_monthlynlpusagecounter_date'),
        ('trackers', '0004_populate_date_and_totals'),
        ('trackers', '0005_remove_year_and_month'),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trackers', '0002_alter_monthlynlpusagecounter_user'),
    ]

    def copy_month_and_year_to_date(apps, schema_editor):
        MonthlyNLPUsageCounter = apps.get_model(
            "trackers", "MonthlyNLPUsageCounter"
        )
        # Note: when converting monthly usage data to daily, set the day to the 1st of the month
        MonthlyNLPUsageCounter.objects.only('year', 'month', 'date').update(
            date=Cast(
                Concat(F('year'), Value('-'), F('month'), Value('-'), 1),
                DateField(),
            ),
        )

    def copy_date_to_month_and_year(apps, schema_editor):
        MonthlyNLPUsageCounter = apps.get_model(
            "trackers", "MonthlyNLPUsageCounter"
        )
        # When doing the operation in reverse we can just do an update
        MonthlyNLPUsageCounter.objects.only('year', 'month', 'date').update(
            year=ExtractYear('date'),
            month=ExtractMonth('date'),
        )

    def populate_usage_totals(apps, schema_editor):
        MonthlyNLPUsageCounter = apps.get_model(
            "trackers", "MonthlyNLPUsageCounter"
        )
        for usage_counter in (
            MonthlyNLPUsageCounter.objects.only('year', 'month', 'date')
                .all()
                .iterator()
        ):
            total_asr_seconds, total_mt_characters = 0, 0
            for tracker, amount in usage_counter.counters.items():
                if tracker.endswith('asr_seconds'):
                    total_asr_seconds += amount
                if tracker.endswith('mt_characters'):
                    total_mt_characters += amount
            usage_counter.total_asr_seconds = total_asr_seconds
            usage_counter.total_asr_seconds = total_asr_seconds
            usage_counter.save()

    operations = [
        migrations.AddField(
            model_name='monthlynlpusagecounter',
            name='date',
            field=models.DateField(
                default=datetime.datetime(2023, 6, 22, 20, 30, 22, 43154)
            ),
        ),
        migrations.AddField(
            model_name='monthlynlpusagecounter',
            name='total_asr_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlynlpusagecounter',
            name='total_mt_characters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            code=copy_month_and_year_to_date,
            reverse_code=copy_date_to_month_and_year,
        ),
        migrations.RunPython(
            code=populate_usage_totals,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='monthlynlpusagecounter',
            name='year',
        ),
        migrations.RemoveField(
            model_name='monthlynlpusagecounter',
            name='month',
        ),
        migrations.RenameModel(
            old_name='monthlynlpusagecounter',
            new_name='nlpusagecounter',
        ),
    ]
