# Generated by Django 4.2.15 on 2025-09-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0005_remove_year_and_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlpusagecounter',
            name='total_llm_requests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
