# flake8: noqa: E501
# Generated by Django 4.2.24 on 2026-01-09 15:02

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def manually_create_indexes_and_constraints_instructions(apps, schema_editor):
    print(
        """
        ⚠️ ATTENTION ⚠️
        Run the SQL queries below in PostgreSQL directly (so we can use CONCURRENTLY):

            -- Legacy cleanup (safe to re-run)
            DROP INDEX CONCURRENTLY IF EXISTS "trackers_mo_year_72676f_idx";
            ALTER TABLE "trackers_nlpusagecounter" DROP CONSTRAINT IF EXISTS "unique_with_asset";
            DROP INDEX CONCURRENTLY IF EXISTS "unique_without_asset";

            -- New objects
            CREATE INDEX CONCURRENTLY IF NOT EXISTS "trackers_nl_date_552b2e_idx"
              ON "trackers_nlpusagecounter" ("date", "user_id");

            CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS "nlpusagecounter_unique_with_asset_idx"
              ON "trackers_nlpusagecounter" ("date", "user_id", "asset_id");

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'nlpusagecounter_unique_with_asset'
                ) THEN
                    ALTER TABLE "trackers_nlpusagecounter"
                        ADD CONSTRAINT "nlpusagecounter_unique_with_asset"
                        UNIQUE USING INDEX "nlpusagecounter_unique_with_asset_idx";
                END IF;
            END
            $$;

            CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS "nlpusagecounter_unique_without_asset"
              ON "trackers_nlpusagecounter" ("date", "user_id")
              WHERE "asset_id" IS NULL;
        """
    )


def manually_drop_indexes_and_constraints_instructions(apps, schema_editor):
    print(
        """
        ⚠️ ATTENTION ⚠️
        Run the SQL queries below in PostgreSQL directly:

            ALTER TABLE "trackers_nlpusagecounter" DROP CONSTRAINT IF EXISTS "nlpusagecounter_unique_with_asset";
            DROP INDEX CONCURRENTLY IF EXISTS "nlpusagecounter_unique_with_asset_idx";
            DROP INDEX CONCURRENTLY IF EXISTS "nlpusagecounter_unique_without_asset";
            DROP INDEX CONCURRENTLY IF EXISTS "trackers_nl_date_552b2e_idx";
        """
    )


def legacy_cleanup_ops():
    """
    Remove old monthly-based objects (by their legacy names).
    This MUST be idempotent in DB, because they may not exist in some environments.
    """
    return migrations.SeparateDatabaseAndState(
        database_operations=[
            # Index (legacy)
            migrations.RunSQL(
                sql='DROP INDEX IF EXISTS "trackers_mo_year_72676f_idx";',
                reverse_sql=migrations.RunSQL.noop,
            ),
            # Unique constraint (legacy)
            migrations.RunSQL(
                sql='ALTER TABLE "trackers_nlpusagecounter" DROP CONSTRAINT IF EXISTS "unique_with_asset";',
                reverse_sql=migrations.RunSQL.noop,
            ),
            migrations.RunSQL(
                sql='DROP INDEX IF EXISTS "unique_without_asset";',
                reverse_sql=migrations.RunSQL.noop,
            ),
            # Conditional unique (legacy) -> in Postgres: partial unique index
            migrations.RunSQL(
                sql='DROP INDEX IF EXISTS "unique_without_asset";',
                reverse_sql=migrations.RunSQL.noop,
            ),
        ],
        state_operations=[
            migrations.RemoveIndex(
                model_name='nlpusagecounter',
                name='trackers_mo_year_72676f_idx',
            ),
            migrations.RemoveConstraint(
                model_name='nlpusagecounter',
                name='unique_with_asset',
            ),
            migrations.RemoveConstraint(
                model_name='nlpusagecounter',
                name='unique_without_asset',
            ),
        ],
    )


def add_state_ops():
    return [
        migrations.AddIndex(
            model_name='nlpusagecounter',
            index=models.Index(fields=['date', 'user'], name='trackers_nl_date_552b2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='nlpusagecounter',
            constraint=models.UniqueConstraint(
                fields=('date', 'user', 'asset'),
                name='nlpusagecounter_unique_with_asset',
            ),
        ),
        migrations.AddConstraint(
            model_name='nlpusagecounter',
            constraint=models.UniqueConstraint(
                condition=Q(('asset', None)),
                fields=('date', 'user'),
                name='nlpusagecounter_unique_without_asset',
            ),
        ),
    ]


def get_add_operations():
    state_ops = add_state_ops()

    if settings.SKIP_HEAVY_MIGRATIONS:
        return [
            migrations.SeparateDatabaseAndState(
                database_operations=[
                    migrations.RunPython(
                        manually_create_indexes_and_constraints_instructions,
                        manually_drop_indexes_and_constraints_instructions,
                    )
                ],
                state_operations=state_ops,
            )
        ]

    return state_ops


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0070_alter_kpi_models_options'),
        ('trackers', '0006_add_total_llm_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlpusagecounter',
            name='date',
            field=models.DateField(),
        ),
        legacy_cleanup_ops(),
        *get_add_operations(),
    ]
