# Generated by Django 3.2.15 on 2023-06-07 19:25
import re

import django.db.models.deletion
from django.core.paginator import Paginator
from django.db import migrations, models


def add_file_references(apps, schema_editor):

    InAppMessage = apps.get_model('help', 'InAppMessage')  # noqa
    MarkdownxUploaderFile = apps.get_model(   # noqa
        'markdownx_uploader', 'MarkdownxUploaderFile'
    )
    MarkdownxUploaderFileReference = apps.get_model(   # noqa
        'markdownx_uploader', 'MarkdownxUploaderFileReference'
    )

    page_size = 10000
    paginator = Paginator(
        InAppMessage.objects.all().order_by('pk'),
        page_size,
    )

    for page in paginator.page_range:
        in_app_messages = paginator.page(page).object_list
        refs = []
        for in_app_message in in_app_messages:
            content = f'{in_app_message.snippet}\n{in_app_message.body}'
            if results := re.findall(r'!\[\]\(([^\)]+)', content):
                image_paths = []
                for result in results:
                    # image path in markdown use this format:
                    # /<app_label>/<url_prefix>/<filename>
                    # We need only the filename
                    _, _, _, *parts = result.split('/')
                    image_paths.append('/'.join(parts))

                pks = MarkdownxUploaderFile.objects.values_list(
                    'pk', flat=True
                ).filter(content__in=image_paths)

                for pk in pks:
                    refs.append(
                        MarkdownxUploaderFileReference(
                            file_id=pk,
                            app_label='help',
                            model_name='inappmessage',
                            object_id=pk,
                        )
                    )

        MarkdownxUploaderFileReference.objects.bulk_create(refs)


def noop(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('markdownx_uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownxUploaderFileReference',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('app_label', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.IntegerField(db_index=True)),
                (
                    'file',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='markdown_fields',
                        to='markdownx_uploader.markdownxuploaderfile',
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            add_file_references,
            noop,
        )
    ]
