# Generated by Django 2.2.27 on 2022-07-05 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trench', '0003_auto_20190213_2330'),
        ('mfa', '0002_add_mfa_available_to_user_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KoboMFAMethod',
            new_name='MfaMethod',
        ),
    ]
