# Generated by Django 2.2.7 on 2019-11-26 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('kpi', '0024_alter_jsonfield_to_jsonbfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectpermission',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
