# Generated by Django 2.2.7 on 2021-01-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0030_auto_20210126_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetexportsettings',
            name='name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
