# Generated by Django 2.2.7 on 2021-01-28 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0031_assetexportsettings_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetexportsettings',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
