# Generated by Django 2.2.7 on 2021-01-29 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0032_assetexportsettings_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetexportsettings',
            name='date_created',
        ),
    ]
