# Generated by Django 2.2.7 on 2020-12-23 20:15

from django.db import migrations, models
import kpi.fields.lazy_default_boolean
import kpi.fields.lazy_default_jsonb
import kpi.models.import_export_task
import private_storage.fields
import private_storage.storage.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0032_add_delete_at_field_to_asset_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='data_sharing',
            field=kpi.fields.lazy_default_jsonb.LazyDefaultJSONBField(default=dict),
        ),
        migrations.AddField(
            model_name='asset',
            name='paired_data',
            field=kpi.fields.lazy_default_jsonb.LazyDefaultJSONBField(default=dict),
        ),
    ]
