# Generated by Django 2.2.7 on 2020-11-19 17:19

from django.db import migrations, models
import kpi.models.import_export_task
import private_storage.fields
import private_storage.storage.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0035_nullable_asset_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetfile',
            name='date_deleted',
            field=models.DateTimeField(null=True, default=None),
        ),
    ]
