# Generated by Django 2.2.7 on 2021-09-17 19:18

from django.db import migrations
import kpi.models.asset_file
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0037_add_sync_flag_to_asset_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetfile',
            name='content',
            field=private_storage.fields.PrivateFileField(max_length=380, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=kpi.models.asset_file.upload_to),
        ),
    ]
