# Generated by Django 2.2.7 on 2021-09-29 17:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kpi.fields.kpi_uid
import kpi.models.asset_file
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0039_add_support_paired_data_to_asset_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', kpi.fields.kpi_uid.KpiUidField(uid_prefix='ar')),
                ('submission_id', models.BigIntegerField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', kpi.fields.kpi_uid.KpiUidField(uid_prefix='aq')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.Asset')),
            ],
        ),
    ]
