# Generated by Django 3.2.15 on 2022-09-15 18:56

from django.db import migrations
import kpi.fields.lazy_default_jsonb
import kpi.models.asset_file
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0042_snapshots_uuids'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='known_cols',
            field=kpi.fields.lazy_default_jsonb.LazyDefaultJSONBField(default=list),
        ),
    ]
