# Generated by Django 3.2.15 on 2023-01-12 14:27

import django.contrib.postgres.indexes
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


def manually_create_indexes_instructions(apps, schema_editor):
    print(
        """
        !!! ATTENTION !!!
        If you have existing projects you need to run the SQL queries below in PostgreSQL directly:

           > CREATE INDEX CONCURRENTLY "kpi_asset_settings__country_codes_idx" on kpi_asset USING GIN((settings->'country_codes'));
           > CREATE INDEX CONCURRENTLY "kpi_asset_asset_type_idx" ON "kpi_asset" ("asset_type");
           > CREATE INDEX CONCURRENTLY "kpi_asset_asset_type__like_idx" ON "kpi_asset" ("asset_type" varchar_pattern_ops);

        Otherwise, project views will perform very poorly.
        """
    )


def manually_drop_indexes_instructions(apps, schema_editor):
    print(
        """
        !!! ATTENTION !!!
        Run the SQL queries below in PostgreSQL directly:

           > DROP INDEX IF EXISTS "kpi_asset_settings__country_codes_idx";
           > DROP INDEX IF EXISTS "kpi_asset_asset_type_idx";
           > DROP INDEX IF EXISTS "kpi_asset_asset_type__like_idx";

        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0045_project_view_export_task'),
    ]

    if not settings.SKIP_HEAVY_MIGRATIONS:
        operations = [
            migrations.AddIndex(
                model_name='asset',
                index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('settings__country_codes'), name='settings__country_codes_idx'),
            ),
            migrations.AlterField(
                model_name='asset',
                name='asset_type',
                field=models.CharField(
                    choices=[
                        ('text', 'text'),
                        ('empty', 'empty'),
                        ('question', 'question'),
                        ('block', 'block'),
                        ('survey', 'survey'),
                        ('template', 'template'),
                        ('collection', 'collection'),
                    ],
                    db_index=True,
                    default='survey',
                    max_length=20,
                ),
            ),
        ]
    else:
        operations = [
            migrations.RunPython(
                manually_create_indexes_instructions,
                manually_drop_indexes_instructions,
            )
        ]
