# Generated by Django 3.2.15 on 2023-11-02 15:30

from django.conf import settings
from django.db import migrations

from kpi.utils.django_orm_helper import RemoveJSONFieldAttribute


def set_stored_data_key_to_null(apps, schema_editor):
    if settings.SKIP_HEAVY_MIGRATIONS:
        return

    print(
        """
        This migration might take a while. If it is too slow, you may want to
        re-run migrations with SKIP_HEAVY_MIGRATIONS=True and apply this one
        manually from the django shell.
        """
    )

    Asset = apps.get_model('kpi', 'Asset')  # noqa

    # it's faster to bulk update '_stored_data_key' than trying to remove it
    Asset.objects.filter(_deployment_data__has_key='_stored_data_key').update(
        _deployment_data=RemoveJSONFieldAttribute(
            '_deployment_data',
            attribute_dotted_path='_stored_data_key',
        ),
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0053_set_user_fullname_required_by_default'),
    ]

    operations = [
        migrations.RunPython(set_stored_data_key_to_null, noop),
    ]
