# Generated by Django 4.2.11 on 2024-07-17 19:28

from django.db import migrations, models
import django.utils.timezone
import kpi.fields.file
import kpi.models.asset_file


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0056_fix_add_submission_bad_permission_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetexportsettings',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assetexportsettings',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
