# Generated by Django 4.2.11 on 2024-07-24 06:43

from django.db import migrations, models
import kpi.models.abstract_models
import kpi.models.asset_file


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0058_add_created_by_and_last_modified_by_to_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetexportsettings',
            name='date_created',
            field=models.DateTimeField(
                default=kpi.models.abstract_models._get_default_datetime
            ),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='date_created',
            field=models.DateTimeField(
                default=kpi.models.abstract_models._get_default_datetime
            ),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_created',
            field=models.DateTimeField(
                default=kpi.models.abstract_models._get_default_datetime
            ),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_modified',
            field=models.DateTimeField(
                default=kpi.models.abstract_models._get_default_datetime
            ),
        ),
        migrations.AlterField(
            model_name='assetexportsettings',
            name='date_modified',
            field=models.DateTimeField(
                default=kpi.models.abstract_models._get_default_datetime
            ),
        ),
        migrations.AlterField(
            model_name='assetfile',
            name='date_created',
            field=models.DateTimeField(
                default=kpi.models.abstract_models._get_default_datetime
            ),
        ),
        migrations.AlterField(
            model_name='assetfile',
            name='date_modified',
            field=models.DateTimeField(
                default=kpi.models.abstract_models._get_default_datetime
            ),
        ),
        migrations.AlterField(
            model_name='assetuserpartialpermission',
            name='date_created',
            field=models.DateTimeField(
                default=kpi.models.abstract_models._get_default_datetime
            ),
        ),
        migrations.AlterField(
            model_name='assetuserpartialpermission',
            name='date_modified',
            field=models.DateTimeField(
                default=kpi.models.abstract_models._get_default_datetime
            ),
        ),
        migrations.AlterField(
            model_name='assetversion',
            name='date_modified',
            field=models.DateTimeField(
                default=kpi.models.abstract_models._get_default_datetime
            ),
        ),
    ]
