# Generated by Django 4.2.15 on 2024-12-11 23:12

from django.db import migrations

import kpi.fields.lazy_default_jsonb


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0060_rename_exporttask_submissionexporttask_and_more'),
    ]
    # `search_field` has been modified to remove the default and allow NULL values.
    # This change was introduced between versions 2.025.02b and 2.025.02d
    # to avoid exclusive locks caused by PostgreSQL rewriting the entire table
    # when applying defaults on large tables like `kpi_asset`.
    operations = [
        migrations.AddField(
            model_name='asset',
            name='search_field',
            field=kpi.fields.lazy_default_jsonb.LazyDefaultJSONBField(default=dict),
        ),
    ]
