# Generated by Django 4.2.15 on 2024-11-12 21:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpi', '0061_rename_synchronousexport_submissionssynchronousexport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExportTask',
            new_name='SubmissionsExportTask',
        ),
    ]
