# Generated by Django 4.2.15 on 2025-01-20 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kpi.fields.kpi_uid
import kpi.models.import_export_task
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpi', '0061_add_search_field_to_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHistoryLogExportTask',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('data', models.JSONField()),
                ('messages', models.JSONField(default=dict)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('created', 'created'),
                            ('processing', 'processing'),
                            ('error', 'error'),
                            ('complete', 'complete'),
                        ],
                        default='created',
                        max_length=32,
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('uid', kpi.fields.kpi_uid.KpiUidField(_null=False, uid_prefix='phe')),
                (
                    'result',
                    private_storage.fields.PrivateFileField(
                        max_length=380,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),  # noqa
                        upload_to=kpi.models.import_export_task.export_upload_to,
                    ),
                ),
                ('asset_uid', models.CharField(null=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(
                kpi.models.import_export_task.ExportTaskMixin,
                kpi.models.import_export_task.AuditLogExportTaskMixin,
                models.Model,
            ),
        ),
    ]
