# Generated by Django 4.2.15 on 2025-01-23 09:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0061_add_search_field_to_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsnapshot',
            name='submission_uuid',
            field=models.CharField(max_length=249, null=True),
        ),
    ]
