# Generated by Django 4.2.15 on 2025-04-17 16:56

from django.db import migrations

import kpi.fields.lazy_default_jsonb


class Migration(migrations.Migration):
    """
    This migration ensures that Django's state is correctly aligned with the database
    schema.

    It is particularly important for instances that were upgraded to release 2.025.02
    (prior to 2.025.02d).

    Migrations 0061 and 0063 were modified to remove defaults and allow NULL values.
    This change was necessary because PostgreSQL rewrites the entire table when applying
    a default, which is not sustainable for large tables like `kpi_asset`.
    """
    dependencies = [
        ('kpi', '0064_create_projecthistorylogexporttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='search_field',
            field=kpi.fields.lazy_default_jsonb.LazyDefaultJSONBField(default=dict),
        ),
    ]
