# Generated by Django 4.2.15 on 2025-07-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kobo_auth', '0002_collectorgroup_collector'),
        ('kpi', '0066_allow_is_excluded_from_project_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='collector_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='kobo_auth.collectorgroup'),
        ),
    ]
