# Generated by Django 4.2.15 on 2025-08-20 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo_auth', '0002_datacollectorgroup_datacollector'),
        ('kpi', '0066_allow_is_excluded_from_project_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='data_collector_group',
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assets',
                to='kobo_auth.datacollectorgroup',
            ),
        ),
    ]
