# flake8: noqa: E501
# Generated by Django 4.2.15 on 2025-08-20 16:42
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def manually_create_indexes_instructions(apps, schema_editor):
    print(
        """
        !!! ATTENTION !!!
        If you have existing projects you need to run the SQL queries below in PostgreSQL directly:

           > CREATE INDEX CONCURRENTLY "kpi_asset_data_collector_group_id_90e5a863" ON "kpi_asset" ("data_collector_group_id");
           > CREATE INDEX CONCURRENTLY "kpi_asset_data_collector_group_id_90e5a863_like" ON "kpi_asset" ("data_collector_group_id" varchar_pattern_ops)
        """
    )


def manually_drop_indexes_instructions(apps, schema_editor):
    print(
        """
        !!! ATTENTION !!!
        Run the SQL queries below in PostgreSQL directly:

           > DROP INDEX IF EXISTS "kpi_asset_data_collector_group_id_90e5a863_like";
           > DROP INDEX IF EXISTS "kpi_asset_data_collector_group_id_90e5a863";

        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('kobo_auth', '0002_datacollectorgroup_datacollector'),
        ('kpi', '0067_asset_data_collector_group'),
    ]
    if settings.SKIP_HEAVY_MIGRATIONS:
        operations = [
            migrations.RunPython(
                manually_create_indexes_instructions,
                manually_drop_indexes_instructions,
            )
        ]
    else:
        operations = [
            migrations.AlterField(
                model_name='asset',
                name='data_collector_group',
                field=models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='assets',
                    to='kobo_auth.datacollectorgroup',
                ),
            ),
        ]
