# flake8: noqa: E501
# Generated by Django 4.2.24 on 2026-01-13 19:37

from django.conf import settings
from django.db import migrations, models


def manually_create_indexes_instructions(apps, schema_editor):
    print(
        """
        ⚠️ ATTENTION ⚠️
        Run the SQL queries below in PostgreSQL directly:

        CREATE INDEX CONCURRENTLY IF NOT EXISTS "kpi_asset_pending_delete_0354e024" ON "kpi_asset" ("pending_delete");
        """
    )


def manually_drop_indexes_instructions(apps, schema_editor):
    print(
        """
        ⚠️ ATTENTION ⚠️
        Run the SQL queries below in PostgreSQL directly:

        DROP INDEX CONCURRENTLY IF EXISTS "kpi_asset_pending_delete_0354e024";
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0069_alter_assetversion_reversion_version'),
    ]

    if settings.SKIP_HEAVY_MIGRATIONS:
        operations = [
            migrations.RunPython(
                manually_create_indexes_instructions,
                manually_drop_indexes_instructions,
            )
        ]
    else:
        operations = [
            migrations.AlterField(
                model_name='asset',
                name='pending_delete',
                field=models.BooleanField(db_index=True, default=False),
            )
        ]
