# Generated by Django 4.2.15 on 2025-08-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0069_alter_assetversion_reversion_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetversion',
            old_name='_reversion_version',
            new_name='_reversion_version_id',
        ),
    ]
