# Generated by Django 4.2.24 on 2026-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0071_alter_kpi_models_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversion',
            name='_content_hash',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
