# Generated by Django 4.2.28 on 2026-03-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0071_alter_kpi_models_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraProjectMetadataField',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text="Unique internal identifier (e.g. 'project_sectors')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    'label',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=(
                            "Translation map: "
                            "{'default': 'Country', 'fr': 'Pays'}"
                        ),
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('text', 'Text'),
                            ('single_select', 'Single Select'),
                            ('multi_select', 'Multi Select'),
                        ],
                        default='text',
                        max_length=20,
                    ),
                ),
                (
                    'is_required',
                    models.BooleanField(default=False, verbose_name='Required'),
                ),
                (
                    'options',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {'name': 'val', 'label': {...}} dicts",
                    ),
                ),
            ],
            options={
                'verbose_name': 'Extra Project Metadata Field',
                'verbose_name_plural': 'Extra Project Metadata Fields',
                'ordering': ['name'],
            },
        ),
    ]
