# Generated by Django 4.2.15 on 2025-02-20 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import kpi.fields.kpi_uid
import kpi.models.abstract_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MassEmailConfig',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'date_created',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'date_modified',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                ('uid', kpi.fields.kpi_uid.KpiUidField(_null=False, uid_prefix='mec')),
                ('name', models.CharField()),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                (
                    'template',
                    models.TextField(
                        blank=True,
                        help_text="Available placeholders:<br />##username##<br />##full_name## - user's full name<br />##plan_name## - user's current subscription plan",  # noqa
                        null=True,
                    ),
                ),
                (
                    'query',
                    models.CharField(blank=True, choices=[], max_length=100, null=True),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MassEmailJob',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'date_created',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'date_modified',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                ('uid', kpi.fields.kpi_uid.KpiUidField(_null=False, uid_prefix='mej')),
                (
                    'email_config',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='mass_emails.massemailconfig',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MassEmailRecord',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'date_created',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'date_modified',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('enqueued', 'Enqueued'),
                            ('failed', 'Failed'),
                            ('sent', 'Sent'),
                        ],
                        null=True,
                    ),
                ),
                ('uid', kpi.fields.kpi_uid.KpiUidField(_null=False, uid_prefix='mer')),
                (
                    'email_job',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='mass_emails.massemailjob',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
