# Generated by Django 4.2.15 on 2025-03-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massemailconfig',
            name='query',
            field=models.CharField(
                blank=True,
                choices=[('users_inactive_for_a_year', 'users_inactive_for_a_year')],
                max_length=100,
                null=True,
            ),
        ),
    ]
