# Generated by Django 4.2.15 on 2025-02-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massemailconfig',
            name='query',
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        'users_above_90_percent_storage',
                        'users_above_90_percent_storage',
                    ),
                    (
                        'users_above_100_percent_storage',
                        'users_above_100_percent_storage',
                    ),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
