# Generated by Django 4.2.15 on 2025-03-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_emails', '0002_alter_massemailconfig_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massemailconfig',
            name='query',
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        'users_above_90_percent_storage',
                        'users_above_90_percent_storage',
                    ),
                    (
                        'users_above_100_percent_storage',
                        'users_above_100_percent_storage',
                    ),
                    (
                        'users_inactive_for_365_days',
                        'users_inactive_for_365_days'
                    ),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
