# Generated by Django 4.2.15 on 2025-03-20 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mass_emails', '0004_add_submission_to_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massemailjob',
            name='email_config',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='jobs',
                to='mass_emails.massemailconfig',
            ),
        ),
        migrations.AlterField(
            model_name='massemailrecord',
            name='email_job',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='records',
                to='mass_emails.massemailjob',
            ),
        ),
    ]
