# Generated by Django 4.2.15 on 2025-03-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_emails', '0005_add_related_name_for_massemailjob_and_massemailrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='massemailconfig',
            name='frequency',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='massemailconfig',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='massemailrecord',
            constraint=models.UniqueConstraint(
                fields=('email_job', 'user'), name='unique_user_per_email_job'
            ),
        ),
    ]
