# Generated by Django 4.2.15 on 2025-03-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_emails', '0006_add_frequency_and_live_to_mass_email_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massemailconfig',
            name='query',
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        'users_above_90_percent_storage',
                        'users_above_90_percent_storage',
                    ),
                    (
                        'users_above_100_percent_storage',
                        'users_above_100_percent_storage',
                    ),
                    ('users_inactive_for_365_days', 'users_inactive_for_365_days'),
                    (
                        'users_above_90_percent_submissions',
                        'users_above_90_percent_submissions',
                    ),
                    (
                        'users_above_100_percent_submissions',
                        'users_above_100_percent_submissions',
                    ),
                    (
                        'users_above_90_percent_nlp_usage',
                        'users_above_90_percent_nlp_usage',
                    ),
                    (
                        'users_above_100_percent_nlp_usage',
                        'users_above_100_percent_nlp_usage',
                    ),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
