# Generated by Django 4.2.24 on 2026-01-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_emails', '0009_massemailqueryparam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massemailconfig',
            name='query',
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        'users_above_80_percent_storage',
                        'users_above_80_percent_storage',
                    ),
                    (
                        'users_above_90_percent_storage',
                        'users_above_90_percent_storage',
                    ),
                    (
                        'users_above_100_percent_storage',
                        'users_above_100_percent_storage',
                    ),
                    ('users_inactive_for_365_days', 'users_inactive_for_365_days'),
                    ('users_active_within_365_days', 'users_active_within_365_days'),
                    (
                        'users_above_80_percent_submissions',
                        'users_above_80_percent_submissions',
                    ),
                    (
                        'users_above_90_percent_submissions',
                        'users_above_90_percent_submissions',
                    ),
                    (
                        'users_above_100_percent_submissions',
                        'users_above_100_percent_submissions',
                    ),
                    (
                        'users_above_80_percent_nlp_usage',
                        'users_above_80_percent_nlp_usage',
                    ),
                    (
                        'users_above_90_percent_nlp_usage',
                        'users_above_90_percent_nlp_usage',
                    ),
                    (
                        'users_above_100_percent_nlp_usage',
                        'users_above_100_percent_nlp_usage',
                    ),
                    ('test_users', 'test_users'),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
