# Generated by Django 5.2.14 on 2026-08-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_emails', '0010_alter_massemailconfig_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massemailrecord',
            name='status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('enqueued', 'Enqueued'),
                    ('failed', 'Failed'),
                    ('sent', 'Sent'),
                    ('stale', 'Stale'),
                ],
                null=True,
            ),
        ),
    ]
