# Generated by Django 3.2.15 on 2023-05-02 19:10

from django.db import migrations
import kpi.fields.kpi_uid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='uid',
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=kpi.fields.kpi_uid.KpiUidField(primary_key=True, serialize=False, uid_prefix='org'),
        ),
    ]
