# Generated by Django 3.2.15 on 2023-06-30 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_squashed_0004_remove_organization_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Email for pending invite', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
