# Generated by Django 3.2.15 on 2023-04-20 15:14

from django.db import migrations
import kpi.fields.kpi_uid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='uid',
            field=kpi.fields.kpi_uid.KpiUidField(uid_prefix='org-uid'),
        ),
    ]
