# Generated by Django 4.2.15 on 2024-10-22 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_squashed_0004_remove_organization_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mmo_override',
            field=models.BooleanField(
                default=False, verbose_name='Multi-members override'
            ),
        ),
    ]
