# Generated by Django 4.2.15 on 2024-10-25 16:08

from django.db import migrations
from django.core.paginator import Paginator


def update_organization_names(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    OrganizationUser = apps.get_model('organizations', 'OrganizationUser')

    page_size = 2000
    paginator = Paginator(
        OrganizationUser.objects.filter(organizationowner__isnull=False)
        .select_related('user', 'organization', 'user__extra_details')
        .order_by('pk'),
        page_size,
    )
    for page in paginator.page_range:
        organization_users = paginator.page(page).object_list
        organizations = []
        for organization_user in organization_users:
            user = organization_user.user
            organization = organization_user.organization
            if (
                organization.name
                and organization.name.strip() != ''
                and organization.name.startswith(user.username)
            ):
                try:
                    organization_name = user.extra_details.data['organization'].strip()
                except (KeyError, AttributeError):
                    continue

                if organization_name:
                    organization.name = organization_name
                    organizations.append(organization)

        if organizations:
            Organization.objects.bulk_update(organizations, ['name'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_add_mmo_override_field_to_organization'),
    ]

    operations = [migrations.RunPython(update_organization_names, noop)]
