# Generated by Django 4.2.15 on 2024-11-28 19:58
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_add_mmo_override_field_to_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(
                choices=[
                    ('non-profit', 'Non-profit organization'),
                    ('government', 'Government institution'),
                    ('educational', 'Educational organization'),
                    ('commercial', 'A commercial/for-profit company'),
                    ('none', 'I am not associated with any organization'),
                ],
                default='none',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(default='', max_length=255),
        ),
    ]
