# flake8: noqa: E501
# Generated by Django 4.2.15 on 2024-12-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_update_organization_name_website_and_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='mmo_override',
            field=models.BooleanField(
                default=False,
                verbose_name='Make organization multi-member (necessary for adding users)',
            ),
        ),
    ]
