# Generated by Django 5.2.14 on 2026-08-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'organizations',
            '0010_add_status_and_invitee_role_to_organization_invitation',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='EmptyOrganization',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organizations.organization',),
        ),
    ]
