# Generated by Django 2.2.7 on 2019-11-19 08:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_remove_formbuilder_preference_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationfile',
            name='content',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='configurationfile',
            name='slug',
            field=models.CharField(choices=[('logo', 'logo'), ('logo_small', 'logo_small'), ('login_background', 'login_background')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='perusersetting',
            name='name',
            field=models.CharField(default='INTERCOM_APP_ID', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='perusersetting',
            name='user_queries',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='A JSON representation of a *list* of Django queries, e.g. `[{"email__iendswith": "@kobotoolbox.org"}, {"email__iendswith": "@kbtdev.org"}]`. A matching user is one who would be returned by ANY of the queries in the list.'),
        ),
    ]
