# Generated by Django 2.2.7 on 2021-01-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_alter_jsonfield_to_jsonbfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusersetting',
            name='name',
            field=models.CharField(default='INTERCOM_APP_ID', max_length=255, unique=True),
        ),
    ]
