# Generated by Django 3.2.15 on 2023-04-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_add_uid_to_extra_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationfile',
            name='content',
            field=models.FileField(help_text='Stored in a PUBLIC location where authentication is NOT required for access', upload_to='__public/'),
        ),
        migrations.AlterField(
            model_name='perusersetting',
            name='name',
            field=models.CharField(default='INTERCOM_APP_ID', max_length=255, unique=True),
        ),
    ]
