# Generated by Django 3.2.15 on 2023-07-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_do_nothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauserdetail',
            name='private_data',
            field=models.JSONField(default=dict),
        ),
    ]
