# Generated by Django 4.2.24 on 2026-01-30 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0016_extrauserdetail_password_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='V1UserTracker',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('last_accessed_path', models.CharField(max_length=255)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='v1_user_tracker',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'v1_user_tracker',
            },
        ),
    ]
