# Generated by Django 4.2.28 on 2026-04-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0020_fix_constance_json_field_corruption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='V1UserTracker',
        ),
    ]
