# Generated by Django 4.2.28 on 2026-04-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0021_extra_user_detail_last_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='V1UserTracker',
        ),
    ]
