# Generated by Django 5.2.13 on 2026-07-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0022_delete_v1usertracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitewidemessage',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
