# Generated by Django 3.2.15 on 2022-11-29 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kpi.fields.kpi_uid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'assignment',
                'ordering': ['user', 'region'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentRegionM2M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', kpi.fields.kpi_uid.KpiUidField(uid_prefix='r')),
                ('name', models.CharField(max_length=200)),
                ('countries', models.JSONField(default=list)),
                ('permissions', models.JSONField(default=list)),
                ('assignments', models.ManyToManyField(related_name='assignments', through='regions.AssignmentRegionM2M', to='regions.Assignment')),
            ],
            options={
                'verbose_name': 'region',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='assignmentregionm2m',
            name='region_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.region'),
        ),
        migrations.AddField(
            model_name='assignmentregionm2m',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_region', to='regions.region'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
