# Generated by Django 4.2.24 on 2026-01-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_disclaimer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdisclaimer',
            name='hidden',
            field=models.BooleanField(
                default=False,
                verbose_name='Hide disclaimer for all languages of the form',
            ),
        ),
    ]
