openapi: 3.0.3
info:
  title: KoboToolbox API
  version: 2.0.0
  description: Powerful and intuitive data collection tools to make an impact
paths:
  /{username}/formList:
    get:
      operationId: form_list_anonymous
      description: |
        ## Implement part of the OpenRosa Form List API

        These endpoints are used for adding submissions, depending on the authenticated status of the user.

        Adding a submission as an anonymous user:
        `/{username}/formList`

        Adding a submission as an authenticated user:
        `/formList`


        ⚠️This endpoint is **only available** from the Kobocat domains (ex: kc.kobotoolbox.org or kc-eu.kobotoolbox.org)⚠️
      parameters:
      - in: path
        name: username
        schema:
          type: string
          pattern: ^\w+$
        required: true
      tags:
      - OpenRosa Form List
      security:
      - TokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/XFormList'
          description: null
  /{username}/submission:
    post:
      operationId: submission_anonymous
      description: |-
        Implements OpenRosa Api [FormSubmissionAPI](        https://bitbucket.org/javarosa/javarosa/wiki/FormSubmissionAPI)

        ## Submit an XML XForm submission

        <pre class="prettyprint">
        <b>POST</b> /api/v1/submissions</pre>
        > Example
        >
        >       curl -X POST -F xml_submission_file=@/path/to/submission.xml     https://example.com/api/v1/submissions

        ## Submit an JSON XForm submission

        <pre class="prettyprint">
        <b>POST</b> /api/v1/submissions</pre>
        > Example
        >
        >       curl -X POST -d '{"id": "[form ID]", "submission": [the JSON]}     http://localhost:8000/api/v1/submissions -u user:pass -H "Content-Type:     application/json"

        Here is some example JSON, it would replace `[the JSON]` above:
        >       {
        >           "transport": {
        >               "available_transportation_types_to_referral_facility":     ["ambulance", "bicycle"],
        >               "loop_over_transport_types_frequency": {
        >                   "ambulance": {
        >                       "frequency_to_referral_facility": "daily"
        >                   },
        >                   "bicycle": {
        >                       "frequency_to_referral_facility": "weekly"
        >                   },
        >                   "boat_canoe": null,
        >                   "bus": null,
        >                   "donkey_mule_cart": null,
        >                   "keke_pepe": null,
        >                   "lorry": null,
        >                   "motorbike": null,
        >                   "taxi": null,
        >                   "other": null
        >               }
        >           }
        >           "meta": {
        >               "instanceID": "uuid:f3d8dc65-91a6-4d0f-9e97-802128083390"
        >           }
        >       }
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - xml
      - in: path
        name: username
        schema:
          type: string
          pattern: ^\w+$
        required: true
      tags:
      - OpenRosa Form Submission
      security:
      - BasicAuth: []
      - TokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /{username}/xformsManifest/{id}:
    get:
      operationId: manifest_anonymous
      parameters:
      - in: path
        name: id
        schema:
          type: string
          pattern: ^[\d+^/]+$
        required: true
      - in: path
        name: username
        schema:
          type: string
          pattern: ^\w+$
        required: true
      tags:
      - OpenRosa Form Manifest
      security:
      - TokenAuth: []
      - {}
      responses:
        '200':
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/XFormList'
          description: ''
  /formList:
    get:
      operationId: form_list_authenticated
      description: |
        ## Implement part of the OpenRosa Form List API

        These endpoints are used for adding submissions, depending on the authenticated status of the user.

        Adding a submission as an anonymous user:
        `/{username}/formList`

        Adding a submission as an authenticated user:
        `/formList`


        ⚠️This endpoint is **only available** from the Kobocat domains (ex: kc.kobotoolbox.org or kc-eu.kobotoolbox.org)⚠️
      tags:
      - OpenRosa Form List
      security:
      - TokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/XFormList'
          description: null
  /submission:
    post:
      operationId: submission_authenticated
      description: |-
        Implements OpenRosa Api [FormSubmissionAPI](        https://bitbucket.org/javarosa/javarosa/wiki/FormSubmissionAPI)

        ## Submit an XML XForm submission

        <pre class="prettyprint">
        <b>POST</b> /api/v1/submissions</pre>
        > Example
        >
        >       curl -X POST -F xml_submission_file=@/path/to/submission.xml     https://example.com/api/v1/submissions

        ## Submit an JSON XForm submission

        <pre class="prettyprint">
        <b>POST</b> /api/v1/submissions</pre>
        > Example
        >
        >       curl -X POST -d '{"id": "[form ID]", "submission": [the JSON]}     http://localhost:8000/api/v1/submissions -u user:pass -H "Content-Type:     application/json"

        Here is some example JSON, it would replace `[the JSON]` above:
        >       {
        >           "transport": {
        >               "available_transportation_types_to_referral_facility":     ["ambulance", "bicycle"],
        >               "loop_over_transport_types_frequency": {
        >                   "ambulance": {
        >                       "frequency_to_referral_facility": "daily"
        >                   },
        >                   "bicycle": {
        >                       "frequency_to_referral_facility": "weekly"
        >                   },
        >                   "boat_canoe": null,
        >                   "bus": null,
        >                   "donkey_mule_cart": null,
        >                   "keke_pepe": null,
        >                   "lorry": null,
        >                   "motorbike": null,
        >                   "taxi": null,
        >                   "other": null
        >               }
        >           }
        >           "meta": {
        >               "instanceID": "uuid:f3d8dc65-91a6-4d0f-9e97-802128083390"
        >           }
        >       }
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - xml
      tags:
      - OpenRosa Form Submission
      security:
      - BasicAuth: []
      - TokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /xformsManifest/{id}:
    get:
      operationId: manifest_authenticated
      parameters:
      - in: path
        name: id
        schema:
          type: string
          pattern: ^[\d+^/]+$
        required: true
      tags:
      - OpenRosa Form Manifest
      security:
      - TokenAuth: []
      - {}
      responses:
        '200':
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/XFormList'
          description: ''
components:
  schemas:
    XFormList:
      type: array
      items:
        type: object
        properties:
          formID:
            type: string
          name:
            type: string
          majorMinorVersion:
            type: string
          version:
            type: string
          hash:
            type: string
          description:
            type: string
          downloadUrl:
            type: string
            format: uri
            example: https://kf.kobotoolbox.org/forms/6/form.xml
          manifestUrl:
            type: string
            format: uri
            example: https://kf.kobotoolbox.org/xformsManifest/6
        xml:
          name: xform
      xml:
        name: xforms
        wrapped: true
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    TokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Token-based authentication. Use the format: `Token <your-token>`'
