name: CI of releases

on:
  push:
    branches: [ 'release/**', 'kalvis/automated-release' ]

jobs:

  changes:
    runs-on: ubuntu-22.04
    permissions: { pull-requests: read }
    steps:
      - uses: actions/checkout@v4
      - id:   filter
        uses: dorny/paths-filter@v3
        name: Detect changed files
        with: { filters: .github/filters.yml }
    outputs:
      darker:   ${{ steps.filter.outputs.darker   }}
      pytest:   ${{ steps.filter.outputs.pytest   }}
      npm-test: ${{ steps.filter.outputs.npm-test }}

  darker:
    needs: changes
    if: needs.changes.outputs.darker == 'true'
    uses: ./.github/workflows/darker.yml

  pytest:
    needs: changes
    if: needs.changes.outputs.pytest == 'true'
    uses: ./.github/workflows/pytest.yml

  npm-test:
    needs: changes
    if: needs.changes.outputs.npm-test == 'true'
    uses: ./.github/workflows/npm-test.yml

  deploy-to-beta:
    runs-on: ubuntu-22.04
    needs:
      - darker
      - pytest
      - npm-test
    if: |
      !failure() &&
      (needs.darker.result == 'skipped' || needs.darker.result == 'success') &&
      (needs.pytest.result == 'skipped' || needs.pytest.result == 'success') &&
      (needs.npm-test.result == 'skipped' || needs.npm-test.result == 'success')
    steps:
    - uses: actions/checkout@v4
    - name: deploy to beta
      run: |
        echo 'TODO, for now deploy manually on kf.beta.kbtdev'

  merge:
    runs-on: ubuntu-22.04
    needs:
      - darker
      - pytest
      - npm-test
      - deploy-to-beta
    if: |
      !failure() &&
      (needs.darker.result == 'skipped' || needs.darker.result == 'success') &&
      (needs.pytest.result == 'skipped' || needs.pytest.result == 'success') &&
      (needs.npm-test.result == 'skipped' || needs.npm-test.result == 'success') &&
      needs.deploy-to-beta.result == 'success'
    steps:
    - uses: actions/checkout@v4
    - name: merge to main
      run: |
        echo 'TODO, lets test this later with a real release branch'


  on-failure:
    runs-on: ubuntu-22.04
    needs:
      - darker
      - pytest
      - npm-test
      - deploy-to-beta
      - merge
    if: |
      failure() &&
      (needs.darker.result == 'failure' || needs.darker.result == 'timed_out' ||
      needs.pytest.result == 'failure' || needs.pytest.result == 'timed_out' ||
      needs.npm-test.result == 'failure' || needs.npm-test.result == 'timed_out' ||
      needs.deploy-to-beta.result == 'failure' || needs.deploy-to-beta.result == 'timed_out' ||
      needs.merge.result == 'failure' || needs.merge.result == 'timed_out')
    steps:

    # References:
    # - https://stackoverflow.com/questions/73402042/github-action-expressions-split-string
    # - https://unix.stackexchange.com/questions/205022/bash-assigning-the-first-line-of-a-variable-to-a-variable#388712
    - name: Split commit message title
      id: title
      env:
        MESSAGE: ${{ github.event.commits[0].message }}
      run: echo "fragment=`echo "${MESSAGE}" | head -1`" >> $GITHUB_OUTPUT

    - name: Send a stream message
      uses: zulip/github-actions-zulip/send-message@v1
      with:
        api-key: ${{ secrets.ZULIP_API_KEY_GITHUB_ACTIONS_BOT }}
        email: "github-actions-bot@chat.kobotoolbox.org"
        organization-url: "https://chat.kobotoolbox.org"
        type: "stream"
        to: "Kobo Dev"
        topic: "Github Actions (releases)"
        content: ":warning: @_TODO_*devs*, [run #${{github.run_number}}](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}) failed on `${{ github.head_ref || github.ref_name }}` at [${{ toJson(steps.title.outputs.fragment) }}](${{ github.event.compare }})"
