name: Python linter (Darker)

on: [pull_request]
jobs:
  darker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
      - name: Install pip dependencies
        run: python -m pip install flake8 flake8-quotes isort
      - uses: akaihola/darker@master
        with:
          options: '--check --isort -L "flake8 --max-line-length=88"'
          revision: "origin/${{ github.event.pull_request.base.ref }}"
          version: "~=2.1.1"
