name: GHCR image cleanup

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  cleanup-old-images:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.KOBO_BOT_CLIENT_ID }}
          private-key: ${{ secrets.KOBO_BOT_PRIVATE_KEY }}
          owner: kobotoolbox

      - uses: snok/container-retention-policy@v3.0.1
        with:
          account: kobotoolbox
          token: ${{ steps.app-token.outputs.token }}
          image-names: kpi
          cut-off: 90d
          dry-run: true
