name: Create a Linear Issue

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      description:
        required: true
        type: string
    secrets:
      LINEAR_API_KEY_GITHUB_ACTIONS_BOT:
        required: true

jobs:
  linear:
    runs-on: ubuntu-22.04
    env:
      TEAM: ea750a9d-5a92-4fe2-a494-55fa114ba0dd
      TITLE: ${{ inputs.title }}
      DESCRIPTION: ${{ inputs.description }}
    steps:

    - name: create a linear issue
      uses: seripap/gh-linear-action@v1.0.3
      with:
        linear-key: ${{ secrets.LINEAR_API_KEY_GITHUB_ACTIONS_BOT }}
        linear-team-id: ea750a9d-5a92-4fe2-a494-55fa114ba0dd
        title: ${{ inputs.title }}
        body: ${{ inputs.description }}
