name: Update Translations

# See docs at `./locale/README.md`.

on:
  push:
    branches: [ "kalvis/transifex" ] # WIP for debugging
  workflow_call:


jobs:
  version:
    if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
    secrets: inherit
    uses: './.github/workflows/find-releases.yml'

  locale:
    needs:
      - version
    runs-on: ubuntu-24.04
    steps:

    ## Setup

    - uses: actions/checkout@v6
      with:
        submodules: true

    - uses: ./.github/actions/checkout-with-github-app-token
      with:
        app-id: ${{ secrets.KOBO_BOT_APP_ID }}
        private-key: ${{ secrets.KOBO_BOT_PRIVATE_KEY }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with: { cache-suffix: 'dev_requirements' }

    - name: Update Debian package lists
      run: sudo DEBIAN_FRONTEND=noninteractive apt-get -y update

    - name: Install Debian dependencies
      run: sudo DEBIAN_FRONTEND=noninteractive apt-get -y install gdal-bin gettext libproj-dev postgresql-client ffmpeg gcc libc-dev build-essential

    - name: Install Python dependencies
      run: uv pip sync --system dependencies/pip/dev_requirements.txt

    ## Testing

    - name: Extract translatable strings from Python code.
      run: python manage.py makemessages --locale en

    - name: Extract translatable strings from Javascript/Typescript code.
      run: python manage.py makemessages --locale en --domain djangojs

    - name: Abort if there are uncommitted translatable string changes.
      run: |
        git diff --stat
        echo 'see `./locale/README.md`. TL;DR: if this errors, run `./scripts/generate_locale.sh` locally.'
        git diff-index --exit-code HEAD
