name: 'CD: stabilize'

on:
  pull_request:
  push:
    branches: [ 'release/**' ]

jobs:

  changes:
    runs-on: ubuntu-24.04
    permissions: { pull-requests: read }
    steps:
      - uses: actions/checkout@v4
      - id:   filter
        uses: dorny/paths-filter@v3
        name: Detect changed files
        with: { filters: .github/filters.yml }
    outputs:
      all:      ${{ steps.filter.outputs.all      }}
      darker:   ${{ steps.filter.outputs.darker   }}
      biome:    ${{ steps.filter.outputs.biome    }}
      pytest:   ${{ steps.filter.outputs.pytest   }}
      npm-test: ${{ steps.filter.outputs.npm-test }}

  darker:
    needs: changes
    if: needs.changes.outputs.all == 'true' || needs.changes.outputs.darker == 'true'
    uses: ./.github/workflows/darker.yml

  biome:
    needs: changes
    if: needs.changes.outputs.all == 'true' || needs.changes.outputs.biome == 'true'
    uses: ./.github/workflows/biome.yml

  pytest:
    needs: changes
    if: needs.changes.outputs.all == 'true' || needs.changes.outputs.pytest == 'true'
    uses: ./.github/workflows/pytest.yml

  npm-test:
    needs: changes
    if: needs.changes.outputs.all == 'true' || needs.changes.outputs.npm-test == 'true'
    uses: ./.github/workflows/npm-test.yml

  version:
    needs:
      - darker
      - biome
      - pytest
      - npm-test
    if: ${{ !cancelled() && !failure() }}
    secrets: inherit
    uses: './.github/workflows/find_release_branch.yml'

  changelog:
    runs-on: ubuntu-24.04
    needs:
      - version
    if: ${{ !cancelled() && !failure() }}
    env:
      PREV_BRANCH: ${{ needs.version.outputs.prev_branch }}
      CURRENT_BRANCH: ${{ needs.version.outputs.current_branch }}
      CURRENT_TAG: ${{ needs.version.outputs.current_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Generate a token to trigger a workflow from a workflow
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.KOBO_BOT_APP_ID }}
          private-key: ${{ secrets.KOBO_BOT_PRIVATE_KEY }}
      - name: post to Gist a release draft
        run: |
          set -xe
          npx git-cliff -u $(git log --format=format:%H origin/$PREV_BRANCH..origin/$CURRENT_BRANCH | tail -1)..origin/$CURRENT_BRANCH --tag $CURRENT_TAG
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/gists \
            -d "{\"files\":{\"${CURRENT_TAG}.md\":{\"content\":$(jq -Rs . <CHANGELOG.md)}}}"
          rm CHANGELOG.md

  # deploy-to-beta:
  #   runs-on: ubuntu-24.04
  #   needs:
  #     - darker
  #     - pytest
  #     - npm-test
  #   if: ${{ !cancelled() && !failure() }}
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: deploy to beta
  #     run: |
  #       set -xe
  #       # TODO, lets test deploy to beta later with a real release branch
  #       git checkout -B public-beta
  #       git push -f --set-upstream origin public-beta

  # merge-forward:
  #   name: Merge forward
  #   runs-on: ubuntu-24.04
  #   needs:
  #     - github-app
  #     - changelog
  #     - deploy-to-beta
  #   if: ${{ !cancelled() && !failure() }}
  #   steps:
  #     - name: Generate a token to trigger a workflow from a workflow
  #       id: app-token
  #       uses: actions/create-github-app-token@v2
  #       with:
  #         app-id: ${{ secrets.KOBO_BOT_APP_ID }}
  #         private-key: ${{ secrets.KOBO_BOT_PRIVATE_KEY }}
  #
  #     - uses: actions/checkout@v4
  #       with:
  #         token: ${{ steps.app-token.outputs.token }}
  #         fetch-depth: "0"

  #     # https://github.com/actions/create-github-app-token?tab=readme-ov-file#configure-git-cli-for-an-apps-bot-user
  #     - name: Get GitHub App user id
  #       id: get-user-id
  #       env:
  #         GH_TOKEN: ${{ steps.app-token.outputs.token }}
  #       run: |
  #         echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
  #     - name: Set git name and email for the bot
  #       run: |
  #         git config --global user.name '${{ steps.app-token.outputs.slug }}[bot]'
  #         git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.slug }}[bot]@users.noreply.github.com'

  #     - name: Find next release branch
  #       id: branches
  #       run: ./.github/find_next_release_branch.sh

  #     - name: Merge
  #       run: |
  #         current_branch="${{ steps.branches.outputs.current_branch }}"
  #         next_branch="${{ steps.branches.outputs.next_branch }}"
  #         git checkout "${next_branch}"
  #         echo 'TODO: squash migrations, if any'
  #         git merge --no-ff "${current_branch}"
  #         git push

  # notify:
  #   needs:
  #     - version
  #     - deploy-to-beta
  #     - merge-forward
  #   if: ${{ !cancelled() && !failure() }}
  #   uses: './.github/workflows/zulip.yml'
  #   secrets: inherit
  #   with:
  #     topic: "${{ needs.version.outputs.current_tag }} release"
  #     content: ":working_on_it: Release branch updated, passed CI, deployed to beta, and merged forward. Please update release notes (TODO: automate)"

  # on-failure:
  #   needs:
  #     - version
  #     - darker
  #     - biome
  #     - pytest
  #     - npm-test
  #     - changelog
  #     - deploy-to-beta
  #     - merge-forward
  #     - notify
  #   if: ${{ !cancelled() && failure() }}
  #   secrets: inherit
  #   uses: './.github/workflows/zulip.yml'
  #   with:
  #     topic: "${{ needs.version.outputs.current_tag }} release"
  #     content: ":warning: @*devs*, [run #${{github.run_number}}](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}) failed on `${{ github.head_ref || github.ref_name }}` at [\"$COMMIT_TITLE\"](${{ github.event.compare }})"
