# Generated by Django 4.2.15 on 2025-08-21 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import kpi.fields.kpi_uid
import kpi.models.abstract_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectorGroup',
            fields=[
                (
                    'date_created',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'date_modified',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'uid',
                    kpi.fields.kpi_uid.KpiUidField(
                        _null=False, primary_key=True, uid_prefix='dcg'
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                (
                    'owner',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataCollector',
            fields=[
                (
                    'date_created',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'date_modified',
                    models.DateTimeField(
                        default=kpi.models.abstract_models._get_default_datetime
                    ),
                ),
                (
                    'uid',
                    kpi.fields.kpi_uid.KpiUidField(
                        _null=False, primary_key=True, uid_prefix='dc'
                    ),
                ),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('token', models.CharField(max_length=40)),
                (
                    'group',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='data_collectors',
                        to='data_collectors.datacollectorgroup',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
