# Generated by Django 3.2.15 on 2023-12-13 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kpi.fields.kpi_uid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', kpi.fields.kpi_uid.KpiUidField(_null=False, uid_prefix='poi')),
                ('status', models.CharField(choices=[('accepted', 'ACCEPTED'), ('cancelled', 'CANCELLED'), ('complete', 'COMPLETE'), ('declined', 'DECLINED'), ('failed', 'FAILED'), ('in_progress', 'IN PROGRESS'), ('pending', 'PENDING')], db_index=True, default='pending', max_length=11)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_ownership_responses', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_ownership_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project ownership transfer invite',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', kpi.fields.kpi_uid.KpiUidField(_null=False, uid_prefix='pot')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='kpi.asset')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='project_ownership.invite')),
            ],
            options={
                'verbose_name': 'project ownership transfer',
            },
        ),
        migrations.CreateModel(
            name='TransferStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('cancelled', 'CANCELLED'), ('failed', 'FAILED'), ('in_progress', 'IN PROGRESS'), ('pending', 'PENDING'), ('success', 'SUCCESS')], db_index=True, default='pending', max_length=11)),
                ('status_type', models.CharField(choices=[('attachments', 'ATTACHMENTS'), ('media_files', 'MEDIA_FILES'), ('global', 'GLOBAL'), ('submissions', 'SUBMISSIONS')], db_index=True, default='global', max_length=11)),
                ('error', models.TextField(null=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='project_ownership.transfer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transferstatus',
            constraint=models.UniqueConstraint(fields=('transfer', 'status_type'), name='uniq_transfer_status_type'),
        ),
    ]
