# Generated by Django 3.2.15 on 2023-12-05 20:41

from django.db import migrations, models
import kobo.apps.project_ownership.models.choices
import kobo.apps.project_ownership.models.transfer


class Migration(migrations.Migration):

    dependencies = [
        ('project_ownership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='async_task_statuses',
            field=models.JSONField(default=kobo.apps.project_ownership.models.choices.TransferAsyncTask.default_statuses_dict),
        ),
        migrations.AddField(
            model_name='transfer',
            name='errors',
            field=models.JSONField(default=kobo.apps.project_ownership.models.transfer.default_errors_dict),
        ),
    ]
