# Generated by Django 4.2.11 on 2024-07-24 06:52

from django.db import migrations, models
import kpi.models.abstract_models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ownership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='date_created',
            field=models.DateTimeField(default=kpi.models.abstract_models._get_default_datetime),
        ),
        migrations.AlterField(
            model_name='invite',
            name='date_modified',
            field=models.DateTimeField(default=kpi.models.abstract_models._get_default_datetime),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date_created',
            field=models.DateTimeField(default=kpi.models.abstract_models._get_default_datetime),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date_modified',
            field=models.DateTimeField(default=kpi.models.abstract_models._get_default_datetime),
        ),
        migrations.AlterField(
            model_name='transferstatus',
            name='date_created',
            field=models.DateTimeField(default=kpi.models.abstract_models._get_default_datetime),
        ),
        migrations.AlterField(
            model_name='transferstatus',
            name='date_modified',
            field=models.DateTimeField(default=kpi.models.abstract_models._get_default_datetime),
        ),
    ]
