# Generated by Django 4.2.15 on 2025-02-12 10:13

from django.db import migrations


def remove_old_task(apps, schema_editor):

    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')  # noqa
    PeriodicTask.objects.filter(
        task='kobo.apps.project_ownership.tasks.task_rescheduler'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            'project_ownership',
            '0002_alter_invite_date_created_alter_invite_date_modified_and_more',
        ),
    ]

    operations = [
        migrations.RunPython(remove_old_task, migrations.RunPython.noop),
    ]
