# Generated by Django 4.2.15 on 2024-11-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'project_ownership',
            '0003_remove_old_task',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgMembershipAutoInvite',
            fields=[],
            options={
                'verbose_name': 'auto-invite for user project transfer to organization',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project_ownership.invite',),
        ),
        migrations.AddField(
            model_name='invite',
            name='invite_type',
            field=models.CharField(
                choices=[
                    ('org-membership', 'Org Membership'),
                    ('org-ownership-transfer', 'Org Ownership Transfer'),
                    ('user-ownership-transfer', 'User Ownership Transfer'),
                ],
                default='user-ownership-transfer',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='transfer',
            name='invite_type',
            field=models.CharField(
                choices=[
                    ('org-membership', 'Org Membership'),
                    ('org-ownership-transfer', 'Org Ownership Transfer'),
                    ('user-ownership-transfer', 'User Ownership Transfer'),
                ],
                default='user-ownership-transfer',
                max_length=30,
            ),
        ),
    ]
