# Generated by Django 4.2.15 on 2025-09-17 17:45

from django.db import migrations, models
import django.db.models.deletion
import kpi.models.abstract_models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ownership', '0005_remove_deprecated_mark_stuck_tasks_as_failed_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferStatusError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=kpi.models.abstract_models._get_default_datetime)),
                ('date_modified', models.DateTimeField(default=kpi.models.abstract_models._get_default_datetime)),
                ('error', models.CharField()),
                ('transfer_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='project_ownership.transferstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
